export type SeedPrompt = {
  category: string;
  title: string;
  body: string;
  variables: string[];
  complexity: "Beginner" | "Intermediate" | "Advanced";
};

export const seedPrompts: SeedPrompt[] = [
  // ===================== Data Scientist =====================
  {
    category: "Data Scientist",
    title: "Exploratory Data Analysis Plan",
    body: "You are an experienced data scientist helping me plan a thorough exploratory data analysis.\nHere is my dataset: {{dataset_description}}.\nThe business goal I'm trying to support is: {{business_goal}}.\nPropose a structured EDA plan covering: data shape and types, missing value patterns, outlier detection approach, univariate and bivariate analysis steps, and any domain-specific checks worth running.\nFor each step, explain briefly why it matters for the stated business goal.\nOutput the plan as a numbered list grouped under clear headings, followed by a short paragraph on what to watch out for before moving to modeling.",
    variables: ["dataset_description", "business_goal"],
    complexity: "Beginner",
  },
  {
    category: "Data Scientist",
    title: "Feature Engineering Brainstorm",
    body: "Act as a senior data scientist specializing in feature engineering.\nI have a dataset described as: {{dataset_description}}, and I'm trying to predict {{target_variable}}.\nThe domain context is: {{domain_context}}.\nSuggest 10-15 candidate engineered features, grouping them into categories such as interaction terms, aggregations, time-based features, and domain-derived ratios.\nFor each feature, give the transformation logic in plain language and a one-line rationale for why it could improve predictive signal.\nFlag any features that risk data leakage and explain why, and present the final answer as a markdown table with columns: Feature, Logic, Rationale, Leakage Risk.",
    variables: ["dataset_description", "target_variable", "domain_context"],
    complexity: "Intermediate",
  },
  {
    category: "Data Scientist",
    title: "Statistical Test Selector",
    body: "You are a statistics consultant helping me choose the right test.\nMy research question is: {{research_question}}.\nThe data type involved is: {{data_type}}, and my sample size is approximately {{sample_size}}.\nRecommend the most appropriate statistical test(s), explaining the assumptions each requires (normality, independence, variance homogeneity, etc.) and how to check them.\nIf assumptions are likely violated given my sample size, suggest a non-parametric alternative.\nPresent your answer as: Recommended Test, Why It Fits, Assumptions to Verify, Alternative If Assumptions Fail, and a one-sentence explanation of how to interpret the p-value in this context.",
    variables: ["research_question", "data_type", "sample_size"],
    complexity: "Beginner",
  },
  {
    category: "Data Scientist",
    title: "ML Model Selection Advisor",
    body: "You are a machine learning consultant helping me choose a modeling approach.\nMy problem type is: {{problem_type}}.\nDataset size is approximately: {{dataset_size}}, and I have the following constraints: {{constraints}}.\nRecommend 3-4 candidate algorithms ranked by suitability, covering at least one simple baseline and one more complex option.\nFor each candidate, explain expected strengths, weaknesses, training/inference cost, and interpretability trade-offs given my constraints.\nEnd with a recommended starting point and a brief validation strategy (cross-validation scheme, key metrics) suited to this problem type.",
    variables: ["problem_type", "dataset_size", "constraints"],
    complexity: "Intermediate",
  },
  {
    category: "Data Scientist",
    title: "ML Pipeline Code Review",
    body: "You are a principal data scientist conducting a rigorous code review of an ML pipeline.\nHere is the pipeline code, written in {{language}}: {{pipeline_code}}.\nI'm specifically concerned about this performance or correctness issue: {{performance_issue}}.\nReview the code for data leakage, improper train/test separation, inefficient preprocessing, missing reproducibility controls (seeds, versioning), and scalability bottlenecks.\nFor each issue found, cite the relevant code section, explain the risk, and give a corrected code snippet.\nConclude with a prioritized action list (critical, moderate, nice-to-have) and note any monitoring you'd add before this goes to production.",
    variables: ["language", "pipeline_code", "performance_issue"],
    complexity: "Advanced",
  },
  {
    category: "Data Scientist",
    title: "A/B Test Experiment Design",
    body: "You are an experimentation lead designing a rigorous A/B test.\nMy hypothesis is: {{hypothesis}}.\nThe primary metric I care about is: {{metric}}, and the target user segment is: {{user_segment}}.\nDesign the experiment including: null and alternative hypotheses, required sample size considerations, randomization unit, guardrail metrics to monitor for unintended harm, minimum detectable effect reasoning, and test duration recommendation.\nAddress common pitfalls such as novelty effects, peeking problems, and segment interaction effects.\nOutput as a structured experiment brief with sections: Hypothesis, Design, Metrics, Risks & Guardrails, and Analysis Plan.",
    variables: ["hypothesis", "metric", "user_segment"],
    complexity: "Advanced",
  },
  {
    category: "Data Scientist",
    title: "Data Quality Audit Checklist",
    body: "You are a data quality specialist reviewing a dataset before it's used for analysis.\nDataset description: {{dataset_description}}.\nData source: {{data_source}}.\nGenerate a comprehensive data quality audit checklist covering completeness, consistency, accuracy, timeliness, uniqueness, and referential integrity.\nFor each dimension, list 2-3 specific checks I should run (with example queries or logic where relevant) and what a failing result would look like.\nEnd with a short severity-ranked summary of the top 5 checks most likely to reveal issues given this data source, and suggest how to document findings for stakeholders.",
    variables: ["dataset_description", "data_source"],
    complexity: "Intermediate",
  },

  // ===================== Managers =====================
  {
    category: "Managers",
    title: "1:1 Meeting Prep Assistant",
    body: "You are an experienced people manager helping me prepare for a 1:1.\nThe employee is {{employee_name}}.\nRecent context I should factor in: {{recent_context}}.\nTheir current goals are: {{goals}}.\nDraft a 1:1 agenda with 4-6 discussion points balancing career growth, current work blockers, and recognition of recent wins.\nInclude 3 open-ended questions I could ask to encourage them to talk more than me.\nFormat the output as: Opening Check-in, Discussion Topics, Questions to Ask, and Suggested Follow-ups.",
    variables: ["employee_name", "recent_context", "goals"],
    complexity: "Beginner",
  },
  {
    category: "Managers",
    title: "Performance Review Writer",
    body: "You are an HR-savvy manager writing a fair, specific, and well-evidenced performance review.\nEmployee: {{employee_name}}, Role: {{role}}.\nKey achievements this period: {{achievements}}.\nAreas for growth: {{growth_areas}}.\nWrite a performance review with sections: Summary, Strengths (with specific examples), Areas for Development (framed constructively, not punitively), and Goals for Next Period.\nUse a professional, balanced tone that avoids vague praise or criticism and ties feedback to observable behaviors and outcomes.\nKeep the total length appropriate for a formal review document, roughly 300-450 words.",
    variables: ["employee_name", "role", "achievements", "growth_areas"],
    complexity: "Intermediate",
  },
  {
    category: "Managers",
    title: "Meeting Agenda Builder",
    body: "You are a management consultant helping me run efficient meetings.\nThe meeting topic is: {{meeting_topic}}.\nAttendees: {{attendees}}.\nAllotted duration: {{duration}}.\nBuild a time-boxed agenda with clear objectives per section, a designated decision-maker note for each agenda item, and a suggested pre-read if useful.\nEnsure the agenda ends with explicit next steps and owners.\nOutput as a table with columns: Time, Topic, Objective, Owner.",
    variables: ["meeting_topic", "attendees", "duration"],
    complexity: "Beginner",
  },
  {
    category: "Managers",
    title: "Delegation Plan Builder",
    body: "You are a leadership coach helping me delegate effectively.\nThe task I want to delegate is: {{task_description}}.\nI'm delegating it to {{team_member_name}}, whose current skill level for this type of task is: {{skill_level}}.\nRecommend how much autonomy to grant (using a framework like directing/coaching/supporting/delegating), what checkpoints to set, and what context or resources I need to hand off up front.\nDraft a short delegation message I could send to this person that sets clear expectations, success criteria, and deadline without micromanaging.\nEnd with 2-3 risks to watch for given their skill level and how to mitigate them.",
    variables: ["task_description", "team_member_name", "skill_level"],
    complexity: "Intermediate",
  },
  {
    category: "Managers",
    title: "Conflict Resolution Conversation Script",
    body: "You are an experienced conflict-resolution coach for managers.\nHere's the situation: {{conflict_description}}.\nParties involved: {{parties_involved}}.\nThe outcome I'm hoping for is: {{desired_outcome}}.\nDraft a step-by-step conversation script I can use to mediate this, using a neutral, non-blaming tone that separates facts from interpretations.\nInclude specific phrases for opening the conversation, redirecting if it becomes accusatory, and summarizing agreements at the end.\nAlso list 3 warning signs that the conversation is going poorly and a recovery line for each, then suggest a follow-up check-in timeline.",
    variables: ["conflict_description", "parties_involved", "desired_outcome"],
    complexity: "Advanced",
  },
  {
    category: "Managers",
    title: "OKR Writer for Team Quarter",
    body: "You are a strategy consultant helping me write effective OKRs.\nTeam: {{team_name}}.\nQuarter: {{quarter}}.\nStrategic priority driving this: {{strategic_priority}}.\nDraft 2-3 Objectives, each with 3 measurable Key Results that are specific, time-bound, and ambitious but achievable.\nAvoid vanity metrics and ensure each Key Result has a clear baseline-to-target structure.\nOutput as a structured list per objective, followed by a short note on how to track progress weekly and what a 'stretch' vs 'committed' key result would look like here.",
    variables: ["team_name", "quarter", "strategic_priority"],
    complexity: "Intermediate",
  },
  {
    category: "Managers",
    title: "Difficult Feedback Conversation Prep",
    body: "You are an executive coach helping me prepare to deliver hard feedback.\nEmployee: {{employee_name}}.\nIssue to address: {{issue_description}}.\nRelationship context: {{relationship_context}}.\nHelp me structure this using a framework like SBI (Situation-Behavior-Impact) or similar, with specific example language I can adapt.\nAnticipate 2-3 likely defensive reactions and give me a calm, empathetic response for each that keeps the conversation focused on behavior and impact rather than character.\nEnd with how to close the conversation constructively, including a concrete next step and a way to check in without hovering.",
    variables: ["employee_name", "issue_description", "relationship_context"],
    complexity: "Advanced",
  },

  // ===================== Marketing =====================
  {
    category: "Marketing",
    title: "Campaign Copy Generator",
    body: "You are a senior marketing copywriter.\nProduct: {{product_name}}.\nTarget audience: {{target_audience}}.\nCampaign goal: {{campaign_goal}}.\nWrite 3 distinct headline options and a supporting paragraph of body copy for each, varying the emotional angle (urgency, aspiration, social proof) across the three.\nKeep the tone aligned to the target audience and make each option punchy enough for a landing page hero section.\nEnd with a one-line CTA suggestion for each variant.",
    variables: ["product_name", "target_audience", "campaign_goal"],
    complexity: "Beginner",
  },
  {
    category: "Marketing",
    title: "SEO Content Brief Generator",
    body: "You are an SEO content strategist.\nTarget keyword: {{target_keyword}}.\nTarget audience: {{target_audience}}.\nCompetitor URLs currently ranking: {{competitor_urls}}.\nCreate a detailed content brief including: recommended title tag and meta description, search intent analysis, a suggested H2/H3 outline that covers gaps competitors miss, target word count, internal linking suggestions, and 5-8 secondary keywords to weave in naturally.\nExplain briefly why this structure should outrank the current top results.\nFormat as a structured brief a writer could execute directly.",
    variables: ["target_keyword", "target_audience", "competitor_urls"],
    complexity: "Intermediate",
  },
  {
    category: "Marketing",
    title: "Social Media Content Calendar",
    body: "You are a social media strategist.\nBrand: {{brand_name}}.\nPlatform: {{platform}}.\nCampaign theme: {{campaign_theme}}.\nDuration: {{duration}}.\nBuild a content calendar with a post idea for each day, varying formats (image, short video, carousel, poll, UGC repost) and including a suggested caption angle and hashtag strategy per post.\nEnsure the mix balances promotional, educational, and engagement-driven content roughly in a 20/50/30 split.\nOutput as a table with columns: Day, Format, Caption Angle, Goal.",
    variables: ["brand_name", "platform", "campaign_theme", "duration"],
    complexity: "Beginner",
  },
  {
    category: "Marketing",
    title: "Competitor Analysis Report",
    body: "You are a competitive intelligence analyst for marketing.\nMy company: {{company_name}}.\nCompetitors to analyze: {{competitor_names}}.\nIndustry: {{industry}}.\nProduce a structured competitor analysis covering positioning, messaging themes, pricing signals, content strategy, and apparent target audience for each competitor.\nIdentify white space or differentiation opportunities my company could exploit, and flag any competitive threats I should be aware of.\nOutput as a comparison table followed by a strategic recommendations section with 3-5 concrete action items.",
    variables: ["company_name", "competitor_names", "industry"],
    complexity: "Advanced",
  },
  {
    category: "Marketing",
    title: "Lifecycle Email Sequence Writer",
    body: "You are a lifecycle marketing specialist.\nProduct: {{product_name}}.\nFunnel stage: {{funnel_stage}}.\nTarget audience: {{target_audience}}.\nWrite a 4-email sequence appropriate for this funnel stage, with each email having a distinct goal (e.g., education, objection-handling, social proof, urgency/close).\nFor each email, provide subject line, preview text, body copy, and CTA, keeping the tone conversational and benefit-focused rather than feature-heavy.\nEnd with recommended send-timing intervals between emails and one A/B test idea for the sequence.",
    variables: ["product_name", "funnel_stage", "target_audience"],
    complexity: "Intermediate",
  },
  {
    category: "Marketing",
    title: "Ad Copy A/B Test Variants",
    body: "You are a performance marketing copywriter.\nProduct: {{product_name}}.\nPlatform: {{platform}}.\nUnique selling point: {{unique_selling_point}}.\nGenerate 5 short ad copy variants suited to this platform's format constraints, each testing a different hook (problem-agitation, curiosity, direct offer, testimonial-style, comparison).\nKeep character counts realistic for the platform and include a CTA button label suggestion for each.\nPresent as a table with columns: Variant, Hook Type, Copy, CTA.",
    variables: ["product_name", "platform", "unique_selling_point"],
    complexity: "Beginner",
  },
  {
    category: "Marketing",
    title: "Brand Messaging Framework Builder",
    body: "You are a brand strategist building a foundational messaging framework.\nBrand: {{brand_name}}.\nTarget audience: {{target_audience}}.\nCore values: {{core_values}}.\nDevelop a messaging framework including: brand positioning statement, value proposition, 3 core message pillars each with supporting proof points, tone-of-voice guidelines (with 3 dos and don'ts), and an elevator pitch of 2-3 sentences.\nEnsure the framework is differentiated, memorable, and consistent with the stated core values.\nOutput in clearly labeled sections so it can be used as an internal reference document.",
    variables: ["brand_name", "target_audience", "core_values"],
    complexity: "Advanced",
  },

  // ===================== UI/UX Developers =====================
  {
    category: "UI/UX Developers",
    title: "UI Design Critique",
    body: "You are a senior product designer giving a constructive design critique.\nScreen description: {{screen_description}}.\nTarget users: {{target_users}}.\nDesign goal: {{design_goal}}.\nEvaluate the screen against visual hierarchy, information density, affordance clarity, and consistency with common platform conventions.\nFor each issue identified, explain the underlying UX principle being violated and give a concrete fix suggestion.\nStructure the critique as: What Works, What Needs Improvement (ranked by impact), and Quick Wins vs Larger Redesign Items.",
    variables: ["screen_description", "target_users", "design_goal"],
    complexity: "Intermediate",
  },
  {
    category: "UI/UX Developers",
    title: "Accessibility Audit (WCAG)",
    body: "You are an accessibility specialist conducting a WCAG-based audit.\nComponent description: {{component_description}}.\nTarget conformance level: {{wcag_level}}.\nTech stack: {{tech_stack}}.\nAudit the component against relevant success criteria for color contrast, keyboard navigation, focus management, ARIA roles/labels, and screen reader announcements.\nFor each issue, cite the specific WCAG criterion, explain the user impact, and provide a code-level fix suggestion appropriate for the given tech stack.\nEnd with a prioritized remediation list (blocker, serious, moderate) and a suggested testing method (manual, automated tool, or assistive tech) for verifying each fix.",
    variables: ["component_description", "wcag_level", "tech_stack"],
    complexity: "Advanced",
  },
  {
    category: "UI/UX Developers",
    title: "Component API Design Review",
    body: "You are a design systems engineer designing a component's public API.\nComponent: {{component_name}}.\nKey use cases it must support: {{use_cases}}.\nFramework: {{framework}}.\nPropose a prop/API surface (names, types, defaults) that is flexible enough for the listed use cases but avoids prop bloat or ambiguous overlapping options.\nExplain your naming conventions and any composition patterns (e.g., slots, render props, compound components) you'd use instead of adding more flags.\nEnd with 2-3 anti-patterns consumers might attempt and how the API design prevents or discourages them.",
    variables: ["component_name", "use_cases", "framework"],
    complexity: "Intermediate",
  },
  {
    category: "UI/UX Developers",
    title: "Design System Documentation Writer",
    body: "You are a design systems documentation specialist.\nComponent: {{component_name}}.\nAvailable design tokens: {{design_tokens}}.\nFramework: {{framework}}.\nWrite documentation for this component including: purpose and when to use it, anatomy/visual breakdown, usage guidelines (do's and don'ts with rationale), accessibility notes, and a code usage example referencing the given tokens.\nKeep the tone clear and instructional for both designers and engineers reading the same page.\nFormat with markdown headings matching a typical design system site structure.",
    variables: ["component_name", "design_tokens", "framework"],
    complexity: "Intermediate",
  },
  {
    category: "UI/UX Developers",
    title: "User Flow Drop-off Analysis",
    body: "You are a UX researcher analyzing a problematic user flow.\nFlow description: {{flow_description}}.\nUser goal: {{user_goal}}.\nKnown drop-off point: {{drop_off_point}}.\nHypothesize the top 5 likely causes of drop-off at this point, drawing on common UX friction patterns (cognitive load, trust signals, unclear next steps, form friction, performance).\nFor each hypothesis, suggest a lightweight way to validate it (heuristic review, session replay, micro-survey) and a corresponding design intervention to test.\nOutput as a table: Hypothesis, Likely Cause Category, Validation Method, Proposed Fix.",
    variables: ["flow_description", "user_goal", "drop_off_point"],
    complexity: "Advanced",
  },
  {
    category: "UI/UX Developers",
    title: "UI Microcopy Improver",
    body: "You are a UX writer refining interface microcopy.\nUI element: {{ui_element}}.\nCurrent copy: {{current_copy}}.\nDesired tone: {{tone}}.\nRewrite the copy 3 different ways that match the desired tone while staying clear, concise, and action-oriented.\nExplain briefly what was weak about the original copy (vague, jargon-heavy, passive, etc.).\nPresent as a simple before/after list with a one-line rationale per option.",
    variables: ["ui_element", "current_copy", "tone"],
    complexity: "Beginner",
  },
  {
    category: "UI/UX Developers",
    title: "Wireframe to Developer Spec Translator",
    body: "You are a UX engineer translating a wireframe into an implementation-ready spec.\nWireframe description: {{wireframe_description}}.\nTarget platform: {{platform}}.\nProduce a developer-facing spec covering: component breakdown, layout/spacing behavior, responsive behavior across breakpoints, interaction states (hover, active, disabled, loading, error), and any edge cases (empty states, long text truncation).\nKeep the spec unambiguous enough that a developer unfamiliar with the design intent could implement it correctly.\nOutput as a structured list grouped by component.",
    variables: ["wireframe_description", "platform"],
    complexity: "Beginner",
  },

  // ===================== Full Stack Developers =====================
  {
    category: "Full Stack Developers",
    title: "Focused Code Review Request",
    body: "You are a senior full-stack engineer performing a thorough code review.\nHere is the code, written in {{language}}: {{code_snippet}}.\nI'm particularly concerned about: {{concern_area}}.\nReview for correctness bugs, edge cases, security issues, readability, and adherence to idiomatic patterns for this language.\nFor each issue, quote the relevant line(s), explain the risk, and provide a corrected snippet.\nEnd with a summary rating (blocker / should-fix / nitpick counts) and one suggestion for a follow-up test to add.",
    variables: ["language", "code_snippet", "concern_area"],
    complexity: "Intermediate",
  },
  {
    category: "Full Stack Developers",
    title: "REST/GraphQL API Design Review",
    body: "You are a principal engineer reviewing an API design before implementation.\nAPI description: {{api_description}}.\nPrimary use cases: {{use_cases}}.\nConstraints: {{constraints}}.\nEvaluate the proposed design for resource modeling, naming consistency, versioning strategy, error response shape, pagination approach, and idempotency of mutating operations.\nRecommend concrete improvements with example request/response payloads where useful.\nEnd with a short section on backward-compatibility risks if this API evolves later.",
    variables: ["api_description", "use_cases", "constraints"],
    complexity: "Advanced",
  },
  {
    category: "Full Stack Developers",
    title: "Systematic Debugging Methodology Guide",
    body: "You are a debugging expert walking me through a systematic troubleshooting process.\nBug description: {{bug_description}}.\nTech stack: {{tech_stack}}.\nError message: {{error_message}}.\nGuide me through a structured debugging approach: reproduce reliably, isolate the smallest failing case, form 3 plausible hypotheses ranked by likelihood, and suggest a specific diagnostic step for each (logging, breakpoint, binary search over commits, etc.).\nExplain what the error message is actually telling us given this tech stack.\nEnd with a checklist I can follow step by step until the root cause is found.",
    variables: ["bug_description", "tech_stack", "error_message"],
    complexity: "Beginner",
  },
  {
    category: "Full Stack Developers",
    title: "Codebase Refactoring Plan",
    body: "You are a staff engineer planning a safe, incremental refactor.\nCodebase description: {{codebase_description}}.\nLanguage: {{language}}.\nKnown pain points: {{pain_points}}.\nPropose a phased refactoring plan that minimizes risk: identify seams for introducing tests before refactoring, suggest an order of operations, and call out any patterns (god objects, tight coupling, missing abstractions) driving the pain points.\nFor each phase, note the expected effort level and the risk of regressions.\nEnd with how you'd validate each phase didn't break existing behavior (test coverage strategy, feature flags, canary rollout).",
    variables: ["codebase_description", "language", "pain_points"],
    complexity: "Advanced",
  },
  {
    category: "Full Stack Developers",
    title: "Test Strategy Builder",
    body: "You are a QA-minded senior engineer designing a test strategy for a new feature.\nFeature description: {{feature_description}}.\nTech stack: {{tech_stack}}.\nKnown risk areas: {{risk_areas}}.\nPropose a test pyramid appropriate for this feature: what to cover with unit tests, integration tests, and end-to-end tests, with concrete example test case names for each layer.\nPrioritize test cases addressing the stated risk areas first.\nEnd with recommended tooling for this tech stack and a note on how to keep the test suite fast and reliable (avoiding flakiness).",
    variables: ["feature_description", "tech_stack", "risk_areas"],
    complexity: "Intermediate",
  },
  {
    category: "Full Stack Developers",
    title: "Database Schema Design",
    body: "You are a database architect designing a schema from requirements.\nDomain description: {{domain_description}}.\nExpected scale: {{expected_scale}}.\nCommon query patterns: {{query_patterns}}.\nDesign a normalized relational schema (tables, key columns, relationships) that supports the query patterns efficiently, and note where denormalization or indexing would be justified given the expected scale.\nInclude the primary/foreign key structure and suggest indexes for the hottest queries.\nEnd with 2-3 trade-offs you made and what would change if scale were 10x higher.",
    variables: ["domain_description", "expected_scale", "query_patterns"],
    complexity: "Advanced",
  },
  {
    category: "Full Stack Developers",
    title: "Architecture Decision Record Writer",
    body: "You are a software architect documenting a major technical decision.\nDecision context: {{decision_context}}.\nOptions considered: {{options_considered}}.\nConstraints: {{constraints}}.\nWrite a formal Architecture Decision Record (ADR) with sections: Context, Decision Drivers, Options Considered (with pros/cons for each), Decision, and Consequences (both positive and negative).\nBe explicit about trade-offs rather than presenting the chosen option as strictly superior.\nKeep the tone neutral and suitable for a technical audience reading this months later without full context.",
    variables: ["decision_context", "options_considered", "constraints"],
    complexity: "Advanced",
  },
  {
    category: "Full Stack Developers",
    title: "Performance Bottleneck Analysis",
    body: "You are a performance engineer diagnosing a slow system.\nSystem description: {{system_description}}.\nObserved symptom: {{bottleneck_symptom}}.\nTech stack: {{tech_stack}}.\nWalk through a structured diagnosis: likely bottleneck categories (network, database, CPU-bound computation, memory/GC pressure, N+1 queries, unindexed queries) ranked by probability given the symptom.\nFor each, suggest a specific profiling or measurement technique appropriate for this tech stack.\nEnd with 3 concrete optimization approaches once the bottleneck is confirmed, and how to verify the fix actually improved things without introducing regressions.",
    variables: ["system_description", "bottleneck_symptom", "tech_stack"],
    complexity: "Intermediate",
  },

  // ===================== Mobile App Development =====================
  {
    category: "Mobile App Development",
    title: "React Native Component Builder",
    body: "You are a senior React Native engineer.\nComponent purpose: {{component_purpose}}.\nTarget platform: {{platform_target}}.\nState management approach: {{state_management}}.\nWrite a well-structured React Native component (functional, with hooks) that fulfills this purpose, handling loading, error, and empty states.\nUse the specified state management approach idiomatically and add comments explaining non-obvious platform-specific handling if relevant.\nEnd with a short note on how you'd test this component and any performance considerations for lists or re-renders.",
    variables: ["component_purpose", "platform_target", "state_management"],
    complexity: "Intermediate",
  },
  {
    category: "Mobile App Development",
    title: "Flutter State Management Advisor",
    body: "You are a Flutter architecture consultant.\nApp description: {{app_description}}.\nState complexity: {{state_complexity}}.\nTeam size: {{team_size}}.\nRecommend a state management approach (Provider, Riverpod, Bloc, GetX, etc.) best suited to this complexity and team size, explaining the trade-offs versus the alternatives.\nOutline how state would be structured for a representative feature in this app, including how you'd separate business logic from UI.\nEnd with onboarding considerations for the team size given, since some approaches have steeper learning curves.",
    variables: ["app_description", "state_complexity", "team_size"],
    complexity: "Advanced",
  },
  {
    category: "Mobile App Development",
    title: "iOS Performance Profiling Guide",
    body: "You are an iOS performance specialist.\nApp feature experiencing issues: {{app_feature}}.\nPerformance symptom: {{performance_symptom}}.\niOS version: {{ios_version}}.\nGuide me through profiling this using Instruments (Time Profiler, Allocations, Core Animation as relevant), explaining what signals to look for given the symptom.\nSuggest the top 3 likely root causes for this kind of symptom on this iOS version (e.g., main thread blocking, retain cycles, offscreen rendering).\nEnd with concrete Swift-level remediation patterns for each likely cause and how to confirm improvement after the fix.",
    variables: ["app_feature", "performance_symptom", "ios_version"],
    complexity: "Advanced",
  },
  {
    category: "Mobile App Development",
    title: "App Store Listing Optimizer",
    body: "You are an App Store Optimization (ASO) specialist.\nApp name: {{app_name}}.\nTarget audience: {{target_audience}}.\nKey features: {{key_features}}.\nWrite an optimized app store listing including: title and subtitle suggestions within character limits, a benefit-led short description, a longer description structured with feature bullets, and 5-8 relevant keywords.\nFocus copy on outcomes for the target audience rather than just listing features.\nEnd with 2 screenshot caption ideas that would strengthen the listing's conversion.",
    variables: ["app_name", "target_audience", "key_features"],
    complexity: "Beginner",
  },
  {
    category: "Mobile App Development",
    title: "Offline-First Architecture Design",
    body: "You are a mobile architecture consultant specializing in offline-first apps.\nApp description: {{app_description}}.\nSync requirements: {{sync_requirements}}.\nTarget platform: {{platform}}.\nDesign an offline-first architecture covering local storage choice, sync strategy (queue-based, conflict resolution approach, last-write-wins vs CRDT-style merging), and how to handle partial connectivity gracefully in the UI.\nAddress how you'd detect and resolve sync conflicts given the stated requirements.\nEnd with a short list of edge cases to test explicitly (app killed mid-sync, clock skew, duplicate submissions).",
    variables: ["app_description", "sync_requirements", "platform"],
    complexity: "Advanced",
  },
  {
    category: "Mobile App Development",
    title: "Kotlin/Android Code Review",
    body: "You are a senior Android engineer performing a code review.\nCode snippet: {{code_snippet}}.\nTarget Android version: {{android_version}}.\nConcern area: {{concern_area}}.\nReview for lifecycle-awareness issues, coroutine misuse, memory leaks (context references, unregistered listeners), and idiomatic Kotlin style.\nFor each issue found, explain the risk in the context of the given Android version and provide a corrected snippet.\nEnd with a short list of relevant lint rules or static analysis checks that would have caught this automatically.",
    variables: ["code_snippet", "android_version", "concern_area"],
    complexity: "Intermediate",
  },
  {
    category: "Mobile App Development",
    title: "Push Notification Strategy",
    body: "You are a mobile growth and engagement specialist.\nApp name: {{app_name}}.\nUse case for notifications: {{use_case}}.\nTarget audience: {{target_audience}}.\nDesign a push notification strategy including: notification types needed, ideal timing/frequency guardrails to avoid fatigue, example copy for 3 notification variants, and a simple opt-in/permission-request approach that maximizes acceptance.\nExplain how you'd segment the audience so notifications feel relevant rather than generic.\nEnd with 2 metrics to track to know if the strategy is working versus annoying users.",
    variables: ["app_name", "use_case", "target_audience"],
    complexity: "Beginner",
  },

  // ===================== Github Commands =====================
  {
    category: "Github Commands",
    title: "Rebase Strategy Explainer",
    body: "You are a git expert helping me choose and execute the right rebase strategy.\nBranch: {{branch_name}}.\nBase branch: {{base_branch}}.\nScenario: {{scenario_description}}.\nExplain whether an interactive rebase, a standard rebase, or a merge would be more appropriate here, and why.\nProvide the exact sequence of git commands to run, explaining what each command does and what to expect at each step (including how to handle conflicts if they arise).\nEnd with how to safely force-push afterward and a warning about coordinating with collaborators if this branch is shared.",
    variables: ["branch_name", "base_branch", "scenario_description"],
    complexity: "Intermediate",
  },
  {
    category: "Github Commands",
    title: "Merge Conflict Resolution Guide",
    body: "You are a git mentor helping me resolve a merge conflict calmly and correctly.\nConflicting files: {{conflicting_files}}.\nBranch: {{branch_name}}.\nConflict description: {{conflict_description}}.\nExplain how to read the conflict markers, decide which changes to keep (or how to combine them), and the exact git commands to stage the resolution and continue the merge or rebase.\nInclude how to abort safely if I want to start over.\nEnd with a short tip on preventing this type of conflict in the future (e.g., smaller PRs, more frequent rebasing).",
    variables: ["conflicting_files", "branch_name", "conflict_description"],
    complexity: "Beginner",
  },
  {
    category: "Github Commands",
    title: "Commit Message Writer",
    body: "You are a git best-practices coach.\nChange description: {{change_description}}.\nChange type: {{change_type}}.\nWrite a well-formed commit message following conventional commit style, with a concise imperative-mood subject line under 50 characters and a body explaining the why (not just the what) in 2-4 sentences.\nInclude a footer noting any breaking change or issue reference if relevant to this change type.\nGive me the final message ready to paste into git commit -m.",
    variables: ["change_description", "change_type"],
    complexity: "Beginner",
  },
  {
    category: "Github Commands",
    title: "Branch Protection Rules Explainer",
    body: "You are a DevOps/release engineering consultant.\nRepository: {{repo_name}}.\nTeam size: {{team_size}}.\nCompliance requirement: {{compliance_requirement}}.\nRecommend a branch protection configuration for this repo's main branch(es), covering required status checks, required reviewers, dismiss-stale-review settings, linear history requirements, and signed commits if relevant to the compliance requirement.\nExplain the reasoning behind each setting given the team size.\nEnd with the exact settings to configure in GitHub's branch protection UI or via the API, listed step by step.",
    variables: ["repo_name", "team_size", "compliance_requirement"],
    complexity: "Intermediate",
  },
  {
    category: "Github Commands",
    title: "Git History Cleanup Plan",
    body: "You are a senior engineer specializing in git history hygiene.\nRepository description: {{repo_description}}.\nProblem to fix: {{problem_description}}.\nBranch affected: {{branch_name}}.\nRecommend the safest approach to clean this up (interactive rebase to squash/reorder, filter-repo to remove sensitive data, or git reset for local-only fixes), explaining why given the problem described.\nProvide the exact command sequence, including any necessary backup steps before running destructive operations.\nEnd with how to communicate this history change to collaborators and what they need to do locally afterward (e.g., re-cloning or resetting their branch).",
    variables: ["repo_description", "problem_description", "branch_name"],
    complexity: "Advanced",
  },
  {
    category: "Github Commands",
    title: "Pull Request Description Generator",
    body: "You are a technical writer specializing in clear PR descriptions.\nChange summary: {{change_summary}}.\nTicket reference: {{ticket_reference}}.\nWrite a PR description with sections: Summary, What Changed, Why, How to Test, and Related Ticket.\nKeep the summary concise (2-3 sentences) and the 'What Changed' section as a scannable bullet list.\nEnd with a checklist reviewers can use (tests added, docs updated, no breaking changes) formatted as GitHub-flavored markdown checkboxes.",
    variables: ["change_summary", "ticket_reference"],
    complexity: "Beginner",
  },
  {
    category: "Github Commands",
    title: "GitHub Actions Workflow Designer",
    body: "You are a CI/CD engineer designing a GitHub Actions workflow.\nProject type: {{project_type}}.\nCI requirements: {{ci_requirements}}.\nDeployment target: {{deployment_target}}.\nDesign a workflow YAML covering triggers, job structure (build, test, lint stages run in parallel where possible), caching strategy for dependencies, and a deployment job gated on the previous jobs passing.\nExplain key design choices such as matrix builds if relevant and how secrets should be referenced securely.\nProvide the complete workflow YAML plus a short explanation of how to extend it later.",
    variables: ["project_type", "ci_requirements", "deployment_target"],
    complexity: "Advanced",
  },

  // ===================== Azure =====================
  {
    category: "Azure",
    title: "Azure RBAC Policy Review",
    body: "You are a cloud security engineer specializing in Azure IAM.\nResource description: {{resource_description}}.\nRoles involved: {{roles_involved}}.\nCompliance requirement: {{compliance_requirement}}.\nReview the described access setup against least-privilege principles, identifying any overly broad role assignments (e.g., Owner/Contributor where a custom or built-in narrower role would suffice).\nRecommend a specific RBAC structure (built-in roles, custom role definitions, and scope levels: management group, subscription, resource group, resource) that satisfies the compliance requirement.\nEnd with a short note on how to audit this on an ongoing basis using Azure Policy or Access Reviews.",
    variables: ["resource_description", "roles_involved", "compliance_requirement"],
    complexity: "Advanced",
  },
  {
    category: "Azure",
    title: "Bicep/ARM Template Generator",
    body: "You are an Azure infrastructure-as-code specialist.\nResource type to provision: {{resource_type}}.\nEnvironment: {{environment}}.\nConfiguration details: {{configuration_details}}.\nGenerate a Bicep template that provisions this resource with sensible defaults, parameterizing values that should differ across environments.\nInclude comments explaining non-obvious settings and any dependent resources it needs (networking, identity, diagnostics settings).\nEnd with the az cli command to deploy this template and how to validate it with a what-if deployment first.",
    variables: ["resource_type", "environment", "configuration_details"],
    complexity: "Intermediate",
  },
  {
    category: "Azure",
    title: "Azure Cost Optimization Analysis",
    body: "You are a FinOps consultant specializing in Azure cost optimization.\nAzure services in use: {{azure_services_used}}.\nCurrent monthly spend: {{monthly_spend}}.\nUsage pattern: {{usage_pattern}}.\nAnalyze likely cost drivers given this usage pattern and recommend concrete optimization levers: right-sizing, reserved instances/savings plans, autoscaling, storage tiering, and eliminating idle resources.\nEstimate the rough percentage savings potential for each recommendation and rank them by effort-to-impact ratio.\nEnd with a suggested cadence for reviewing cost anomalies going forward (e.g., using Azure Cost Management alerts).",
    variables: ["azure_services_used", "monthly_spend", "usage_pattern"],
    complexity: "Intermediate",
  },
  {
    category: "Azure",
    title: "Azure App Service Architecture Design",
    body: "You are a cloud solutions architect designing an Azure-based application architecture.\nApp description: {{app_description}}.\nExpected traffic: {{expected_traffic}}.\nBudget constraint: {{budget_constraint}}.\nDesign an architecture using appropriate Azure services (App Service plan tier, Azure SQL/Cosmos DB, Front Door/CDN, Application Insights, Key Vault) that meets the traffic expectations within budget.\nExplain the scaling strategy (auto-scale rules) and how you'd keep costs predictable at this traffic level.\nEnd with a simple architecture diagram described in text/ASCII and 2-3 trade-offs made to stay within budget.",
    variables: ["app_description", "expected_traffic", "budget_constraint"],
    complexity: "Advanced",
  },
  {
    category: "Azure",
    title: "Azure DevOps Pipeline Troubleshooting",
    body: "You are an Azure DevOps specialist helping debug a failing pipeline.\nPipeline error: {{pipeline_error}}.\nFailing stage: {{pipeline_stage}}.\nTech stack: {{tech_stack}}.\nDiagnose the most likely causes of this error given the stage and tech stack (permissions, missing variables/secrets, agent pool mismatch, dependency resolution failure).\nSuggest the exact YAML or configuration change to fix the most likely cause, and a fallback diagnostic step if that doesn't resolve it.\nEnd with how to add better logging or diagnostics to this stage so future failures are easier to triage.",
    variables: ["pipeline_error", "pipeline_stage", "tech_stack"],
    complexity: "Beginner",
  },
  {
    category: "Azure",
    title: "Azure Functions vs App Service Advisor",
    body: "You are an Azure compute options advisor.\nWorkload description: {{workload_description}}.\nScaling needs: {{scaling_needs}}.\nCompare Azure Functions (consumption vs premium plan) against App Service for this workload, weighing cold-start behavior, cost model, and operational simplicity given the scaling needs.\nRecommend the best fit with clear reasoning, and note when I'd want to revisit this decision as the workload grows.\nEnd with one concrete next step to prototype the recommended option quickly.",
    variables: ["workload_description", "scaling_needs"],
    complexity: "Beginner",
  },
  {
    category: "Azure",
    title: "Azure AD Conditional Access Design",
    body: "You are an identity security architect specializing in Azure AD (Entra ID).\nOrganization size: {{organization_size}}.\nSecurity requirement: {{security_requirement}}.\nUser groups affected: {{user_groups}}.\nDesign a conditional access policy set that satisfies the security requirement while minimizing friction for the user groups given, covering MFA enforcement conditions, device compliance requirements, location-based restrictions, and sign-in risk-based controls.\nExplain the order in which policies should be evaluated and how to avoid unintentional lockouts (break-glass account guidance).\nEnd with a rollout plan (report-only mode first, then staged enforcement) appropriate for this organization size.",
    variables: ["organization_size", "security_requirement", "user_groups"],
    complexity: "Advanced",
  },

  // ===================== AWS =====================
  {
    category: "AWS",
    title: "AWS IAM Policy Review",
    body: "You are a cloud security engineer specializing in AWS IAM.\nResource description: {{resource_description}}.\nRoles involved: {{roles_involved}}.\nCompliance requirement: {{compliance_requirement}}.\nReview the described access setup for least-privilege violations (wildcard actions/resources, overly permissive trust policies) and recommend a scoped IAM policy structure using specific actions, resources, and conditions.\nAddress how this satisfies the stated compliance requirement.\nEnd with how to validate the policy using IAM Access Analyzer or policy simulator before deploying it.",
    variables: ["resource_description", "roles_involved", "compliance_requirement"],
    complexity: "Advanced",
  },
  {
    category: "AWS",
    title: "Terraform Module Generator (AWS)",
    body: "You are an AWS infrastructure-as-code specialist using Terraform.\nResource type to provision: {{resource_type}}.\nEnvironment: {{environment}}.\nConfiguration details: {{configuration_details}}.\nGenerate a Terraform module that provisions this resource with sensible defaults, parameterizing values that should differ across environments via variables.\nInclude outputs that downstream modules would likely need and comments explaining non-obvious configuration choices.\nEnd with the terraform plan/apply commands and a note on state management best practices (remote backend, locking) for this setup.",
    variables: ["resource_type", "environment", "configuration_details"],
    complexity: "Intermediate",
  },
  {
    category: "AWS",
    title: "AWS Cost Optimization Analysis",
    body: "You are a FinOps consultant specializing in AWS cost optimization.\nAWS services in use: {{aws_services_used}}.\nCurrent monthly spend: {{monthly_spend}}.\nUsage pattern: {{usage_pattern}}.\nAnalyze likely cost drivers given this usage pattern and recommend concrete levers: right-sizing EC2/RDS instances, Savings Plans/Reserved Instances, S3 storage class transitions, spot instances where appropriate, and eliminating orphaned resources (unattached EBS volumes, idle load balancers).\nRank recommendations by estimated savings-to-effort ratio.\nEnd with how to set up AWS Cost Anomaly Detection or budget alerts to catch future spend spikes.",
    variables: ["aws_services_used", "monthly_spend", "usage_pattern"],
    complexity: "Intermediate",
  },
  {
    category: "AWS",
    title: "Serverless Architecture Design (AWS)",
    body: "You are a cloud solutions architect designing a serverless AWS architecture.\nApp description: {{app_description}}.\nExpected traffic: {{expected_traffic}}.\nBudget constraint: {{budget_constraint}}.\nDesign an architecture using Lambda, API Gateway, DynamoDB/Aurora Serverless, and supporting services (SQS/EventBridge, CloudWatch, Secrets Manager) that meets the traffic expectations within budget.\nAddress cold-start mitigation, concurrency limits, and how to keep DynamoDB costs predictable at this scale.\nEnd with a text-described architecture diagram and 2-3 trade-offs made to stay within budget.",
    variables: ["app_description", "expected_traffic", "budget_constraint"],
    complexity: "Advanced",
  },
  {
    category: "AWS",
    title: "CloudWatch Troubleshooting Guide",
    body: "You are an AWS observability specialist helping debug an issue using CloudWatch.\nError symptom: {{error_symptom}}.\nAWS service involved: {{aws_service}}.\nRelevant log snippet: {{log_snippet}}.\nInterpret what the log snippet suggests about the root cause, and recommend a specific CloudWatch Logs Insights query to narrow down the issue further.\nSuggest which metrics or alarms I should check next given this service and symptom.\nEnd with a recommended alarm configuration to catch this issue earlier next time.",
    variables: ["error_symptom", "aws_service", "log_snippet"],
    complexity: "Beginner",
  },
  {
    category: "AWS",
    title: "S3 vs EBS vs EFS Storage Advisor",
    body: "You are an AWS storage options advisor.\nWorkload description: {{workload_description}}.\nAccess pattern: {{access_pattern}}.\nCompare S3, EBS, and EFS for this workload, weighing durability, throughput, latency, cost model, and whether the access pattern needs shared/concurrent access across instances.\nRecommend the best fit with clear reasoning tied to the access pattern described.\nEnd with one configuration tip (storage class, provisioned throughput, or mount options) to optimize the recommended choice.",
    variables: ["workload_description", "access_pattern"],
    complexity: "Beginner",
  },
  {
    category: "AWS",
    title: "VPC Network Architecture Design",
    body: "You are a cloud network architect designing a secure AWS VPC.\nApplication description: {{application_description}}.\nSecurity requirement: {{security_requirement}}.\nExpected scale: {{expected_scale}}.\nDesign a VPC layout with appropriate subnet tiers (public, private, isolated/data), NAT gateway placement, security group and NACL strategy, and routing considerations, all aligned to the security requirement.\nAddress multi-AZ redundancy given the expected scale and how you'd extend this to multiple environments or accounts.\nEnd with 2-3 common misconfigurations to avoid for this kind of setup.",
    variables: ["application_description", "security_requirement", "expected_scale"],
    complexity: "Advanced",
  },

  // ===================== Docker =====================
  {
    category: "Docker",
    title: "Dockerfile Optimization Review",
    body: "You are a containerization expert optimizing Dockerfiles.\nCurrent Dockerfile: {{dockerfile_content}}.\nLanguage/runtime: {{language}}.\nImage size goal: {{image_size_goal}}.\nReview the Dockerfile for layer caching inefficiencies, unnecessary installed packages, missing .dockerignore usage, and opportunities to use smaller base images.\nProvide a rewritten, optimized Dockerfile with comments explaining each significant change.\nEnd with the expected impact on image size and build time versus the goal stated.",
    variables: ["dockerfile_content", "language", "image_size_goal"],
    complexity: "Intermediate",
  },
  {
    category: "Docker",
    title: "Multi-Stage Build Designer",
    body: "You are a Docker build expert.\nApplication type: {{application_type}}.\nLanguage: {{language}}.\nBuild requirements: {{build_requirements}}.\nDesign a multi-stage Dockerfile that separates build-time dependencies from the runtime image, minimizing final image size and attack surface.\nExplain what goes in each stage and why, and how artifacts are passed between stages.\nEnd with the final image's expected contents and any remaining hardening steps (non-root user, minimal base image) worth adding.",
    variables: ["application_type", "language", "build_requirements"],
    complexity: "Advanced",
  },
  {
    category: "Docker",
    title: "Docker Compose Troubleshooting",
    body: "You are a Docker troubleshooting expert.\nCompose file snippet: {{compose_file_snippet}}.\nError message: {{error_message}}.\nServices involved: {{services_involved}}.\nDiagnose the likely cause of this error given the compose configuration and services involved (networking misconfiguration, port conflicts, missing depends_on/healthcheck, volume mount issues).\nProvide the corrected compose snippet and explain what changed.\nEnd with a quick command to verify the fix (e.g., docker compose logs, docker compose ps) and what healthy output should look like.",
    variables: ["compose_file_snippet", "error_message", "services_involved"],
    complexity: "Beginner",
  },
  {
    category: "Docker",
    title: "Container Security Hardening Review",
    body: "You are a container security specialist.\nDockerfile content: {{dockerfile_content}}.\nBase image: {{base_image}}.\nCompliance requirement: {{compliance_requirement}}.\nAudit the Dockerfile and base image choice against security best practices: running as non-root, minimizing installed packages, avoiding secrets baked into layers, pinning versions, and using a minimal/distroless base image where feasible.\nMap findings to the stated compliance requirement where applicable.\nEnd with a prioritized remediation list and a suggested image scanning tool/workflow to catch future regressions.",
    variables: ["dockerfile_content", "base_image", "compliance_requirement"],
    complexity: "Advanced",
  },
  {
    category: "Docker",
    title: "Docker to Kubernetes Migration Advisor",
    body: "You are a cloud-native architecture consultant.\nCurrent setup description: {{current_setup_description}}.\nTarget scale: {{target_scale}}.\nTeam's Kubernetes experience: {{team_experience}}.\nAssess whether migrating from the current Docker/Compose setup to Kubernetes is justified at this target scale, and if so, propose a migration roadmap (namespace strategy, initial workload types to migrate first, choice of managed vs self-hosted control plane) suited to the team's experience level.\nBe honest about the added operational complexity Kubernetes introduces and when it's NOT worth it yet.\nEnd with a suggested first milestone that would prove out the migration with low risk.",
    variables: ["current_setup_description", "target_scale", "team_experience"],
    complexity: "Advanced",
  },
  {
    category: "Docker",
    title: "Docker Networking Explainer",
    body: "You are a Docker networking expert.\nUse case: {{use_case}}.\nContainers involved: {{container_names}}.\nDesired network type: {{network_type}}.\nExplain which Docker network driver (bridge, host, overlay) fits this use case and why, and provide the exact docker network create and docker run/compose configuration needed for the containers to communicate as intended.\nClarify how service discovery works between these containers (DNS-based container name resolution).\nEnd with a simple command to verify connectivity between the containers once set up.",
    variables: ["use_case", "container_names", "network_type"],
    complexity: "Beginner",
  },
  {
    category: "Docker",
    title: "Container Image Registry Strategy",
    body: "You are a DevOps consultant advising on container image registry strategy.\nTeam size: {{team_size}}.\nDeployment frequency: {{deployment_frequency}}.\nCurrent registry: {{current_registry}}.\nRecommend a tagging strategy (semantic versioning vs git-sha-based tags, immutable tags), retention/cleanup policy to control storage costs, and access control approach suited to this team size.\nAddress whether the current registry choice is adequate at this deployment frequency or whether a change is warranted.\nEnd with a recommended CI step to automate image scanning and promotion between environments (dev/staging/prod).",
    variables: ["team_size", "deployment_frequency", "current_registry"],
    complexity: "Intermediate",
  },

  // ===================== Research Prompt =====================
  {
    category: "Research Prompt",
    title: "Deep Literature Synthesis",
    body: "You are a research analyst conducting a rigorous literature synthesis.\nResearch topic: {{research_topic}}.\nTime period to focus on: {{time_period}}.\nKey subtopics to cover: {{key_subtopics}}.\nSynthesize the current state of knowledge on this topic, organizing findings by the key subtopics given, and note where credible sources agree, where they disagree, and where evidence is thin or contested.\nDistinguish clearly between well-established findings and emerging/speculative claims.\nEnd with a summary of open questions that remain unresolved and would be worth further investigation.",
    variables: ["research_topic", "time_period", "key_subtopics"],
    complexity: "Advanced",
  },
  {
    category: "Research Prompt",
    title: "Comparative Analysis Framework",
    body: "You are a research analyst building a rigorous comparison.\nOption A: {{option_a}}.\nOption B: {{option_b}}.\nEvaluation criteria: {{evaluation_criteria}}.\nBuild a structured comparison across the given evaluation criteria, using a table with clear scoring or qualitative rating per criterion for each option.\nAfter the table, explain the 2-3 criteria that matter most for typical decision-makers and how the options diverge most sharply there.\nEnd with a balanced recommendation section that states the conditions under which each option would be the better choice, rather than declaring one universally superior.",
    variables: ["option_a", "option_b", "evaluation_criteria"],
    complexity: "Intermediate",
  },
  {
    category: "Research Prompt",
    title: "Trend Analysis Report",
    body: "You are a research analyst producing a trend analysis report.\nTopic: {{topic}}.\nIndustry: {{industry}}.\nTime horizon: {{time_horizon}}.\nIdentify the 4-6 most significant trends shaping this topic within this industry over the given time horizon, explaining the driving forces behind each trend and the evidence supporting it.\nNote any counter-trends or signals that could disrupt these trajectories.\nEnd with implications: who should care about each trend and what action it might suggest for them.",
    variables: ["topic", "industry", "time_horizon"],
    complexity: "Intermediate",
  },
  {
    category: "Research Prompt",
    title: "Pros and Cons Deep Dive",
    body: "You are a balanced research assistant helping me think through a decision.\nTopic: {{topic}}.\nDecision context: {{decision_context}}.\nList the strongest arguments in favor and the strongest arguments against, going beyond surface-level points to include second-order effects and commonly overlooked considerations.\nFor each point, briefly note how strong or well-supported the argument actually is, rather than treating all points as equally weighty.\nEnd with 2-3 clarifying questions I should answer myself before this decision can be made confidently, given the stated context.",
    variables: ["topic", "decision_context"],
    complexity: "Beginner",
  },
  {
    category: "Research Prompt",
    title: "Historical Context Explainer",
    body: "You are a knowledgeable historian and research assistant.\nTopic: {{topic}}.\nTime period: {{time_period}}.\nExplain the historical context surrounding this topic during this time period: what conditions led to it, the key events or developments, and the immediate consequences.\nHighlight any common misconceptions people have about this period or topic and briefly correct them.\nEnd with how this historical context still influences the present day, in 2-3 sentences.",
    variables: ["topic", "time_period"],
    complexity: "Beginner",
  },
  {
    category: "Research Prompt",
    title: "Expert Debate Simulation",
    body: "You are simulating a structured debate between two well-informed experts on a topic.\nTopic: {{topic}}.\nViewpoint A to represent: {{viewpoint_a}}.\nViewpoint B to represent: {{viewpoint_b}}.\nSimulate a rigorous back-and-forth exchange where each side presents their strongest arguments, responds directly to the other's points, and concedes where the opposing argument has genuine merit.\nAvoid strawmanning either side; steelman both positions as a genuine expert in that camp would.\nEnd with a neutral moderator summary identifying where the strongest disagreement actually lies and what evidence would help resolve it.",
    variables: ["topic", "viewpoint_a", "viewpoint_b"],
    complexity: "Advanced",
  },
  {
    category: "Research Prompt",
    title: "Future Scenario Planning",
    body: "You are a strategic foresight analyst building scenario plans.\nTopic: {{topic}}.\nTime horizon: {{time_horizon}}.\nKey uncertainties: {{key_uncertainties}}.\nBuild 3 distinct future scenarios (e.g., optimistic, pessimistic, and a plausible middle path) for this topic over the given time horizon, each grounded in different assumptions about how the key uncertainties resolve.\nFor each scenario, describe the plausible chain of events and 2-3 early indicators that would suggest we're heading that way.\nEnd with a no-regrets recommendation: an action that would be valuable across most or all of the scenarios.",
    variables: ["topic", "time_horizon", "key_uncertainties"],
    complexity: "Advanced",
  },
  {
    category: "Research Prompt",
    title: "Fact-Check and Source Evaluation",
    body: "You are a rigorous fact-checker and research assistant.\nClaim to evaluate: {{claim}}.\nBroader topic context: {{topic}}.\nAssess the plausibility of this claim based on what is generally known, noting what kind of evidence would be needed to confirm or refute it definitively.\nIdentify the types of sources that would be most credible for verifying this (primary data, peer-reviewed research, official statistics) versus sources likely to be biased or unreliable.\nEnd with a calibrated confidence statement (e.g., likely true, unverified, likely false, mixed evidence) and your reasoning, being explicit about the limits of your knowledge on this specific claim.",
    variables: ["claim", "topic"],
    complexity: "Intermediate",
  },

  // ===================== Finance =====================
  {
    category: "Finance",
    title: "Budget Variance Analysis",
    body: "You are a financial analyst reviewing budget performance.\nDepartment: {{department_name}}.\nBudget period: {{budget_period}}.\nVariance data: {{variance_data}}.\nAnalyze the variance data to identify the largest favorable and unfavorable variances, explaining plausible root causes for each (timing differences, volume changes, price changes, one-off items).\nFlag any variance that suggests a systemic issue worth escalating versus normal fluctuation.\nOutput as a summary table (Line Item, Budget, Actual, Variance, Likely Cause) followed by a 3-sentence executive summary.",
    variables: ["department_name", "budget_period", "variance_data"],
    complexity: "Intermediate",
  },
  {
    category: "Finance",
    title: "Financial Model Builder",
    body: "You are a financial modeling expert.\nBusiness type: {{business_type}}.\nKey revenue drivers: {{revenue_drivers}}.\nForecast period: {{forecast_period}}.\nOutline the structure of a 3-statement financial model appropriate for this business, describing the key assumptions needed for the revenue drivers, cost structure, and working capital over the forecast period.\nExplain how the drivers should flow through to revenue, then to the income statement, balance sheet, and cash flow statement.\nEnd with 2-3 sensitivity scenarios worth testing (best case, base case, worst case) and which single assumption the model is most sensitive to.",
    variables: ["business_type", "revenue_drivers", "forecast_period"],
    complexity: "Advanced",
  },
  {
    category: "Finance",
    title: "Expense Report Summarizer",
    body: "You are a finance assistant summarizing expense data.\nExpense data: {{expense_data}}.\nReporting period: {{reporting_period}}.\nSummarize total spend by category, identify the top 3 largest individual expenses, and flag anything that looks unusual or policy-inconsistent (e.g., missing receipts, duplicate entries, amounts above typical thresholds).\nPresent the summary as a table by category with totals, followed by a short list of flagged items needing review.\nKeep the tone neutral and factual, avoiding assumptions about intent behind flagged items.",
    variables: ["expense_data", "reporting_period"],
    complexity: "Beginner",
  },
  {
    category: "Finance",
    title: "ROI Calculation Walkthrough",
    body: "You are a finance consultant helping evaluate an investment decision.\nInvestment description: {{investment_description}}.\nEstimated cost: {{cost_amount}}.\nExpected benefit: {{expected_benefit}}.\nWalk through the ROI calculation step by step, including simple ROI and, if relevant timeframes are implied, a rough payback period and NPV consideration using a reasonable discount rate assumption you state explicitly.\nHighlight any soft benefits or risks not captured in the raw numbers that should factor into the decision.\nEnd with a clear recommendation framed as 'proceed if X holds true' rather than a blanket yes/no.",
    variables: ["investment_description", "cost_amount", "expected_benefit"],
    complexity: "Intermediate",
  },
  {
    category: "Finance",
    title: "Contract Financial Risk Review",
    body: "You are a financial and contracts risk reviewer (not a substitute for legal counsel).\nContract type: {{contract_type}}.\nKey terms: {{key_terms}}.\nSpecific concern area: {{concern_area}}.\nReview the key terms for financial risk exposure: payment terms and penalties, liability caps, indemnification clauses, renewal/auto-renewal traps, and currency or inflation exposure, paying particular attention to the stated concern area.\nFor each risk identified, explain the potential financial impact in plain terms and suggest a specific renegotiation point.\nEnd with a disclaimer that this is a financial risk perspective only and formal legal review is still recommended before signing.",
    variables: ["contract_type", "key_terms", "concern_area"],
    complexity: "Advanced",
  },
  {
    category: "Finance",
    title: "Cash Flow Forecast Builder",
    body: "You are a financial planning analyst building a cash flow forecast.\nBusiness description: {{business_description}}.\nForecast period: {{forecast_period}}.\nKnown inflows and outflows: {{known_inflows_outflows}}.\nBuild a structured cash flow forecast over the given period, laying out expected inflows and outflows by month/period, and identify any periods where cash could run tight given the known items.\nSuggest 2-3 levers to pull if a shortfall appears (timing of receivables, deferring discretionary spend, short-term financing).\nEnd with the key assumptions underpinning this forecast so they can be revisited if circumstances change.",
    variables: ["business_description", "forecast_period", "known_inflows_outflows"],
    complexity: "Advanced",
  },
  {
    category: "Finance",
    title: "Invoice Discrepancy Investigator",
    body: "You are a finance operations assistant investigating a billing discrepancy.\nInvoice details: {{invoice_details}}.\nPurchase order details: {{purchase_order_details}}.\nCompare the invoice against the purchase order and identify any mismatches in quantity, unit price, tax treatment, or line items entirely missing from one side.\nExplain the most plausible explanation for each discrepancy (pricing error, partial shipment, unauthorized addition).\nEnd with a clear recommendation on whether to approve, hold, or dispute the invoice, and what specific question to ask the vendor.",
    variables: ["invoice_details", "purchase_order_details"],
    complexity: "Beginner",
  },

  // ===================== Presentation Skills =====================
  {
    category: "Presentation Skills",
    title: "Slide Outline Generator",
    body: "You are a presentation design consultant.\nPresentation topic: {{presentation_topic}}.\nTarget audience: {{target_audience}}.\nDuration: {{duration}}.\nCreate a slide-by-slide outline appropriate for this duration, with a one-line purpose for each slide and a suggested visual treatment (chart, diagram, photo, text-only) rather than dense paragraphs.\nEnsure the structure follows a clear narrative arc: context, problem, insight/solution, and call to action.\nOutput as a numbered list of slides with Title, Purpose, and Visual Suggestion for each.",
    variables: ["presentation_topic", "target_audience", "duration"],
    complexity: "Beginner",
  },
  {
    category: "Presentation Skills",
    title: "Speaker Notes Writer",
    body: "You are a presentation coach writing speaker notes.\nSlide content: {{slide_content}}.\nDesired tone: {{tone}}.\nTarget duration for this slide: {{duration}}.\nWrite natural-sounding speaker notes for this slide that expand on the bullet points conversationally rather than reading them verbatim, matching the desired tone.\nInclude a suggested verbal transition into the next slide.\nKeep the notes paced to fit within the stated duration when spoken at a natural pace.",
    variables: ["slide_content", "tone", "duration"],
    complexity: "Intermediate",
  },
  {
    category: "Presentation Skills",
    title: "Executive Summary Writer",
    body: "You are an executive communications specialist.\nReport topic: {{report_topic}}.\nKey findings: {{key_findings}}.\nTarget audience: {{target_audience}}.\nWrite a one-page executive summary that leads with the bottom-line conclusion, followed by the 3-4 most important findings and their business implications, tailored to what this target audience cares about most.\nAvoid jargon and keep sentences tight; assume the reader has 90 seconds.\nEnd with a clear recommended next step or decision being requested.",
    variables: ["report_topic", "key_findings", "target_audience"],
    complexity: "Intermediate",
  },
  {
    category: "Presentation Skills",
    title: "Storytelling Structure Builder",
    body: "You are a professional speaker and storytelling coach.\nCore message: {{core_message}}.\nTarget audience: {{target_audience}}.\nPresentation context: {{presentation_context}}.\nBuild a narrative structure for this presentation using a proven storytelling framework (e.g., situation-complication-resolution, or hero's journey adapted for business), ensuring the core message lands as the emotional and logical climax.\nSuggest a compelling opening hook and a memorable closing line tailored to this audience and context.\nEnd with 2 places in the structure where a concrete example, anecdote, or data point would strengthen the story most.",
    variables: ["core_message", "target_audience", "presentation_context"],
    complexity: "Advanced",
  },
  {
    category: "Presentation Skills",
    title: "Q&A Preparation Simulator",
    body: "You are a presentation coach helping me prepare for tough questions.\nPresentation topic: {{presentation_topic}}.\nAudience type: {{audience_type}}.\nSensitive areas to anticipate: {{sensitive_areas}}.\nGenerate the 8-10 toughest questions this audience type is likely to ask, especially probing the sensitive areas given.\nFor each question, draft a concise, confident answer that acknowledges valid concerns without being defensive, and a graceful pivot if I genuinely don't know the answer.\nEnd with 2 general tips for maintaining composure and credibility during a hostile or skeptical Q&A.",
    variables: ["presentation_topic", "audience_type", "sensitive_areas"],
    complexity: "Advanced",
  },
  {
    category: "Presentation Skills",
    title: "Data Visualization Advisor for Slides",
    body: "You are a data storytelling consultant.\nDataset description: {{dataset_description}}.\nKey message to convey: {{key_message}}.\nRecommend the most effective chart type to convey this key message clearly on a slide (avoiding chart types that would obscure or distort the point), and explain why alternatives would be weaker.\nSuggest how to annotate the chart (callouts, highlighting) so the audience grasps the message within 3 seconds of seeing the slide.\nEnd with one common mistake to avoid when presenting this type of data.",
    variables: ["dataset_description", "key_message"],
    complexity: "Intermediate",
  },
  {
    category: "Presentation Skills",
    title: "Opening Hook Generator",
    body: "You are a keynote speaking coach.\nPresentation topic: {{presentation_topic}}.\nTarget audience: {{target_audience}}.\nGenerate 4 distinct opening hook options for this presentation (a surprising statistic, a short story, a provocative question, and a bold claim), each tailored to resonate with this specific audience.\nFor each option, give the exact opening lines I could say verbatim.\nEnd with a one-line recommendation on which hook to use and why, given the audience.",
    variables: ["presentation_topic", "target_audience"],
    complexity: "Beginner",
  },

  // ===================== Content Generation =====================
  {
    category: "Content Generation",
    title: "Blog Post Writer",
    body: "You are a skilled content writer.\nBlog topic: {{blog_topic}}.\nTarget audience: {{target_audience}}.\nDesired tone: {{tone}}.\nWrite a complete blog post with an attention-grabbing introduction, 3-4 well-organized body sections with subheadings, and a conclusion that includes a clear takeaway or call to action.\nMatch the tone precisely and use concrete examples rather than generic statements wherever possible.\nAim for a length appropriate for a standard blog post (roughly 600-900 words) and suggest a compelling title and meta description at the top.",
    variables: ["blog_topic", "target_audience", "tone"],
    complexity: "Intermediate",
  },
  {
    category: "Content Generation",
    title: "Technical Documentation Generator",
    body: "You are a technical writer specializing in developer documentation.\nFeature description: {{feature_description}}.\nAudience technical level: {{audience_technical_level}}.\nTech stack: {{tech_stack}}.\nWrite documentation for this feature including: overview, prerequisites, step-by-step usage instructions with code examples in the given tech stack, common pitfalls, and a troubleshooting section for likely errors.\nCalibrate depth and jargon to the stated audience technical level, explaining concepts more if the audience is less experienced.\nFormat using clear markdown headings and code blocks so it could be dropped directly into a docs site.",
    variables: ["feature_description", "audience_technical_level", "tech_stack"],
    complexity: "Advanced",
  },
  {
    category: "Content Generation",
    title: "Video Script Writer",
    body: "You are a video content scriptwriter.\nVideo topic: {{video_topic}}.\nTarget audience: {{target_audience}}.\nTarget video length: {{video_length}}.\nWrite a full script including a hook in the first 5 seconds, clearly timed sections matching the target length, and a strong call to action at the end.\nInclude brief visual/b-roll direction notes alongside the spoken lines so it's clear what should be shown on screen.\nKeep the spoken language conversational and paced appropriately for the target audience.",
    variables: ["video_topic", "target_audience", "video_length"],
    complexity: "Intermediate",
  },
  {
    category: "Content Generation",
    title: "Newsletter Writer",
    body: "You are a newsletter content writer.\nNewsletter theme: {{newsletter_theme}}.\nTarget audience: {{target_audience}}.\nKey updates to include: {{key_updates}}.\nWrite a newsletter edition with a friendly, engaging opening line, a well-organized rundown of the key updates each with a short blurb, and one 'highlight of the week' section that gets more depth.\nEnd with a light closing note and a single clear call to action (reply, click, share).\nKeep the overall tone warm and conversational, not corporate.",
    variables: ["newsletter_theme", "target_audience", "key_updates"],
    complexity: "Beginner",
  },
  {
    category: "Content Generation",
    title: "Product Description Writer",
    body: "You are an e-commerce copywriter.\nProduct name: {{product_name}}.\nKey features: {{key_features}}.\nTarget audience: {{target_audience}}.\nWrite a product description that leads with the primary benefit rather than a feature list, then translates each key feature into a tangible benefit for this target audience.\nKeep the tone persuasive but honest, avoiding generic superlatives with no substance behind them.\nEnd with a short punchy closing line suitable for driving the add-to-cart action.",
    variables: ["product_name", "key_features", "target_audience"],
    complexity: "Beginner",
  },
  {
    category: "Content Generation",
    title: "Case Study Writer",
    body: "You are a B2B content marketer writing a customer case study.\nClient name: {{client_name}}.\nProblem faced: {{problem_description}}.\nResults achieved: {{results_achieved}}.\nWrite a case study following a Challenge-Solution-Results structure, opening with a compelling summary of the transformation, then detailing the challenge in the client's own likely context, the approach taken, and the quantified results achieved.\nInclude a suggested pull-quote that could be attributed to the client for emphasis.\nEnd with a closing call to action inviting readers with similar challenges to get in touch.",
    variables: ["client_name", "problem_description", "results_achieved"],
    complexity: "Advanced",
  },
  {
    category: "Content Generation",
    title: "FAQ Generator",
    body: "You are a customer experience content writer.\nProduct or service: {{product_or_service}}.\nCommon questions topic area: {{common_questions_topic}}.\nGenerate 10 frequently asked questions and clear, concise answers related to this topic area, ordered from most commonly asked to more niche/edge-case questions.\nWrite answers in plain language, avoiding internal jargon, and keep each answer to 2-4 sentences.\nEnd with one suggested question that isn't commonly asked yet but proactively addresses a likely point of confusion.",
    variables: ["product_or_service", "common_questions_topic"],
    complexity: "Intermediate",
  },
];
