import type { SeedPrompt } from "./prompt-data";

export const seedPromptsBatchB: SeedPrompt[] = [
  // ===================== Full Stack Developers =====================
  {
    category: "Full Stack Developers",
    title: "API Reference Documentation Generator",
    body: "You are a technical writer and senior full-stack engineer helping me produce clear API reference documentation.\nHere is the API surface or code to document: {{api_code_or_spec}}.\nThe target audience is: {{target_audience}}.\nGenerate reference documentation covering endpoint/method signatures, parameters with types and constraints, example requests and responses, and common error codes with explanations.\nWrite in a concise, consistent style suitable for {{documentation_format}} and flag any ambiguous behavior in the code that should be clarified with the original author.\nOutput as structured markdown with one section per endpoint/method, followed by a short 'Getting Started' example.",
    variables: ["api_code_or_spec", "target_audience", "documentation_format"],
    complexity: "Intermediate",
  },
  {
    category: "Full Stack Developers",
    title: "README & Setup Guide Writer",
    body: "You are a senior full-stack developer writing a README that gets new contributors productive fast.\nProject description: {{project_description}}.\nTech stack: {{tech_stack}}.\nKnown setup gotchas: {{setup_gotchas}}.\nDraft a README with sections for Overview, Prerequisites, Installation, Local Development, Running Tests, and Troubleshooting, weaving in the setup gotchas where relevant so new developers don't get stuck.\nKeep instructions copy-pasteable as shell commands where applicable and avoid assuming prior project knowledge.\nOutput the full README in markdown, ready to commit as README.md.",
    variables: ["project_description", "tech_stack", "setup_gotchas"],
    complexity: "Beginner",
  },
  {
    category: "Full Stack Developers",
    title: "Onboarding Runbook for New Engineers",
    body: "You are an engineering lead creating an onboarding runbook for new full-stack engineers.\nTeam/product: {{team_or_product}}.\nCodebase entry points: {{codebase_entry_points}}.\nFirst 30-day goals for a new hire: {{thirty_day_goals}}.\nWrite a runbook covering environment setup, key repositories and where to find things, who to contact for what (roles, not names), a suggested first-week task list, and common pitfalls new engineers hit in this codebase.\nStructure it so a new hire can follow it top to bottom without needing to ask for help on basics.\nOutput as a markdown runbook with numbered phases: Day 1, Week 1, Weeks 2-4.",
    variables: ["team_or_product", "codebase_entry_points", "thirty_day_goals"],
    complexity: "Intermediate",
  },
  {
    category: "Full Stack Developers",
    title: "Static Analysis Findings Triage",
    body: "You are a principal engineer helping me triage a batch of static analysis findings.\nHere is the raw output from the tool ({{tool_name}}): {{findings_output}}.\nOur risk tolerance and release timeline: {{release_context}}.\nGroup the findings by severity and real-world exploitability or bug risk, discarding likely false positives with a brief justification.\nFor each retained finding, explain the underlying issue in plain language and suggest a minimal fix.\nOutput as a table with columns: Finding, Severity, Real Risk?, Recommended Fix, Fix Now or Defer.",
    variables: ["tool_name", "findings_output", "release_context"],
    complexity: "Advanced",
  },
  {
    category: "Full Stack Developers",
    title: "Code Smell Detection Pass",
    body: "You are a meticulous senior engineer doing a code smell pass on a pull request or module.\nHere is the code: {{code_snippet}}.\nContext on how this code is used: {{usage_context}}.\nIdentify code smells such as long methods, duplicated logic, inappropriate coupling, primitive obsession, and unclear naming.\nFor each smell, quote the offending section, name the smell, and propose a concrete refactor with a short before/after illustration.\nEnd with a prioritized list of which smells to fix before merge versus which can be tracked as follow-up tech debt.",
    variables: ["code_snippet", "usage_context"],
    complexity: "Intermediate",
  },
  {
    category: "Full Stack Developers",
    title: "Technical Debt Reduction Roadmap",
    body: "You are a staff engineer building a technical debt reduction roadmap.\nCurrent pain points reported by the team: {{pain_points}}.\nCodebase size/age context: {{codebase_context}}.\nAvailable engineering capacity per sprint: {{available_capacity}}.\nProduce a prioritized roadmap that scores each debt item by risk-if-ignored and effort-to-fix, sequences the work across the available capacity, and explains the expected payoff (velocity, reliability, onboarding speed) for tackling each item.\nInclude a suggested way to communicate this roadmap to non-engineering stakeholders.\nOutput as a phased plan (Phase 1, Phase 2, Phase 3) with a short table of Item, Risk, Effort, Payoff per phase.",
    variables: ["pain_points", "codebase_context", "available_capacity"],
    complexity: "Advanced",
  },
  {
    category: "Full Stack Developers",
    title: "Frontend Framework Comparison & Recommendation",
    body: "You are a pragmatic full-stack architect researching frontend framework options.\nProject requirements: {{project_requirements}}.\nCandidate frameworks under consideration: {{candidate_frameworks}}.\nTeam's existing experience: {{team_experience}}.\nCompare the candidates on learning curve, ecosystem maturity, performance characteristics, SSR/SEO support, and long-term maintainability given the team's experience.\nRecommend one option with explicit trade-offs you're accepting, and note the conditions under which you'd reconsider the recommendation.\nOutput as a comparison table followed by a 'Recommendation & Rationale' section.",
    variables: ["project_requirements", "candidate_frameworks", "team_experience"],
    complexity: "Advanced",
  },
  {
    category: "Full Stack Developers",
    title: "Backend Architecture Options Comparison",
    body: "You are a solutions architect comparing backend architecture options for a new or evolving system.\nSystem requirements and expected scale: {{system_requirements}}.\nOptions to evaluate: {{architecture_options}} (for example monolith, modular monolith, microservices).\nOrganizational constraints (team size, deployment maturity): {{org_constraints}}.\nResearch and compare the options on operational complexity, development velocity, scalability, and failure isolation, grounding each point in how it plays out given the stated constraints.\nRecommend the best-fit architecture and lay out a rough migration or adoption plan if it differs from the current state.\nOutput as: Comparison Table, Recommendation, Migration Plan (if applicable).",
    variables: ["system_requirements", "architecture_options", "org_constraints"],
    complexity: "Advanced",
  },
  {
    category: "Full Stack Developers",
    title: "Feature Flag Rollout Plan",
    body: "You are a full-stack engineer planning a safe feature flag rollout.\nFeature being released: {{feature_description}}.\nRisk level: {{risk_level}}.\nTarget rollout timeline: {{rollout_timeline}}.\nDesign a rollout plan with flag stages (internal, beta cohort, percentage ramp, full release), the metrics to monitor at each stage, and clear rollback criteria.\nInclude how to clean up the flag once it's fully rolled out so it doesn't become permanent tech debt.\nOutput as a staged plan with a table: Stage, Audience %, Success Metric, Rollback Trigger.",
    variables: ["feature_description", "risk_level", "rollout_timeline"],
    complexity: "Intermediate",
  },
  {
    category: "Full Stack Developers",
    title: "Third-Party API Integration Plan",
    body: "You are a full-stack engineer planning an integration with an external API.\nThird-party API: {{third_party_api}}.\nWhat we need it to do: {{integration_purpose}}.\nOur reliability requirements: {{reliability_requirements}}.\nPlan the integration covering authentication approach, rate limit handling, retry/backoff strategy, error mapping to our own domain errors, and a fallback behavior if the third party is down.\nFlag any data we should cache locally to reduce dependency on the third party's uptime.\nOutput as an integration design doc with sections: Auth, Resilience Strategy, Data Flow, Failure Modes.",
    variables: ["third_party_api", "integration_purpose", "reliability_requirements"],
    complexity: "Intermediate",
  },
  {
    category: "Full Stack Developers",
    title: "Error Handling & Logging Strategy",
    body: "You are a senior full-stack engineer designing a consistent error handling and logging strategy.\nStack: {{tech_stack}}.\nCurrent pain points with errors/logs: {{current_pain_points}}.\nDesign a strategy covering error classification (expected vs unexpected), a consistent error response shape for APIs, structured logging fields to always include, and log levels to use in each scenario.\nInclude guidance on what should trigger an alert versus what's just informational.\nOutput as a strategy doc with sections: Error Taxonomy, API Error Shape, Logging Standards, Alerting Rules.",
    variables: ["tech_stack", "current_pain_points"],
    complexity: "Intermediate",
  },
  {
    category: "Full Stack Developers",
    title: "Caching Strategy Designer",
    body: "You are a backend-focused full-stack engineer designing a caching strategy.\nWhat we're trying to speed up: {{slow_operation}}.\nCurrent data access pattern: {{access_pattern}}.\nConsistency requirements: {{consistency_requirements}}.\nRecommend a caching layer (in-memory, distributed, CDN, etc.) appropriate to this pattern, define the cache key strategy, TTL approach, and invalidation strategy that respects the consistency requirements.\nCall out the failure mode if the cache goes down or serves stale data, and how to detect it.\nOutput as: Recommended Approach, Key & TTL Design, Invalidation Strategy, Failure Handling.",
    variables: ["slow_operation", "access_pattern", "consistency_requirements"],
    complexity: "Advanced",
  },
  {
    category: "Full Stack Developers",
    title: "Authentication/Authorization Flow Designer",
    body: "You are a full-stack security-minded engineer designing an auth flow.\nApplication type: {{application_type}}.\nUser roles/permission model needed: {{permission_model}}.\nExisting identity provider or constraints: {{identity_constraints}}.\nDesign the authentication and authorization flow, specifying token type and lifecycle, session handling, and how role/permission checks should be enforced at both API and UI layers.\nCall out common pitfalls (token leakage, privilege escalation, insecure direct object references) and how this design avoids them.\nOutput as a flow description with a numbered sequence of steps and a short 'Security Considerations' list.",
    variables: ["application_type", "permission_model", "identity_constraints"],
    complexity: "Advanced",
  },
  {
    category: "Full Stack Developers",
    title: "CI/CD Pipeline Blueprint",
    body: "You are a full-stack engineer designing a CI/CD pipeline.\nStack and deployment target: {{stack_and_target}}.\nCurrent pain points in the release process: {{release_pain_points}}.\nDesign a pipeline with stages for lint/test, build, security scan, staging deploy, and production deploy, specifying what gates each stage and what triggers a rollback.\nRecommend how to keep pipeline run time reasonable without sacrificing safety.\nOutput as a stage-by-stage table: Stage, Trigger, Checks Performed, Failure Action.",
    variables: ["stack_and_target", "release_pain_points"],
    complexity: "Intermediate",
  },
  {
    category: "Full Stack Developers",
    title: "Dependency Upgrade Impact Assessment",
    body: "You are a senior engineer assessing the impact of a dependency upgrade before doing it.\nDependency and version change: {{dependency_change}}.\nHow it's used in our codebase: {{usage_context}}.\nOur test coverage in affected areas: {{test_coverage_notes}}.\nAssess breaking changes likely to affect us, areas of the codebase most at risk, and a safe upgrade sequence (e.g., isolate, upgrade, test, expand).\nRecommend what additional test coverage to add before upgrading given the current coverage gaps.\nOutput as: Risk Summary, Affected Areas, Step-by-Step Upgrade Plan, Pre-Upgrade Test Additions.",
    variables: ["dependency_change", "usage_context", "test_coverage_notes"],
    complexity: "Intermediate",
  },
  {
    category: "Full Stack Developers",
    title: "Scalability Readiness Checklist",
    body: "You are a full-stack architect assessing whether a system is ready to handle increased scale.\nSystem description: {{system_description}}.\nExpected growth: {{expected_growth}}.\nCurrent known bottlenecks: {{known_bottlenecks}}.\nProduce a scalability readiness checklist covering database load, caching, horizontal scaling of services, background job processing, and monitoring/alerting coverage.\nFor each area, mark it as likely ready, at risk, or needs work given the expected growth, with a one-line justification.\nOutput as a checklist table: Area, Status, Justification, Recommended Action.",
    variables: ["system_description", "expected_growth", "known_bottlenecks"],
    complexity: "Advanced",
  },
  {
    category: "Full Stack Developers",
    title: "Cross-Team API Contract Proposal",
    body: "You are a full-stack engineer proposing an API contract to be consumed by another team.\nWhat the API needs to support: {{api_purpose}}.\nConsuming team's stated needs: {{consumer_needs}}.\nPropose a versioned API contract including resource shapes, key endpoints, pagination and filtering conventions, and error response format, explaining trade-offs where you deviated from the consuming team's literal request in favor of consistency or long-term maintainability.\nInclude a short migration note if this replaces an existing contract.\nOutput as a proposal doc: Contract Summary, Endpoints & Shapes, Open Questions for the Consuming Team.",
    variables: ["api_purpose", "consumer_needs"],
    complexity: "Intermediate",
  },

  // ===================== Mobile App Development =====================
  {
    category: "Mobile App Development",
    title: "App Architecture Documentation Writer",
    body: "You are a senior mobile engineer documenting an app's architecture for the team.\nApp platform(s): {{platform}}.\nHigh-level architecture pattern used: {{architecture_pattern}}.\nKey modules/layers: {{key_modules}}.\nWrite architecture documentation covering the overall layering (UI, domain, data), how navigation and state flow between layers, dependency injection approach, and where a new engineer should look first to add a feature.\nInclude a short diagram description in words since this will be turned into a visual later.\nOutput as markdown documentation with sections: Overview, Layers, Data Flow, Where to Add X.",
    variables: ["platform", "architecture_pattern", "key_modules"],
    complexity: "Intermediate",
  },
  {
    category: "Mobile App Development",
    title: "Release Notes Generator",
    body: "You are a mobile release manager writing user-facing release notes.\nApp name: {{app_name}}.\nRaw changelog or commit summary for this release: {{raw_changes}}.\nTarget audience: {{audience}}.\nTransform the raw technical changes into concise, benefit-focused release notes appropriate for an app store listing, grouping items into New, Improved, and Fixed.\nOmit purely internal changes that don't affect users, and keep language plain and upbeat without overselling minor fixes.\nOutput as: a short intro line, then bulleted New/Improved/Fixed sections.",
    variables: ["app_name", "raw_changes", "audience"],
    complexity: "Beginner",
  },
  {
    category: "Mobile App Development",
    title: "SDK Integration Guide Writer",
    body: "You are a mobile developer relations engineer writing an SDK integration guide.\nSDK/library name and purpose: {{sdk_name}}.\nTarget platform(s): {{target_platforms}}.\nCommon integration pitfalls you've seen: {{known_pitfalls}}.\nWrite a step-by-step integration guide covering installation, initialization, minimal working example, and how to verify the integration succeeded, proactively addressing the known pitfalls inline rather than in a separate FAQ.\nKeep code samples realistic and idiomatic for the target platform(s).\nOutput as a markdown guide with numbered steps and a 'Troubleshooting' section at the end.",
    variables: ["sdk_name", "target_platforms", "known_pitfalls"],
    complexity: "Intermediate",
  },
  {
    category: "Mobile App Development",
    title: "Mobile Code Review Depth Checklist",
    body: "You are a principal mobile engineer reviewing a pull request with a focus on depth, not just style.\nHere is the code/diff: {{code_diff}}.\nPlatform and framework: {{platform_framework}}.\nReview for lifecycle/memory issues, main-thread blocking work, improper state handling, and platform-specific anti-patterns, not just formatting.\nFor each issue, quote the relevant lines, explain the real-world impact (crash, jank, battery drain, memory leak), and suggest a fix.\nEnd with a merge recommendation (approve, approve with comments, request changes) and reasoning.",
    variables: ["code_diff", "platform_framework"],
    complexity: "Advanced",
  },
  {
    category: "Mobile App Development",
    title: "Technical Debt Audit for Mobile Codebase",
    body: "You are a staff mobile engineer auditing technical debt in an app codebase.\nApp description and age: {{app_description}}.\nAreas developers complain about most: {{pain_points}}.\nCurrent team size: {{team_size}}.\nAudit the codebase conceptually for signs of debt such as outdated architecture patterns, tangled navigation, oversized view controllers/activities/widgets, and inconsistent state management, using the reported pain points as your starting clues.\nPrioritize the debt items by user-facing risk versus developer friction, and propose a realistic paydown plan given the team size.\nOutput as: Debt Inventory (table), Prioritization Rationale, Suggested Paydown Plan.",
    variables: ["app_description", "pain_points", "team_size"],
    complexity: "Advanced",
  },
  {
    category: "Mobile App Development",
    title: "Refactoring Plan for Legacy Mobile Screen",
    body: "You are a senior mobile engineer planning a safe refactor of a legacy screen.\nScreen/feature description: {{screen_description}}.\nCurrent known issues: {{current_issues}}.\nConstraints (must not break, deadline, etc.): {{constraints}}.\nPropose a step-by-step refactoring plan that keeps the screen functional throughout (no big-bang rewrite), including how to add test coverage before refactoring if there is none today.\nCall out the riskiest step and how to mitigate it (e.g., feature flag, gradual rollout).\nOutput as a sequenced plan: Step, What Changes, Risk, Mitigation.",
    variables: ["screen_description", "current_issues", "constraints"],
    complexity: "Advanced",
  },
  {
    category: "Mobile App Development",
    title: "Cross-Platform vs Native Development Comparison",
    body: "You are a mobile technical lead researching cross-platform versus native development for a new project.\nProject requirements: {{project_requirements}}.\nTeam's current skill set: {{team_skills}}.\nPerformance/UX bar required: {{performance_requirements}}.\nCompare native (Swift/Kotlin) against leading cross-platform options on development speed, performance ceiling, access to platform APIs, and long-term maintenance cost given the team's skills.\nRecommend one approach with clear justification and note the specific conditions that would flip the recommendation.\nOutput as a comparison table followed by 'Recommendation & Trade-offs'.",
    variables: ["project_requirements", "team_skills", "performance_requirements"],
    complexity: "Advanced",
  },
  {
    category: "Mobile App Development",
    title: "State Management Approach Comparison",
    body: "You are a mobile architect comparing state management approaches for an app.\nApp complexity and data flow needs: {{app_complexity}}.\nCandidate approaches/libraries: {{candidate_approaches}}.\nTeam familiarity: {{team_familiarity}}.\nResearch and compare the candidates on boilerplate, testability, learning curve, and how well each scales as screens and shared state grow, grounded in the stated app complexity.\nRecommend one option and describe a lightweight migration path if the app currently uses something else.\nOutput as: Comparison Table, Recommendation, Migration Notes.",
    variables: ["app_complexity", "candidate_approaches", "team_familiarity"],
    complexity: "Advanced",
  },
  {
    category: "Mobile App Development",
    title: "Deep Linking Strategy Designer",
    body: "You are a mobile engineer designing a deep linking strategy.\nApp features that need deep links: {{features_needing_links}}.\nPlatforms targeted: {{target_platforms}}.\nMarketing/attribution requirements: {{attribution_requirements}}.\nDesign a deep linking scheme (URL structure, universal/app links vs custom scheme) that handles cold-start and warm-start navigation correctly, and satisfies the attribution requirements.\nCall out edge cases like the app not being installed and how to gracefully fall back.\nOutput as: Link Structure, Routing Logic, Fallback Behavior, Edge Cases.",
    variables: ["features_needing_links", "target_platforms", "attribution_requirements"],
    complexity: "Intermediate",
  },
  {
    category: "Mobile App Development",
    title: "App Permissions & Privacy Flow Designer",
    body: "You are a mobile engineer designing how an app requests permissions and communicates privacy.\nPermissions needed and why: {{permissions_needed}}.\nPlatform(s): {{target_platforms}}.\nRegulatory considerations: {{regulatory_considerations}}.\nDesign the permission request flow, including pre-permission priming screens that explain value before the system prompt, graceful degradation if a permission is denied, and copy that satisfies the stated regulatory considerations.\nFlag any permission requests that look excessive relative to the stated purpose.\nOutput as: Flow Steps, Priming Copy, Denied-State Behavior, Compliance Notes.",
    variables: ["permissions_needed", "target_platforms", "regulatory_considerations"],
    complexity: "Intermediate",
  },
  {
    category: "Mobile App Development",
    title: "Mobile CI/CD Pipeline Setup Plan",
    body: "You are a mobile DevOps-minded engineer setting up a CI/CD pipeline for an app.\nPlatform(s) and build tooling: {{platform_and_tooling}}.\nCurrent release cadence: {{release_cadence}}.\nPain points in the current process: {{pain_points}}.\nDesign a pipeline covering automated build, test, code signing, beta distribution (e.g., TestFlight/Play internal track), and store submission, addressing the stated pain points explicitly.\nRecommend how to keep build times reasonable and where to add manual gates versus full automation.\nOutput as a stage table: Stage, Tooling, Trigger, Manual Gate?",
    variables: ["platform_and_tooling", "release_cadence", "pain_points"],
    complexity: "Intermediate",
  },
  {
    category: "Mobile App Development",
    title: "Crash Reporting & Monitoring Strategy",
    body: "You are a mobile reliability engineer designing a crash reporting and monitoring strategy.\nApp and current monitoring gaps: {{monitoring_gaps}}.\nTools already in use, if any: {{existing_tools}}.\nTeam's on-call setup: {{oncall_setup}}.\nRecommend what to instrument (crashes, ANRs/hangs, non-fatal errors, key funnels), how to set meaningful alert thresholds, and how findings should route to the right owner given the on-call setup.\nInclude guidance on triaging a new crash spike within the first hour of a release.\nOutput as: Instrumentation Plan, Alerting Thresholds, Triage Runbook.",
    variables: ["monitoring_gaps", "existing_tools", "oncall_setup"],
    complexity: "Advanced",
  },
  {
    category: "Mobile App Development",
    title: "App Localization Plan",
    body: "You are a mobile engineer planning app localization.\nApp description: {{app_description}}.\nTarget locales: {{target_locales}}.\nCurrent state of string externalization: {{current_string_state}}.\nPlan the localization effort covering string extraction approach, handling of pluralization/RTL layouts/date-number formats, translation workflow, and how to avoid regressions like truncated UI text.\nGiven the current state of string externalization, sequence the work realistically.\nOutput as a phased plan: Phase, Tasks, Risk to Watch.",
    variables: ["app_description", "target_locales", "current_string_state"],
    complexity: "Intermediate",
  },
  {
    category: "Mobile App Development",
    title: "Battery & Memory Usage Optimization Plan",
    body: "You are a mobile performance engineer planning battery and memory optimizations.\nSymptom reported: {{performance_symptom}}.\nSuspected culprit areas: {{suspected_areas}}.\nPlatform: {{platform}}.\nPropose a diagnostic plan (profiling tools and what to look for) to confirm the suspected culprits, then likely fixes for common causes such as background work, wakelocks, retained references, or inefficient rendering.\nRank the fixes by expected impact versus implementation effort.\nOutput as: Diagnostic Steps, Likely Root Causes, Ranked Fix List.",
    variables: ["performance_symptom", "suspected_areas", "platform"],
    complexity: "Advanced",
  },
  {
    category: "Mobile App Development",
    title: "Biometric Authentication Integration Guide",
    body: "You are a mobile security-focused engineer integrating biometric authentication.\nPlatform(s): {{target_platforms}}.\nWhat biometrics will gate (e.g., app unlock, payment): {{gated_action}}.\nFallback requirements: {{fallback_requirements}}.\nWrite an integration guide covering the platform biometric APIs to use, secure storage of any resulting tokens/keys, and the required fallback flow (PIN/password) per the stated requirements.\nCall out common mistakes like storing sensitive data insecurely or skipping the fallback path.\nOutput as a numbered integration guide with a 'Security Notes' closing section.",
    variables: ["target_platforms", "gated_action", "fallback_requirements"],
    complexity: "Intermediate",
  },
  {
    category: "Mobile App Development",
    title: "In-App Purchase / Subscription Flow Design",
    body: "You are a mobile engineer designing an in-app purchase or subscription flow.\nProduct/subscription tiers: {{product_tiers}}.\nPlatform(s): {{target_platforms}}.\nEdge cases to handle (e.g., restore purchases, upgrade/downgrade): {{edge_cases}}.\nDesign the purchase flow including the paywall trigger points, receipt validation approach (client vs server), and handling for the stated edge cases so users don't lose access or get double-charged.\nNote platform-specific store review requirements to keep in mind.\nOutput as: Flow Diagram (described in steps), Validation Approach, Edge Case Handling Table.",
    variables: ["product_tiers", "target_platforms", "edge_cases"],
    complexity: "Advanced",
  },
  {
    category: "Mobile App Development",
    title: "Accessibility Audit for Mobile App",
    body: "You are a mobile accessibility specialist auditing an app or screen.\nScreen(s)/flow to audit: {{screen_or_flow}}.\nPlatform: {{platform}}.\nKnown user complaints, if any: {{known_complaints}}.\nAudit for screen reader support (labels, focus order), touch target sizing, color contrast, and dynamic text scaling support, referencing platform accessibility guidelines.\nFor each issue found, rate severity and give a concrete fix.\nOutput as a table: Issue, Severity, Guideline Violated, Recommended Fix.",
    variables: ["screen_or_flow", "platform", "known_complaints"],
    complexity: "Intermediate",
  },
  {
    category: "Mobile App Development",
    title: "Mobile App Security Checklist",
    body: "You are a mobile security engineer building a pre-release security checklist.\nApp description and sensitive data handled: {{sensitive_data_handled}}.\nPlatform(s): {{target_platforms}}.\nKnown compliance requirements: {{compliance_requirements}}.\nProduce a checklist covering secure storage of secrets/tokens, network transport security, certificate pinning considerations, root/jailbreak detection, and obfuscation, tailored to the sensitive data and compliance requirements stated.\nMark each item as must-fix before release versus nice-to-have.\nOutput as a checklist table: Item, Why It Matters, Priority.",
    variables: ["sensitive_data_handled", "target_platforms", "compliance_requirements"],
    complexity: "Advanced",
  },

  // ===================== Github Commands =====================
  {
    category: "Github Commands",
    title: "CONTRIBUTING.md Writer",
    body: "You are an open-source maintainer writing a CONTRIBUTING.md.\nProject name and purpose: {{project_description}}.\nContribution workflow you want enforced (branching, PR process): {{contribution_workflow}}.\nCoding/testing standards: {{coding_standards}}.\nWrite a CONTRIBUTING.md covering how to set up a dev environment, the branching and PR workflow, coding standards, how to report bugs versus propose features, and what reviewers will check before merging.\nKeep the tone welcoming to first-time contributors while being explicit about non-negotiables.\nOutput the full CONTRIBUTING.md in markdown.",
    variables: ["project_description", "contribution_workflow", "coding_standards"],
    complexity: "Beginner",
  },
  {
    category: "Github Commands",
    title: "Git Workflow Documentation for Team",
    body: "You are an engineering lead documenting the team's git workflow so everyone follows it consistently.\nBranching model in use: {{branching_model}}.\nRelease cadence: {{release_cadence}}.\nCommon mistakes the team currently makes: {{common_mistakes}}.\nDocument the workflow covering branch naming conventions, when to branch and from where, PR and review expectations, and how releases/tags are cut, explicitly addressing the common mistakes so the doc prevents them.\nInclude a short 'do this, not that' comparison for the trickiest part of the workflow.\nOutput as a markdown team doc with clear headings and at least one example command sequence.",
    variables: ["branching_model", "release_cadence", "common_mistakes"],
    complexity: "Intermediate",
  },
  {
    category: "Github Commands",
    title: "Changelog Generator From Commits",
    body: "You are a release engineer generating a changelog from raw commit history.\nRaw commit log: {{commit_log}}.\nRelease version: {{release_version}}.\nAudience for this changelog: {{audience}}.\nParse the commits into grouped categories (Features, Fixes, Breaking Changes, Chores/Internal), rewriting terse commit messages into clear, user-relevant descriptions and dropping noise commits like 'wip' or merge commits.\nFlag anything that looks like a breaking change so it can be double-checked before publishing.\nOutput as a markdown changelog entry for {{release_version}} with the grouped sections.",
    variables: ["commit_log", "release_version", "audience"],
    complexity: "Beginner",
  },
  {
    category: "Github Commands",
    title: "Pull Request Review Depth Checklist",
    body: "You are a senior engineer building a depth-focused PR review checklist, beyond just style nits.\nRepo/context: {{repo_context}}.\nThis PR's diff or summary: {{pr_diff}}.\nApply a checklist covering correctness of logic, test coverage for the change, backward compatibility, and whether the change matches its stated intent, going through the diff section by section.\nFor each concern raised, note whether it's a blocking issue or a suggestion.\nOutput as: Blocking Issues, Suggestions, Overall Merge Recommendation.",
    variables: ["repo_context", "pr_diff"],
    complexity: "Advanced",
  },
  {
    category: "Github Commands",
    title: "Static Analysis Findings Triage for CI",
    body: "You are a senior engineer triaging static analysis or linter findings surfaced in a CI run.\nCI tool and raw output: {{ci_findings_output}}.\nRepo context (language, criticality): {{repo_context}}.\nClassify each finding as a true positive worth fixing now, a true positive that can be deferred, or a likely false positive, with reasoning for each.\nFor true positives, suggest the minimal fix; for deferred items, suggest how to suppress with a documented reason rather than silently ignoring.\nOutput as a table: Finding, Classification, Reasoning, Suggested Action.",
    variables: ["ci_findings_output", "repo_context"],
    complexity: "Advanced",
  },
  {
    category: "Github Commands",
    title: "Repo Technical Debt Cleanup Plan",
    body: "You are a repo maintainer planning a git hygiene and technical debt cleanup.\nSymptoms in the repo (stale branches, huge history, bloated files): {{repo_symptoms}}.\nRepo size/activity level: {{repo_activity_level}}.\nConstraints (can't rewrite public history, etc.): {{constraints}}.\nPropose a cleanup plan addressing stale branch pruning, large file/history bloat, and inconsistent tagging, respecting the stated constraints (e.g., avoiding history rewrites on shared branches where unsafe).\nSequence the plan so higher-risk steps happen with the most caution and communication.\nOutput as a phased plan: Phase, Action, Risk Level, Communication Needed.",
    variables: ["repo_symptoms", "repo_activity_level", "constraints"],
    complexity: "Advanced",
  },
  {
    category: "Github Commands",
    title: "Branching Strategy Comparison",
    body: "You are a git workflow consultant comparing branching strategies for a team.\nTeam size and release cadence: {{team_and_cadence}}.\nCurrent pain points: {{current_pain_points}}.\nDeployment model (continuous vs scheduled releases): {{deployment_model}}.\nCompare trunk-based development against git-flow (and a lightweight GitHub-flow variant if relevant) on merge friction, release predictability, and suitability for the stated deployment model.\nRecommend the best fit for this team and describe the first two changes they'd need to make to adopt it.\nOutput as: Comparison Table, Recommendation, Adoption First Steps.",
    variables: ["team_and_cadence", "current_pain_points", "deployment_model"],
    complexity: "Advanced",
  },
  {
    category: "Github Commands",
    title: "Monorepo vs Polyrepo Comparison & Recommendation",
    body: "You are a platform engineer researching monorepo versus polyrepo structure for an organization.\nNumber and relationship of projects: {{project_landscape}}.\nTooling maturity (build systems, CI): {{tooling_maturity}}.\nTeam structure and ownership boundaries: {{team_structure}}.\nCompare the two approaches on cross-project changes, CI/build complexity, dependency versioning, and access control given the team structure, citing realistic trade-offs rather than a generic list.\nRecommend one structure with a rough migration outline if it differs from the current setup.\nOutput as: Comparison Table, Recommendation, Migration Outline.",
    variables: ["project_landscape", "tooling_maturity", "team_structure"],
    complexity: "Advanced",
  },
  {
    category: "Github Commands",
    title: "Git Bisect Investigation Plan",
    body: "You are a debugging-focused engineer planning a git bisect investigation.\nBug description and symptom: {{bug_description}}.\nApproximate range where it was introduced (last known good, first known bad): {{commit_range}}.\nHow to reproduce/test each commit: {{test_procedure}}.\nWalk me through a git bisect plan including the exact commands to start the bisect, how to script the test procedure so bisect can run automatically if possible, and how to interpret and communicate the result once the culprit commit is found.\nInclude what to do if the bug turns out to be non-deterministic.\nOutput as a numbered step-by-step plan with example commands.",
    variables: ["bug_description", "commit_range", "test_procedure"],
    complexity: "Intermediate",
  },
  {
    category: "Github Commands",
    title: "Release Tagging & Versioning Strategy",
    body: "You are a release manager designing a tagging and versioning strategy.\nVersioning scheme desired (e.g., semver): {{versioning_scheme}}.\nRelease cadence: {{release_cadence}}.\nDownstream consumers of this repo: {{downstream_consumers}}.\nDesign a tagging strategy covering when to bump major/minor/patch, how pre-releases/release candidates should be tagged, and how tags map to CI/CD deployment triggers, considering the needs of the stated downstream consumers.\nInclude the exact git commands for creating and pushing an annotated release tag.\nOutput as: Versioning Rules, Tagging Workflow, Example Commands.",
    variables: ["versioning_scheme", "release_cadence", "downstream_consumers"],
    complexity: "Intermediate",
  },
  {
    category: "Github Commands",
    title: "GitHub Issue Template Designer",
    body: "You are a maintainer designing GitHub issue templates.\nProject type: {{project_type}}.\nMost common issue types received: {{common_issue_types}}.\nInformation you consistently have to ask reporters for: {{missing_info_pattern}}.\nDesign issue templates (bug report, feature request, and any others implied by the common issue types) using GitHub's YAML issue form format, front-loading the fields that address the missing-info pattern so triagers stop re-asking the same questions.\nInclude sensible default labels for each template.\nOutput as YAML issue form definitions, one per template, ready to place in .github/ISSUE_TEMPLATE/.",
    variables: ["project_type", "common_issue_types", "missing_info_pattern"],
    complexity: "Intermediate",
  },
  {
    category: "Github Commands",
    title: "CODEOWNERS File Designer",
    body: "You are a repo maintainer designing a CODEOWNERS file.\nRepo structure/key directories: {{repo_structure}}.\nTeam/owner mapping: {{owner_mapping}}.\nReview policy goals (e.g., security-sensitive paths need extra review): {{review_goals}}.\nDesign a CODEOWNERS file that maps directories to the right owners, adds stricter coverage for security-sensitive paths per the stated goals, and avoids overly broad wildcard rules that would make review requests noisy.\nExplain any tricky precedence rules relevant to your proposed structure.\nOutput as the CODEOWNERS file content plus a short explanation of the precedence logic used.",
    variables: ["repo_structure", "owner_mapping", "review_goals"],
    complexity: "Intermediate",
  },
  {
    category: "Github Commands",
    title: "Git Hooks Setup Guide",
    body: "You are a developer productivity engineer setting up git hooks for a team.\nChecks we want enforced before commit/push (lint, format, tests): {{desired_checks}}.\nTooling already in use (e.g., husky, pre-commit): {{existing_tooling}}.\nTeam's tolerance for slow hooks: {{speed_tolerance}}.\nDesign a git hooks setup that enforces the desired checks at the right stage (pre-commit vs pre-push) balancing thoroughness against the team's stated speed tolerance, and explain how to let developers bypass a hook in a genuine emergency without normalizing it.\nProvide example hook script content.\nOutput as: Hook-by-Hook Plan, Example Script, Bypass Policy Note.",
    variables: ["desired_checks", "existing_tooling", "speed_tolerance"],
    complexity: "Intermediate",
  },
  {
    category: "Github Commands",
    title: "Large File / Git LFS Migration Plan",
    body: "You are a git infrastructure engineer planning a migration to Git LFS.\nTypes and rough size of large files currently in the repo: {{large_file_description}}.\nRepo history size/age: {{history_size}}.\nConstraints (can collaborators tolerate a history rewrite?): {{collaboration_constraints}}.\nPlan the LFS migration including which file patterns to track, whether a history rewrite is needed to reclaim space versus tracking large files only going forward, and how to communicate the change to all collaborators so no one's local clone breaks unexpectedly.\nInclude the key git lfs commands involved.\nOutput as: Migration Approach, Commands, Collaborator Communication Plan.",
    variables: ["large_file_description", "history_size", "collaboration_constraints"],
    complexity: "Advanced",
  },
  {
    category: "Github Commands",
    title: "Fork & Upstream Sync Workflow Guide",
    body: "You are a maintainer helping a contributor set up a fork-and-sync workflow.\nUpstream repo: {{upstream_repo}}.\nContributor's typical use case (occasional PR vs long-running fork): {{use_case}}.\nWrite a guide covering forking, adding upstream as a remote, keeping the fork's main branch in sync via rebase or merge, and handling the case where their feature branch has drifted far from upstream.\nInclude the exact git commands for each step.\nOutput as a numbered guide with commands, ending with a short 'if you get stuck' troubleshooting note.",
    variables: ["upstream_repo", "use_case"],
    complexity: "Beginner",
  },
  {
    category: "Github Commands",
    title: "Git Blame Investigation Assistant",
    body: "You are a debugging-focused engineer using git blame/log to investigate why a piece of code exists.\nFile and code section in question: {{code_section}}.\nWhat prompted the investigation: {{investigation_reason}}.\nWalk me through the git commands to trace the history of this section (including following renames and ignoring whitespace-only commits), and explain how to read the resulting history to understand intent versus incidental changes.\nSuggest what to do if the responsible author has left the team.\nOutput as a numbered investigation procedure with example commands and how to interpret the output at each step.",
    variables: ["code_section", "investigation_reason"],
    complexity: "Intermediate",
  },
  {
    category: "Github Commands",
    title: "Repository Access & Permissions Audit Plan",
    body: "You are a security-conscious engineering manager auditing repository access and permissions.\nOrganization/repo scope: {{repo_scope}}.\nCurrent known access issues (e.g., too many admins): {{known_issues}}.\nCompliance requirement driving this: {{compliance_requirement}}.\nDesign an audit covering who has admin versus write versus read access, whether branch protection and required reviews are correctly configured, and whether any service tokens have excessive scope, tailored to the stated compliance requirement.\nProduce a remediation checklist for issues you'd expect to find.\nOutput as: Audit Checklist, Expected Findings, Remediation Steps.",
    variables: ["repo_scope", "known_issues", "compliance_requirement"],
    complexity: "Advanced",
  },
  {
    category: "Github Commands",
    title: "Git Stash Workflow Guide",
    body: "You are a developer productivity coach explaining an effective git stash workflow.\nScenario prompting the need to stash: {{scenario}}.\nHow many things they're often juggling at once: {{concurrent_work_context}}.\nExplain when to use stash versus a WIP commit versus a new branch, how to use named stashes to avoid losing track of multiple stashed changes, and how to safely recover a stash if it's accidentally dropped.\nInclude the exact commands for creating, listing, applying, and naming stashes.\nOutput as a short guide with a decision rule (stash vs commit vs branch) followed by command examples.",
    variables: ["scenario", "concurrent_work_context"],
    complexity: "Beginner",
  },

  // ===================== QA Testing =====================
  {
    category: "QA Testing",
    title: "Test Plan Documentation Writer",
    body: "You are a QA lead writing a formal test plan document.\nFeature/release under test: {{feature_description}}.\nScope and out-of-scope items: {{scope_details}}.\nTimeline and resources available: {{timeline_and_resources}}.\nWrite a test plan covering objectives, scope, test approach (types of testing to run), entry/exit criteria, environment and data needs, and risks with mitigations, tailored to the stated timeline and resources.\nMake exit criteria measurable rather than vague.\nOutput as a structured test plan document with clear headings matching the sections above.",
    variables: ["feature_description", "scope_details", "timeline_and_resources"],
    complexity: "Intermediate",
  },
  {
    category: "QA Testing",
    title: "Bug Report Template Designer",
    body: "You are a QA process owner designing a bug report template for the team.\nTracking tool in use: {{tracking_tool}}.\nCommon information currently missing from reports: {{missing_info_pattern}}.\nSeverity/priority scheme the team uses: {{severity_scheme}}.\nDesign a bug report template with fields for steps to reproduce, expected vs actual behavior, environment details, severity/priority per the stated scheme, and attachments, explicitly adding fields that address the commonly missing information.\nInclude a short filled-in example report using the template.\nOutput as: Template Fields (list), Example Filled Report.",
    variables: ["tracking_tool", "missing_info_pattern", "severity_scheme"],
    complexity: "Beginner",
  },
  {
    category: "QA Testing",
    title: "Test Case Documentation Standards Guide",
    body: "You are a QA lead establishing test case documentation standards for the team.\nCurrent inconsistencies observed: {{current_inconsistencies}}.\nTest management tool used: {{test_tool}}.\nTeam size and experience mix: {{team_composition}}.\nDefine a standard for how test cases should be titled, structured (preconditions, steps, expected result), and tagged for traceability back to requirements, directly addressing the inconsistencies observed.\nInclude 2 example test cases written to this standard for a simple feature.\nOutput as: Standard Definition, Example Test Cases.",
    variables: ["current_inconsistencies", "test_tool", "team_composition"],
    complexity: "Beginner",
  },
  {
    category: "QA Testing",
    title: "Test Coverage Gap Analysis",
    body: "You are a QA architect analyzing test coverage gaps.\nFeature or module under review: {{module_description}}.\nExisting test cases or suite summary: {{existing_tests_summary}}.\nKnown production incidents in this area: {{known_incidents}}.\nAnalyze the existing coverage against the feature's critical paths and the known incidents, identifying specific untested scenarios (edge cases, negative paths, integration points).\nPrioritize the gaps by risk of a real user-facing incident if left uncovered.\nOutput as a table: Gap, Why It Matters, Priority, Suggested Test Case.",
    variables: ["module_description", "existing_tests_summary", "known_incidents"],
    complexity: "Advanced",
  },
  {
    category: "QA Testing",
    title: "Flaky Test Diagnosis Assistant",
    body: "You are a test reliability engineer diagnosing a flaky test.\nTest name and what it verifies: {{test_description}}.\nFailure pattern observed (intermittent logs/errors): {{failure_pattern}}.\nTest environment/framework: {{test_environment}}.\nWalk through likely root causes for this flakiness such as timing/race conditions, shared state between tests, environment dependency, or improper waits, ranking them by likelihood given the observed failure pattern.\nFor the most likely cause, suggest a concrete fix and how to verify the fix actually resolved the flakiness rather than just hiding it.\nOutput as: Ranked Likely Causes, Recommended Fix, Verification Approach.",
    variables: ["test_description", "failure_pattern", "test_environment"],
    complexity: "Advanced",
  },
  {
    category: "QA Testing",
    title: "Test Case Quality Review",
    body: "You are a senior QA engineer reviewing a batch of test cases for quality, not just coverage.\nHere are the test cases: {{test_cases}}.\nFeature they test: {{feature_context}}.\nReview each for clarity of steps, whether expected results are specific and verifiable, unnecessary duplication, and whether preconditions are complete enough for another tester to execute without guessing.\nFor each weak test case, show a rewritten version.\nOutput as a table: Original Issue, Test Case, Rewritten Version.",
    variables: ["test_cases", "feature_context"],
    complexity: "Intermediate",
  },
  {
    category: "QA Testing",
    title: "Testing Framework Comparison & Recommendation",
    body: "You are a QA architect researching test automation framework options.\nApplication type and stack: {{application_stack}}.\nCandidate frameworks/tools: {{candidate_frameworks}}.\nTeam's current skills and CI setup: {{team_and_ci_context}}.\nCompare the candidates on setup complexity, execution speed, flakiness tendencies, reporting quality, and community support given the stated stack and team skills.\nRecommend one framework and outline the first proof-of-concept test you'd write to validate the choice.\nOutput as: Comparison Table, Recommendation, POC Test Outline.",
    variables: ["application_stack", "candidate_frameworks", "team_and_ci_context"],
    complexity: "Advanced",
  },
  {
    category: "QA Testing",
    title: "Unit vs E2E Test Investment Strategy",
    body: "You are a QA strategy lead deciding how to allocate testing investment across the test pyramid.\nCurrent test distribution (unit/integration/E2E): {{current_distribution}}.\nRecent incidents or pain points: {{recent_pain_points}}.\nTeam capacity for writing/maintaining tests: {{team_capacity}}.\nBased on research into test pyramid best practices, recommend a target distribution and prioritize where to invest first given the recent pain points and available capacity, explaining the trade-offs between fast/cheap unit tests and slower/more realistic E2E tests.\nOutput as: Current vs Target Distribution, Prioritized Investment Plan, Rationale.",
    variables: ["current_distribution", "recent_pain_points", "team_capacity"],
    complexity: "Advanced",
  },
  {
    category: "QA Testing",
    title: "Test Case Generator From Requirements",
    body: "You are a QA engineer generating test cases directly from requirements.\nRequirement or user story: {{requirement_text}}.\nAcceptance criteria, if provided: {{acceptance_criteria}}.\nApplication context: {{application_context}}.\nGenerate a comprehensive set of test cases covering positive paths, negative/invalid input paths, boundary conditions, and any implied non-functional checks (e.g., permissions), each with preconditions, steps, and expected result.\nMap each test case back to the specific acceptance criterion it verifies.\nOutput as a table: Test Case ID, Steps, Expected Result, Related Criterion.",
    variables: ["requirement_text", "acceptance_criteria", "application_context"],
    complexity: "Beginner",
  },
  {
    category: "QA Testing",
    title: "Exploratory Testing Charter Builder",
    body: "You are a QA lead building exploratory testing charters.\nArea/feature to explore: {{feature_area}}.\nRisk areas or recent changes: {{risk_areas}}.\nTime-box available: {{time_box}}.\nWrite exploratory testing charters following a 'Explore <area> with <resources> to discover <information>' structure, each scoped to fit within the time-box and targeted at the stated risk areas.\nInclude example test ideas/heuristics (e.g., boundary, error guessing) a tester could use as starting points within each charter.\nOutput as a set of charters, each with: Mission, Time-box, Starting Heuristics.",
    variables: ["feature_area", "risk_areas", "time_box"],
    complexity: "Intermediate",
  },
  {
    category: "QA Testing",
    title: "Regression Test Suite Designer",
    body: "You are a QA architect designing a regression test suite.\nApplication and its major features: {{application_features}}.\nHistory of past regressions/breakages: {{regression_history}}.\nAvailable execution time/frequency: {{execution_constraints}}.\nDesign a regression suite that prioritizes coverage of areas with a history of breaking and critical user flows, structuring it into tiers (smoke, core regression, full regression) that fit the stated execution constraints.\nRecommend which tier runs on every commit versus nightly versus pre-release.\nOutput as: Tiered Suite Structure, Test Areas per Tier, Execution Cadence.",
    variables: ["application_features", "regression_history", "execution_constraints"],
    complexity: "Advanced",
  },
  {
    category: "QA Testing",
    title: "Accessibility Testing Plan",
    body: "You are a QA engineer specializing in accessibility planning a testing effort.\nApplication/screens in scope: {{screens_in_scope}}.\nTarget conformance level (e.g., WCAG AA): {{conformance_level}}.\nAvailable tools (screen readers, automated scanners): {{available_tools}}.\nPlan accessibility testing covering automated scans, manual keyboard-only navigation, screen reader walkthroughs, and color contrast checks, mapped to the stated conformance level and available tools.\nPrioritize which screens to test first based on user traffic or criticality if that's a constraint.\nOutput as: Test Plan by Technique, Screens Prioritized, Pass/Fail Criteria per Technique.",
    variables: ["screens_in_scope", "conformance_level", "available_tools"],
    complexity: "Intermediate",
  },
  {
    category: "QA Testing",
    title: "Performance & Load Testing Plan",
    body: "You are a QA performance engineer planning load and performance testing.\nSystem/endpoint under test: {{system_description}}.\nExpected peak traffic/usage pattern: {{expected_load}}.\nAvailable tooling: {{available_tooling}}.\nDesign a performance test plan covering load, stress, and soak test scenarios appropriate to the expected peak traffic, define key metrics to capture (latency percentiles, error rate, throughput), and set pass/fail thresholds tied to business requirements.\nInclude how to safely ramp load to avoid taking down a shared environment.\nOutput as: Scenario Definitions, Metrics & Thresholds, Ramp-Up Safety Plan.",
    variables: ["system_description", "expected_load", "available_tooling"],
    complexity: "Advanced",
  },
  {
    category: "QA Testing",
    title: "API Contract Testing Guide",
    body: "You are a QA engineer setting up contract testing for an API.\nAPI/service and its consumers: {{api_and_consumers}}.\nContract testing tooling being considered: {{contract_tooling}}.\nCurrent integration issues between provider and consumers: {{current_issues}}.\nExplain how to set up consumer-driven contract tests that catch the stated integration issues before they reach production, covering how contracts are defined, verified against the provider, and integrated into each side's CI pipeline.\nAddress how to handle contract versioning as the API evolves.\nOutput as: Setup Steps, CI Integration Points, Versioning Guidance.",
    variables: ["api_and_consumers", "contract_tooling", "current_issues"],
    complexity: "Advanced",
  },
  {
    category: "QA Testing",
    title: "Test Automation Framework Selector",
    body: "You are a QA automation architect selecting a framework for a new automation initiative.\nApplication type(s) to automate: {{application_types}}.\nTeam's programming language preference: {{language_preference}}.\nReporting/CI integration needs: {{ci_needs}}.\nEvaluate 3-4 realistic framework options against ease of maintenance, cross-platform support, reporting quality, and how well they integrate with the stated CI needs, given the team's language preference.\nRecommend one and outline the folder/project structure for a starter automation project.\nOutput as: Evaluation Table, Recommendation, Starter Project Structure.",
    variables: ["application_types", "language_preference", "ci_needs"],
    complexity: "Advanced",
  },
  {
    category: "QA Testing",
    title: "Bug Triage & Severity Classifier",
    body: "You are a QA lead running a bug triage session.\nHere are the reported bugs: {{bug_list}}.\nProduct criticality context (revenue-impacting areas, user base size): {{product_context}}.\nRelease deadline: {{release_deadline}}.\nClassify each bug by severity and priority using clear criteria (e.g., data loss/crash = critical, cosmetic = low), factoring in the product context, and recommend which bugs must block the release deadline versus which can ship as known issues.\nFlag any bugs that need more information before they can be triaged confidently.\nOutput as a table: Bug, Severity, Priority, Blocks Release?, Notes.",
    variables: ["bug_list", "product_context", "release_deadline"],
    complexity: "Intermediate",
  },
  {
    category: "QA Testing",
    title: "Test Data Management Strategy",
    body: "You are a QA engineer designing a test data management strategy.\nTypes of data needed for testing (e.g., user accounts, transactions): {{data_types_needed}}.\nSensitivity/compliance concerns (PII, production data use): {{compliance_concerns}}.\nEnvironments needing data: {{target_environments}}.\nDesign a strategy for generating, masking/anonymizing, and refreshing test data across the stated environments that respects the compliance concerns, and recommend an approach for keeping data sets in sync with evolving schemas.\nInclude how to handle data needed for edge-case scenarios that are hard to generate naturally.\nOutput as: Data Sourcing Approach, Masking/Compliance Handling, Refresh Strategy.",
    variables: ["data_types_needed", "compliance_concerns", "target_environments"],
    complexity: "Intermediate",
  },
  {
    category: "QA Testing",
    title: "Cross-Browser/Device Testing Strategy",
    body: "You are a QA lead designing a cross-browser and cross-device testing strategy.\nProduct and its user base analytics (top browsers/devices): {{usage_analytics}}.\nCurrent testing gaps: {{current_gaps}}.\nBudget/tooling constraints: {{tooling_constraints}}.\nDesign a strategy that prioritizes browser/device combinations based on the usage analytics rather than testing everything equally, recommends which combinations to automate versus spot-check manually, and fits within the stated tooling constraints.\nAddress how to handle a critical bug that only reproduces on a low-priority device.\nOutput as: Priority Matrix, Automation vs Manual Split, Edge-Case Handling Note.",
    variables: ["usage_analytics", "current_gaps", "tooling_constraints"],
    complexity: "Intermediate",
  },
  {
    category: "QA Testing",
    title: "CI Test Pipeline Designer",
    body: "You are a QA engineer designing how automated tests run in CI.\nTest suite composition (unit/integration/E2E) and current run time: {{suite_composition}}.\nCurrent pain points (flaky failures blocking merges, slow pipelines): {{pain_points}}.\nDeployment frequency: {{deployment_frequency}}.\nDesign a CI test pipeline that parallelizes or stages tests appropriately, decides what must pass before merge versus before deploy, and includes a policy for handling flaky test failures without blocking unrelated work, addressing the stated pain points.\nOutput as: Pipeline Stage Diagram (described in steps), Merge/Deploy Gating Rules, Flaky Test Policy.",
    variables: ["suite_composition", "pain_points", "deployment_frequency"],
    complexity: "Advanced",
  },
  {
    category: "QA Testing",
    title: "Mocking & Stubbing Strategy Guide",
    body: "You are a QA/test architecture engineer designing a mocking and stubbing strategy.\nSystem under test and its external dependencies: {{external_dependencies}}.\nTest levels involved (unit, integration, contract): {{test_levels}}.\nCurrent issues (brittle mocks, tests that don't catch real bugs): {{current_issues}}.\nRecommend when to mock versus use real dependencies versus test doubles like fakes, per test level, and how to keep mocks in sync with real dependency behavior so they don't mask actual bugs, directly addressing the current issues described.\nInclude one concrete before/after example of a brittle mock being improved.\nOutput as: Strategy by Test Level, Before/After Example, Sync-Drift Prevention Tips.",
    variables: ["external_dependencies", "test_levels", "current_issues"],
    complexity: "Advanced",
  },
  {
    category: "QA Testing",
    title: "Security Testing Checklist Builder",
    body: "You are a QA engineer building a foundational security testing checklist (not a full pentest).\nApplication type: {{application_type}}.\nSensitive data/functionality involved: {{sensitive_functionality}}.\nCompliance drivers, if any: {{compliance_drivers}}.\nBuild a checklist covering common issues to manually verify such as input validation/injection basics, authentication/session handling, access control on sensitive endpoints, and exposure of sensitive data in responses or logs, tailored to what's sensitive in this application.\nMark items that likely require a specialist security review beyond this checklist.\nOutput as a checklist table: Item, How to Test, Needs Specialist Review?",
    variables: ["application_type", "sensitive_functionality", "compliance_drivers"],
    complexity: "Intermediate",
  },
  {
    category: "QA Testing",
    title: "Smoke Test Suite Designer",
    body: "You are a QA engineer designing a smoke test suite for fast build validation.\nApplication and its critical user flows: {{critical_flows}}.\nDeployment frequency and time budget for smoke tests: {{time_budget}}.\nEnvironments this will run in: {{target_environments}}.\nDesign a lean smoke test suite covering only the flows whose failure would justify blocking a deploy, staying within the stated time budget, and specify what a failure should trigger (auto-rollback, alert, manual review) per environment.\nExplicitly list what you deliberately excluded and why.\nOutput as: Smoke Test List, Failure Response by Environment, Explicit Exclusions.",
    variables: ["critical_flows", "time_budget", "target_environments"],
    complexity: "Beginner",
  },
  {
    category: "QA Testing",
    title: "Test Environment Setup Guide",
    body: "You are a QA engineer documenting how to set up a test environment.\nApplication and its dependencies (databases, third-party services): {{app_dependencies}}.\nEnvironment type (local, staging, ephemeral): {{environment_type}}.\nCommon setup failures new testers hit: {{common_setup_failures}}.\nWrite a setup guide covering prerequisites, configuration steps, seeding required test data, and verifying the environment is healthy before testing begins, proactively addressing the common setup failures inline.\nInclude a quick smoke check a tester can run to confirm the environment is ready.\nOutput as a numbered setup guide ending with a 'Verify Your Environment' checklist.",
    variables: ["app_dependencies", "environment_type", "common_setup_failures"],
    complexity: "Beginner",
  },
  {
    category: "QA Testing",
    title: "User Acceptance Testing (UAT) Plan",
    body: "You are a QA lead planning a User Acceptance Testing phase.\nFeature/release under test: {{feature_description}}.\nBusiness stakeholders participating: {{stakeholders}}.\nAcceptance criteria/business goals: {{acceptance_criteria}}.\nDesign a UAT plan covering scenario selection based on real business workflows, how to prepare non-technical stakeholders to test effectively, sign-off criteria tied to the stated acceptance criteria, and how to handle a stakeholder finding an issue that's actually a design preference rather than a defect.\nOutput as: UAT Scenarios, Stakeholder Instructions, Sign-off Criteria.",
    variables: ["feature_description", "stakeholders", "acceptance_criteria"],
    complexity: "Intermediate",
  },
  {
    category: "QA Testing",
    title: "Test Metrics & Reporting Dashboard Plan",
    body: "You are a QA manager designing a test metrics and reporting approach for leadership visibility.\nCurrent testing pain points leadership cares about: {{leadership_concerns}}.\nData sources available (test management tool, CI, bug tracker): {{data_sources}}.\nReporting cadence expected: {{reporting_cadence}}.\nRecommend which metrics actually indicate quality and risk (avoiding vanity metrics like raw test count) given the stated leadership concerns, how to source each from the available data, and how to present them so non-QA stakeholders understand trends at a glance.\nInclude one metric you'd deliberately avoid reporting and why it would be misleading.\nOutput as: Recommended Metrics Table, Data Source per Metric, Reporting Format Notes.",
    variables: ["leadership_concerns", "data_sources", "reporting_cadence"],
    complexity: "Advanced",
  },
];
