import type { SeedPrompt } from "./prompt-data";

export const seedPromptsBatchA: SeedPrompt[] = [
  // ===================== Data Scientist =====================
  {
    category: "Data Scientist",
    title: "Model Card Documentation Writer",
    body: "You are a machine learning documentation specialist writing a model card for responsible deployment.\nModel name: {{model_name}}.\nModel purpose and intended use: {{intended_use}}.\nTraining data description: {{training_data_description}}.\nKey evaluation metrics: {{evaluation_metrics}}.\nWrite a structured model card covering: Model Details, Intended Use and Out-of-Scope Uses, Training Data, Evaluation Results, Known Limitations and Biases, and Ethical Considerations.\nBe specific about the populations or scenarios where the model's performance is untested or likely weaker, rather than using vague disclaimers.\nFormat as markdown with clear headings suitable for pasting into an internal model registry.",
    variables: ["model_name", "intended_use", "training_data_description", "evaluation_metrics"],
    complexity: "Intermediate",
  },
  {
    category: "Data Scientist",
    title: "Data Dictionary Generator",
    body: "You are a data documentation specialist creating a data dictionary for a shared dataset.\nTable or dataset name: {{table_name}}.\nColumn list with brief notes: {{column_notes}}.\nIntended audience: {{audience}}.\nProduce a complete data dictionary with one row per field, including: field name, data type, plain-language description, valid value range or accepted categories, nullability, and an example value.\nFlag any fields whose meaning is ambiguous from the notes given and suggest a clarifying question to ask the data owner.\nOutput as a markdown table followed by a short section on known caveats (e.g., unreliable historical periods, deprecated columns) for the given audience to be aware of.",
    variables: ["table_name", "column_notes", "audience"],
    complexity: "Beginner",
  },
  {
    category: "Data Scientist",
    title: "Analysis Reproducibility Write-Up",
    body: "You are a research data scientist documenting an analysis so a colleague can reproduce it exactly.\nAnalysis goal: {{analysis_goal}}.\nData sources used: {{data_sources}}.\nKey steps performed (rough notes): {{analysis_steps}}.\nTools/environment: {{tools_environment}}.\nWrite a reproducibility write-up including: Objective, Data Sources and Access Instructions, Environment Setup (versions, dependencies), Step-by-Step Method, and Known Sources of Non-Determinism (e.g., random seeds, sampling, API rate limits).\nCall out any manual or ad-hoc steps that would need to be scripted for true reproducibility.\nEnd with a short checklist someone could run through to confirm they reproduced the same result.",
    variables: ["analysis_goal", "data_sources", "analysis_steps", "tools_environment"],
    complexity: "Intermediate",
  },
  {
    category: "Data Scientist",
    title: "Statistical Rigor Review of an Analysis",
    body: "You are a senior statistician reviewing an analysis for methodological rigor before it goes to stakeholders.\nAnalysis summary: {{analysis_summary}}.\nStatistical methods used: {{methods_used}}.\nSample size and data collection method: {{sample_details}}.\nCritique the analysis for common pitfalls: multiple comparisons without correction, confusing correlation with causation, underpowered sample sizes, selection bias, and misinterpretation of confidence intervals or p-values.\nFor each issue found, explain why it matters and how it could change the conclusion if uncorrected.\nEnd with a revised, more defensible interpretation of the findings and any additional analysis you'd recommend before presenting this externally.",
    variables: ["analysis_summary", "methods_used", "sample_details"],
    complexity: "Advanced",
  },
  {
    category: "Data Scientist",
    title: "Model Evaluation Critique",
    body: "You are a machine learning evaluation specialist scrutinizing a model's reported performance.\nModel type: {{model_type}}.\nReported metrics: {{reported_metrics}}.\nEvaluation setup description: {{evaluation_setup}}.\nCritique whether the evaluation setup actually supports the claimed performance: check for test set leakage, metric choice appropriateness for the problem's class balance, whether a naive baseline was compared, and whether the evaluation reflects real-world deployment conditions.\nIdentify the single biggest weakness in this evaluation and explain the risk it poses if the model ships as-is.\nEnd with a concrete revised evaluation plan (additional metrics, held-out slices, baseline comparisons) to run before trusting these results.",
    variables: ["model_type", "reported_metrics", "evaluation_setup"],
    complexity: "Advanced",
  },
  {
    category: "Data Scientist",
    title: "Analysis Reproducibility Audit",
    body: "You are a research integrity reviewer auditing a completed analysis for reproducibility gaps.\nAnalysis description: {{analysis_description}}.\nCode/notebook state: {{code_state}}.\nDocumentation currently available: {{existing_documentation}}.\nAudit the analysis against a reproducibility checklist: version-controlled code, pinned dependencies, documented data provenance, fixed random seeds, and a clear record of any manual data cleaning steps.\nFor each gap found, rate its severity (would block reproduction vs. minor inconvenience) and suggest the specific fix.\nEnd with a prioritized remediation list ordered by what would most likely change the reported conclusions if redone carefully.",
    variables: ["analysis_description", "code_state", "existing_documentation"],
    complexity: "Advanced",
  },
  {
    category: "Data Scientist",
    title: "Modeling Approach Recommendation from Research",
    body: "You are a machine learning research advisor helping me choose a modeling approach based on recent findings.\nProblem I'm solving: {{problem_description}}.\nCandidate approaches from papers or benchmarks I've found: {{candidate_approaches}}.\nMy team's constraints (data volume, compute, latency): {{constraints}}.\nCompare the candidate approaches on expected accuracy, implementation complexity, compute cost, and maintainability given my constraints, noting where the research evidence is strong versus where it's based on benchmarks that may not transfer to my setting.\nRecommend the single best approach to pursue first, with clear reasoning for why it beats the alternatives here.\nEnd with a short pilot plan (what to build first, what metric would validate the choice) before committing fully.",
    variables: ["problem_description", "candidate_approaches", "constraints"],
    complexity: "Advanced",
  },
  {
    category: "Data Scientist",
    title: "Benchmark Comparison and Modeling Plan",
    body: "You are a data science technical advisor helping me decide between modeling options after reviewing benchmark results.\nTask type: {{task_type}}.\nBenchmark or research findings I've collected: {{benchmark_findings}}.\nDeployment environment: {{deployment_environment}}.\nSummarize what the benchmark findings actually show versus what they don't (e.g., benchmark data may not match my deployment environment), then rank the modeling options by expected real-world performance rather than raw benchmark score alone.\nRecommend one option to move forward with and justify the choice against the two next-best contenders.\nOutput as: Findings Summary, Ranked Options with Trade-offs, Recommendation, and Risks to Monitor After Deployment.",
    variables: ["task_type", "benchmark_findings", "deployment_environment"],
    complexity: "Advanced",
  },
  {
    category: "Data Scientist",
    title: "SQL Query Optimization Advisor",
    body: "You are a data engineer helping optimize a slow analytical SQL query.\nQuery: {{sql_query}}.\nDatabase/warehouse: {{database_type}}.\nApproximate table sizes: {{table_sizes}}.\nDiagnose likely performance issues (missing indexes, unnecessary full scans, inefficient joins, lack of partitioning/pruning) given the database type and table sizes.\nProvide a rewritten, optimized version of the query and explain each change.\nEnd with how to verify the improvement (e.g., EXPLAIN plan comparison) and one indexing or partitioning change worth proposing to the data platform team.",
    variables: ["sql_query", "database_type", "table_sizes"],
    complexity: "Intermediate",
  },
  {
    category: "Data Scientist",
    title: "Dashboard Metric Definition Clarifier",
    body: "You are a data analyst helping resolve ambiguity in dashboard metric definitions.\nMetric name: {{metric_name}}.\nCurrent informal definition: {{current_definition}}.\nStakeholders who use it: {{stakeholders}}.\nPropose a precise, unambiguous definition of this metric, specifying the exact calculation, time window, inclusion/exclusion rules, and how edge cases (nulls, duplicates, refunds/reversals) should be handled.\nIdentify likely points of disagreement between the stakeholders given how each group probably interprets the metric today.\nEnd with a short 'metric contract' summary that could be pinned in the dashboard's documentation to prevent future confusion.",
    variables: ["metric_name", "current_definition", "stakeholders"],
    complexity: "Beginner",
  },
  {
    category: "Data Scientist",
    title: "Causal Inference Approach Advisor",
    body: "You are a causal inference specialist helping me choose a method to estimate a treatment effect from observational data.\nQuestion I want to answer: {{causal_question}}.\nData available: {{data_available}}.\nKnown confounders: {{known_confounders}}.\nRecommend a suitable causal inference approach (e.g., matching, regression adjustment, instrumental variables, difference-in-differences, propensity score methods) given the data and confounders described, explaining the identifying assumptions each requires.\nFlag which assumptions are most likely to be violated in this setting and what that would mean for the validity of the estimate.\nEnd with a sensitivity analysis suggestion to test how robust the conclusion is to unmeasured confounding.",
    variables: ["causal_question", "data_available", "known_confounders"],
    complexity: "Advanced",
  },
  {
    category: "Data Scientist",
    title: "Time Series Forecasting Model Selector",
    body: "You are a forecasting specialist helping me choose a time series modeling approach.\nSeries description: {{series_description}}.\nForecast horizon: {{forecast_horizon}}.\nKnown patterns (seasonality, trend, external drivers): {{known_patterns}}.\nRecommend 2-3 candidate approaches (e.g., classical statistical methods, gradient-boosted trees with lag features, or a neural forecasting model) ranked by fit for this horizon and pattern complexity.\nFor each, note data requirements, how it would handle the seasonality/trend described, and typical failure modes.\nEnd with a recommended backtesting scheme (rolling-origin evaluation) and which error metric best reflects business impact for this use case.",
    variables: ["series_description", "forecast_horizon", "known_patterns"],
    complexity: "Intermediate",
  },
  {
    category: "Data Scientist",
    title: "Class Imbalance Handling Strategy",
    body: "You are a machine learning specialist advising on class imbalance.\nProblem description: {{problem_description}}.\nClass distribution: {{class_distribution}}.\nBusiness cost of false negatives vs false positives: {{cost_asymmetry}}.\nRecommend an appropriate strategy (resampling, class weighting, threshold tuning, anomaly-detection framing) given the imbalance severity and cost asymmetry described.\nExplain why accuracy is likely a misleading metric here and which metrics (precision-recall AUC, F-beta, cost-weighted score) better reflect the real objective.\nEnd with a short validation plan that avoids the resampling leaking into the test set.",
    variables: ["problem_description", "class_distribution", "cost_asymmetry"],
    complexity: "Intermediate",
  },
  {
    category: "Data Scientist",
    title: "Data Storytelling Slide Outline",
    body: "You are a data storytelling coach helping me turn an analysis into a compelling presentation.\nKey finding: {{key_finding}}.\nAudience: {{audience}}.\nDecision this should inform: {{decision_context}}.\nOutline a slide-by-slide narrative (5-7 slides) that leads with the business implication before the methodology, uses one clear chart recommendation per slide, and anticipates the top objection this audience is likely to raise.\nFor each slide, give a one-sentence 'so what' takeaway rather than just a chart description.\nEnd with a suggested closing slide that ties the finding directly back to the decision context.",
    variables: ["key_finding", "audience", "decision_context"],
    complexity: "Beginner",
  },
  {
    category: "Data Scientist",
    title: "Synthetic Data Generation Plan",
    body: "You are a data scientist designing a synthetic data generation approach for testing or augmentation.\nUse case: {{use_case}}.\nReal data characteristics to preserve: {{data_characteristics}}.\nPrivacy or scale constraint: {{constraint}}.\nRecommend a synthetic data generation method (rule-based simulation, statistical resampling, or generative modeling) suited to this use case and constraint, explaining the trade-off between realism and the stated constraint.\nList which statistical properties of the real data must be validated in the synthetic output before it's trusted (distributions, correlations, rare-event frequency).\nEnd with a short validation checklist to run before using the synthetic data downstream.",
    variables: ["use_case", "data_characteristics", "constraint"],
    complexity: "Advanced",
  },
  {
    category: "Data Scientist",
    title: "Model Monitoring and Drift Detection Plan",
    body: "You are an MLOps specialist designing a post-deployment monitoring plan.\nModel purpose: {{model_purpose}}.\nInput features most likely to drift: {{drift_prone_features}}.\nDeployment environment: {{deployment_environment}}.\nDesign a monitoring plan covering: data drift detection (which statistical tests or distance metrics to use per feature type), prediction distribution monitoring, performance degradation detection when ground truth is delayed, and alert thresholds.\nRecommend a response playbook for when drift is detected (retrain, roll back, investigate upstream data change).\nEnd with a suggested review cadence and who should be notified for each severity level.",
    variables: ["model_purpose", "drift_prone_features", "deployment_environment"],
    complexity: "Advanced",
  },
  {
    category: "Data Scientist",
    title: "Sample Size and Power Calculator Walkthrough",
    body: "You are a biostatistics-trained consultant helping me compute a required sample size.\nEffect size I want to detect: {{effect_size}}.\nBaseline rate or variance: {{baseline_metric}}.\nDesired significance level and power: {{significance_and_power}}.\nWalk through the sample size calculation step by step, stating which formula or test applies given the metric type (proportion vs continuous), and compute the required sample size per group.\nExplain how the required size would change if the effect size assumption turns out to be optimistic.\nEnd with practical guidance on what to do if the required sample size is not achievable within a reasonable timeframe.",
    variables: ["effect_size", "baseline_metric", "significance_and_power"],
    complexity: "Intermediate",
  },
  {
    category: "Data Scientist",
    title: "Cross-Team Data Handoff Documentation",
    body: "You are a data scientist preparing a clean handoff of an analysis or model to another team.\nDeliverable being handed off: {{deliverable_description}}.\nReceiving team's technical background: {{receiving_team_background}}.\nOutstanding caveats or TODOs: {{outstanding_caveats}}.\nWrite a handoff document covering: What This Is, How to Run/Use It, Key Assumptions and Limitations, Known Issues and Workarounds, and Who to Contact for Questions.\nTailor the technical depth to the receiving team's background so nothing is assumed that they wouldn't know.\nEnd with a short 'if something breaks' troubleshooting section addressing the most likely failure points.",
    variables: ["deliverable_description", "receiving_team_background", "outstanding_caveats"],
    complexity: "Beginner",
  },

  // ===================== Managers =====================
  {
    category: "Managers",
    title: "Team Runbook Documentation Writer",
    body: "You are an operations-minded manager writing a team runbook.\nTeam function: {{team_function}}.\nRecurring task or process to document: {{process_to_document}}.\nCommon failure points people run into: {{common_failure_points}}.\nWrite a runbook entry with sections: Purpose, When to Use This, Step-by-Step Procedure, Common Pitfalls and How to Avoid Them, and Escalation Path if something goes wrong.\nWrite the steps specifically enough that someone doing this for the first time could follow them without needing to ask a teammate.\nEnd with a short 'last updated by / review cadence' note to keep the runbook from going stale.",
    variables: ["team_function", "process_to_document", "common_failure_points"],
    complexity: "Beginner",
  },
  {
    category: "Managers",
    title: "New Hire Onboarding Doc Builder",
    body: "You are a people manager building a 30-60-90 day onboarding document for a new hire.\nRole: {{role_title}}.\nTeam context: {{team_context}}.\nKey tools/systems they'll need access to: {{tools_and_systems}}.\nDraft an onboarding document structured by week 1, day 30, day 60, and day 90, with concrete learning goals, people to meet, and a small early win they could aim for in the first two weeks.\nInclude a checklist of access/setup items so nothing blocks their first day.\nEnd with how you'll check in with them at each milestone to calibrate whether onboarding is on track.",
    variables: ["role_title", "team_context", "tools_and_systems"],
    complexity: "Intermediate",
  },
  {
    category: "Managers",
    title: "Decision-Making Process Documentation",
    body: "You are a management consultant documenting how a recurring team decision should be made.\nDecision type: {{decision_type}}.\nCurrent (informal) process: {{current_process}}.\nStakeholders typically involved: {{stakeholders}}.\nWrite a clear process document specifying: who has decision rights (using a framework like RACI or DACI), what input is required before a decision is made, the escalation path if stakeholders disagree, and how the decision and its rationale should be recorded afterward.\nIdentify where the current informal process likely causes delays or unclear ownership.\nEnd with a one-page summary version suitable for pinning in a team wiki.",
    variables: ["decision_type", "current_process", "stakeholders"],
    complexity: "Intermediate",
  },
  {
    category: "Managers",
    title: "Team Decision Blind Spot Review",
    body: "You are an executive advisor helping me pressure-test a decision before I commit to it.\nDecision I'm about to make: {{decision_description}}.\nReasoning so far: {{current_reasoning}}.\nWho will be affected: {{affected_parties}}.\nIdentify likely blind spots in my reasoning: unexamined assumptions, groups whose perspective wasn't consulted, short-term optimization that could create longer-term cost, and confirmation bias in the evidence I've gathered.\nPlay devil's advocate and give the strongest counter-argument to the decision as currently framed.\nEnd with 2-3 questions I should answer before finalizing this decision, and who I should specifically ask given the affected parties.",
    variables: ["decision_description", "current_reasoning", "affected_parties"],
    complexity: "Advanced",
  },
  {
    category: "Managers",
    title: "Process Quality Gap Audit",
    body: "You are an operations consultant auditing a team process for quality gaps.\nProcess description: {{process_description}}.\nRecent issues or complaints tied to it: {{recent_issues}}.\nProcess owner: {{process_owner}}.\nAudit the process for common failure modes: unclear ownership at handoff points, missing quality checks before output reaches the next stage, single points of failure (bus factor), and lack of feedback loops to catch recurring issues early.\nMap each recent issue back to the specific process gap that most likely allowed it to happen.\nEnd with a prioritized list of process changes (quick fixes vs structural changes) and who should own implementing each.",
    variables: ["process_description", "recent_issues", "process_owner"],
    complexity: "Advanced",
  },
  {
    category: "Managers",
    title: "Team Restructuring Options Comparison",
    body: "You are an organizational design consultant helping me choose a team restructuring approach based on research and internal data I've gathered.\nCurrent team structure: {{current_structure}}.\nRestructuring options I'm considering: {{restructuring_options}}.\nBusiness driver behind this: {{business_driver}}.\nCompare the restructuring options against the business driver, weighing impact on collaboration, communication overhead, career growth paths, and short-term disruption during the transition.\nRecommend the single best option and justify why it outperforms the alternatives given the specific driver.\nEnd with a phased rollout plan and 2-3 risks to watch for during the transition, with a mitigation for each.",
    variables: ["current_structure", "restructuring_options", "business_driver"],
    complexity: "Advanced",
  },
  {
    category: "Managers",
    title: "Hiring Plan Recommendation from Market Research",
    body: "You are a workforce planning advisor helping me decide on a hiring approach based on research I've collected.\nRole(s) needed: {{roles_needed}}.\nMarket/compensation research findings: {{market_research}}.\nBudget and timeline constraints: {{constraints}}.\nCompare the realistic hiring options (senior hire vs junior-plus-mentorship, contractor vs full-time, internal transfer vs external search) against the market research and constraints given.\nRecommend the best plan and explain why it beats the alternatives on speed, cost, and risk.\nEnd with a suggested timeline with key milestones and a fallback plan if the primary approach stalls.",
    variables: ["roles_needed", "market_research", "constraints"],
    complexity: "Intermediate",
  },
  {
    category: "Managers",
    title: "Skip-Level Meeting Prep",
    body: "You are a leadership coach helping me prepare for a skip-level meeting.\nEmployee (my report's report): {{employee_name}}.\nWhat I currently know about their work: {{current_context}}.\nWhat I want to learn or signal: {{meeting_goal}}.\nDraft a set of 5-6 open-ended questions that would surface honest feedback about team health, management effectiveness, and blockers without putting the employee in an awkward position regarding their direct manager.\nSuggest how to frame the meeting's purpose at the start so it doesn't feel like an evaluation.\nEnd with guidance on what follow-up actions are appropriate versus what should be handled through the normal management chain.",
    variables: ["employee_name", "current_context", "meeting_goal"],
    complexity: "Intermediate",
  },
  {
    category: "Managers",
    title: "Team Health Check Survey Designer",
    body: "You are an organizational psychologist designing a lightweight team health check survey.\nTeam context: {{team_context}}.\nSpecific concerns to probe: {{specific_concerns}}.\nDesired frequency: {{frequency}}.\nDesign a short survey (8-10 items) covering psychological safety, workload sustainability, clarity of priorities, and manager support, phrased so responses are actionable rather than just a vague sentiment score.\nInclude a mix of Likert-scale and one or two open-ended questions targeted at the specific concerns given.\nEnd with guidance on how to share results back with the team transparently and turn the top 1-2 findings into concrete actions.",
    variables: ["team_context", "specific_concerns", "frequency"],
    complexity: "Intermediate",
  },
  {
    category: "Managers",
    title: "Cross-Functional Stakeholder Alignment Brief",
    body: "You are a program management advisor helping me align cross-functional stakeholders on a shared initiative.\nInitiative: {{initiative_name}}.\nStakeholders and their teams: {{stakeholders}}.\nKnown points of disagreement: {{disagreements}}.\nDraft a short alignment brief that states the shared goal, surfaces each stakeholder's likely priority or concern, and proposes a compromise position on each known disagreement.\nSuggest a meeting structure to work through the disagreements efficiently rather than relitigating them repeatedly.\nEnd with a one-paragraph summary I could send beforehand so no one is surprised in the room.",
    variables: ["initiative_name", "stakeholders", "disagreements"],
    complexity: "Intermediate",
  },
  {
    category: "Managers",
    title: "Underperformance Root Cause Diagnostic",
    body: "You are an experienced manager helping me diagnose why a team member's performance has declined.\nEmployee: {{employee_name}}.\nObserved symptoms: {{observed_symptoms}}.\nRecent changes in their context (workload, team, personal): {{recent_changes}}.\nWalk through the most common root causes of underperformance (unclear expectations, skill gap, motivation/engagement issue, personal circumstances, poor fit with current work) and rank which are most plausible given the symptoms and recent changes.\nFor the top 2 hypotheses, suggest a specific, low-pressure way to explore them in conversation.\nEnd with guidance on when this shifts from a coaching conversation to a formal performance process.",
    variables: ["employee_name", "observed_symptoms", "recent_changes"],
    complexity: "Advanced",
  },
  {
    category: "Managers",
    title: "Budget Reallocation Recommendation",
    body: "You are a finance-savvy operations manager helping me decide how to reallocate a team budget based on research and usage data.\nCurrent budget allocation: {{current_allocation}}.\nUsage/ROI data gathered: {{usage_data}}.\nStrategic priority for next period: {{strategic_priority}}.\nCompare the plausible reallocation options against the usage data and strategic priority, flagging any current spend that looks like it isn't earning its keep.\nRecommend a specific reallocation plan with rough percentages or amounts and justify the trade-offs versus keeping the status quo.\nEnd with how you'd monitor whether the reallocation is paying off within the next one to two review cycles.",
    variables: ["current_allocation", "usage_data", "strategic_priority"],
    complexity: "Advanced",
  },
  {
    category: "Managers",
    title: "Manager Escalation Message Drafting",
    body: "You are a communications-savvy manager helping me escalate an issue to my own manager or leadership.\nIssue: {{issue_description}}.\nImpact if unresolved: {{impact}}.\nWhat I'm asking for: {{ask}}.\nDraft a concise escalation message that states the issue, its business impact, what I've already tried, and a specific, actionable ask, avoiding either downplaying the severity or sounding alarmist.\nKeep the tone professional and solution-oriented rather than purely complaint-driven.\nEnd with a suggested follow-up cadence if I don't hear back within a reasonable window.",
    variables: ["issue_description", "impact", "ask"],
    complexity: "Beginner",
  },
  {
    category: "Managers",
    title: "Remote Team Collaboration Norms Doc",
    body: "You are a distributed-team management consultant documenting collaboration norms.\nTeam composition (time zones, roles): {{team_composition}}.\nCurrent pain points: {{current_pain_points}}.\nTools in use: {{tools_in_use}}.\nWrite a team norms document covering: expected response times by channel, meeting-free/focus-time conventions, how decisions get documented for asynchronous visibility, and how to handle urgent issues across time zones.\nAddress the specific pain points given rather than generic remote-work advice.\nEnd with how the team should revisit and update these norms periodically.",
    variables: ["team_composition", "current_pain_points", "tools_in_use"],
    complexity: "Intermediate",
  },
  {
    category: "Managers",
    title: "Layoff or Headcount Reduction Conversation Prep",
    body: "You are an experienced HR-partnered manager preparing for an extremely sensitive conversation.\nSituation: {{situation_description}}.\nEmployee(s) affected: {{affected_employees}}.\nCompany-provided support available: {{support_available}}.\nHelp me prepare a compassionate, clear, and legally careful script for this conversation, covering how to deliver the core message directly without burying it, what practical information to provide (support available, next steps, timeline), and how to handle likely emotional reactions with empathy.\nFlag any phrasing that could create legal risk or false hope and suggest safer alternatives.\nEnd with guidance on how to support the remaining team afterward.",
    variables: ["situation_description", "affected_employees", "support_available"],
    complexity: "Advanced",
  },
  {
    category: "Managers",
    title: "Promotion Case Builder",
    body: "You are a manager-coaching assistant helping me build a strong promotion case for a team member.\nEmployee: {{employee_name}}.\nTarget level/role: {{target_level}}.\nEvidence of impact so far: {{evidence_of_impact}}.\nStructure a promotion case mapped to the typical evaluation dimensions for the target level (scope of impact, technical/functional depth, cross-team influence, leadership behaviors), matching each dimension to specific evidence rather than general praise.\nIdentify any dimension where the current evidence is thin and suggest what additional proof point could strengthen it before submission.\nEnd with a concise summary paragraph suitable for a promotion committee packet.",
    variables: ["employee_name", "target_level", "evidence_of_impact"],
    complexity: "Intermediate",
  },
  {
    category: "Managers",
    title: "Post-Incident Management Retrospective",
    body: "You are a management consultant facilitating a blameless retrospective after an operational incident.\nIncident summary: {{incident_summary}}.\nTeams involved: {{teams_involved}}.\nBusiness impact: {{business_impact}}.\nDraft a retrospective agenda and a set of guiding questions covering timeline reconstruction, contributing factors (not just the immediate trigger), what went well in the response, and what would have caught this earlier.\nExplicitly frame the questions to avoid assigning individual blame while still surfacing concrete process gaps.\nEnd with a template for turning findings into tracked action items with owners and due dates.",
    variables: ["incident_summary", "teams_involved", "business_impact"],
    complexity: "Advanced",
  },
  {
    category: "Managers",
    title: "Manager Time Audit and Prioritization Review",
    body: "You are a productivity coach helping a manager audit how their time is spent.\nRough breakdown of a typical week: {{time_breakdown}}.\nCurrent top priorities: {{top_priorities}}.\nBiggest frustration with current schedule: {{frustration}}.\nAnalyze the time breakdown against the stated priorities and identify mismatches (time going to low-leverage activities while priorities are neglected).\nRecommend specific changes: meetings to delegate or cut, blocks to protect for high-leverage work, and one habit change to address the stated frustration.\nEnd with a sample rebalanced weekly schedule reflecting the recommendations.",
    variables: ["time_breakdown", "top_priorities", "frustration"],
    complexity: "Beginner",
  },

  // ===================== Marketing =====================
  {
    category: "Marketing",
    title: "Campaign Brief Template Writer",
    body: "You are a marketing operations lead creating a reusable campaign brief template.\nTeam/function this template serves: {{team_function}}.\nTypical campaign types run: {{campaign_types}}.\nInformation stakeholders always end up chasing after the fact: {{missing_info_pain_points}}.\nDesign a standardized campaign brief template with sections covering objective, target audience, key message, budget and channels, timeline, success metrics, and approval sign-offs.\nMake sure the template explicitly captures the information stakeholders currently have to chase down after the fact.\nOutput the template with placeholder fields clearly marked, ready to be turned into a fillable document.",
    variables: ["team_function", "campaign_types", "missing_info_pain_points"],
    complexity: "Beginner",
  },
  {
    category: "Marketing",
    title: "Brand Style Guide Documentation Writer",
    body: "You are a brand designer writing the written portion of a brand style guide.\nBrand name: {{brand_name}}.\nCore brand attributes: {{brand_attributes}}.\nExisting visual elements (colors, fonts, logo usage notes): {{visual_elements}}.\nWrite the documentation sections for voice and tone (with 3 example do/don't sentence pairs), logo usage rules (clear space, minimum size, misuse examples), color usage guidance, and typography hierarchy rules.\nEnsure the tone-of-voice guidance is specific enough that two different writers would produce consistent copy from it.\nFormat as a style guide document with clear section headings ready to hand to freelancers or agencies.",
    variables: ["brand_name", "brand_attributes", "visual_elements"],
    complexity: "Intermediate",
  },
  {
    category: "Marketing",
    title: "Marketing Playbook Documentation",
    body: "You are a marketing operations specialist documenting a repeatable campaign playbook.\nCampaign type this playbook covers: {{campaign_type}}.\nPast learnings to bake in: {{past_learnings}}.\nTeam roles involved: {{team_roles}}.\nWrite a playbook covering: When to Use This Playbook, Step-by-Step Execution Timeline, Roles and Responsibilities, Channel-Specific Checklists, and Common Mistakes to Avoid (drawing on the past learnings given).\nMake the steps specific enough that a new team member could run the campaign type with minimal hand-holding.\nEnd with a short section on how to measure whether this playbook's approach is still working versus needs updating.",
    variables: ["campaign_type", "past_learnings", "team_roles"],
    complexity: "Intermediate",
  },
  {
    category: "Marketing",
    title: "Content Quality and Brand Consistency Review",
    body: "You are a brand quality reviewer auditing a piece of marketing content before publish.\nContent piece: {{content_piece}}.\nBrand voice guidelines: {{brand_voice_guidelines}}.\nTarget audience: {{target_audience}}.\nReview the content for brand voice consistency, clarity, factual/claim accuracy risk, and whether it actually resonates with the stated target audience rather than reading as generic.\nFor each issue found, quote the specific sentence or section, explain why it misses the mark, and suggest a rewritten version.\nEnd with an overall publish-readiness verdict (ready / needs minor edits / needs rework) and the single highest-priority fix.",
    variables: ["content_piece", "brand_voice_guidelines", "target_audience"],
    complexity: "Intermediate",
  },
  {
    category: "Marketing",
    title: "Campaign Performance Post-Mortem",
    body: "You are a marketing analytics lead running a rigorous campaign post-mortem.\nCampaign goal: {{campaign_goal}}.\nActual results versus target: {{results_vs_target}}.\nChannels and tactics used: {{channels_and_tactics}}.\nAnalyze likely reasons for the gap between actual results and target, considering targeting/audience fit, creative fatigue, channel mix, timing, and external market factors, and rank the most plausible contributing factors.\nBe honest about what worked well too, not just what underperformed, so it isn't discarded in the next campaign.\nEnd with 3 specific, testable changes to try next time and how you'd measure whether each change actually helped.",
    variables: ["campaign_goal", "results_vs_target", "channels_and_tactics"],
    complexity: "Advanced",
  },
  {
    category: "Marketing",
    title: "Marketing Claims Compliance Review",
    body: "You are a marketing compliance-minded reviewer checking copy for risky claims.\nCopy to review: {{copy_text}}.\nIndustry: {{industry}}.\nKnown regulatory sensitivities: {{regulatory_sensitivities}}.\nReview the copy for unsubstantiated superlatives, comparative claims that would require evidence, and any language that could be read as a guarantee or regulated claim given the industry and sensitivities noted.\nFor each risky phrase, explain the specific risk and suggest a safer rewrite that keeps the persuasive intent.\nEnd with a short list of claims that should be run past legal/compliance before publishing.",
    variables: ["copy_text", "industry", "regulatory_sensitivities"],
    complexity: "Advanced",
  },
  {
    category: "Marketing",
    title: "Campaign Strategy Recommendation from Market Research",
    body: "You are a marketing strategist recommending a campaign approach based on research I've gathered.\nProduct/offer: {{product_offer}}.\nMarket research findings: {{market_research_findings}}.\nStrategy options being considered: {{strategy_options}}.\nCompare the strategy options against the research findings, weighing audience fit, expected cost-efficiency, and speed to results.\nRecommend the single best strategy to pursue and justify why it outperforms the alternatives given what the research actually shows (not just gut feel).\nEnd with a phased execution plan and one leading indicator to check within the first two weeks that the chosen strategy is working.",
    variables: ["product_offer", "market_research_findings", "strategy_options"],
    complexity: "Advanced",
  },
  {
    category: "Marketing",
    title: "Channel Mix Recommendation from Benchmarks",
    body: "You are a media planning consultant recommending a channel mix based on benchmark data.\nBudget: {{budget}}.\nTarget audience: {{target_audience}}.\nBenchmark performance data by channel: {{benchmark_data}}.\nCompare the candidate channels against the benchmark data, weighing expected reach, cost-per-result, and fit with the target audience's typical media habits.\nRecommend a specific budget split across channels and justify why this mix beats an even split or a single-channel-only approach.\nEnd with how you'd reallocate mid-campaign if early data diverges from the benchmark expectations.",
    variables: ["budget", "target_audience", "benchmark_data"],
    complexity: "Intermediate",
  },
  {
    category: "Marketing",
    title: "Landing Page Conversion Copy Rewrite",
    body: "You are a conversion copywriter improving an underperforming landing page.\nCurrent page copy: {{current_copy}}.\nOffer: {{offer}}.\nKnown objections from users: {{known_objections}}.\nRewrite the headline, subheadline, and primary CTA to more directly address the value proposition and preempt the known objections.\nExplain what was weak about the original (buried value prop, generic CTA, no objection handling, etc.).\nEnd with 2 alternative headline variants for A/B testing and the hypothesis behind each.",
    variables: ["current_copy", "offer", "known_objections"],
    complexity: "Beginner",
  },
  {
    category: "Marketing",
    title: "Influencer/Partnership Brief Writer",
    body: "You are a partnerships marketing manager drafting a brief for an influencer or brand partner.\nPartner: {{partner_name}}.\nCampaign goal: {{campaign_goal}}.\nKey messages and mandatory disclosures: {{key_messages}}.\nWrite a partner brief covering campaign context, key messages to convey in their own voice, content format and deliverable expectations, timeline, and mandatory disclosure/compliance language.\nKeep creative guidance loose enough to preserve the partner's authentic voice while ensuring the key messages land.\nEnd with the approval process and how performance will be measured and shared back with the partner.",
    variables: ["partner_name", "campaign_goal", "key_messages"],
    complexity: "Beginner",
  },
  {
    category: "Marketing",
    title: "Customer Persona Refresh from Research",
    body: "You are a market research analyst updating a customer persona based on new research data.\nExisting persona summary: {{existing_persona}}.\nNew research findings: {{new_research_findings}}.\nBusiness segment: {{business_segment}}.\nCompare the existing persona against the new research findings and identify what's outdated, confirmed, or newly revealed.\nProduce an updated persona including demographics/firmographics, goals, pain points, buying triggers, and objections, clearly noting which details are backed by the new research versus carried over as assumptions.\nEnd with 2-3 implications this update should have on current messaging or targeting.",
    variables: ["existing_persona", "new_research_findings", "business_segment"],
    complexity: "Intermediate",
  },
  {
    category: "Marketing",
    title: "Marketing Attribution Model Explainer",
    body: "You are a marketing analytics consultant explaining attribution modeling choices.\nCurrent attribution approach: {{current_attribution_model}}.\nChannels involved in the customer journey: {{channels_involved}}.\nBusiness question we're trying to answer: {{business_question}}.\nExplain the strengths and blind spots of the current attribution model given the channels involved, and recommend whether a different model (first-touch, linear, time-decay, data-driven) would better answer the stated business question.\nBe explicit about what the recommended model would and would not tell us.\nEnd with one practical step to validate the model's output against a real-world signal (e.g., holdout test, incrementality test).",
    variables: ["current_attribution_model", "channels_involved", "business_question"],
    complexity: "Advanced",
  },
  {
    category: "Marketing",
    title: "Event/Webinar Promotion Plan",
    body: "You are an event marketing specialist building a promotion plan.\nEvent name and format: {{event_name}}.\nTarget registrants: {{target_audience}}.\nTimeline until the event: {{timeline}}.\nBuild a promotion plan with a countdown structure (e.g., save-the-date, mid-funnel nurture, last-chance push) across email, social, and any partner channels, specifying the goal and key message for each phase.\nInclude a registration-to-attendance nurture sequence to reduce no-shows.\nOutput as a timeline table with columns: Phase, Timing, Channel, Key Message, Goal.",
    variables: ["event_name", "target_audience", "timeline"],
    complexity: "Beginner",
  },
  {
    category: "Marketing",
    title: "Customer Testimonial and Case Study Outline",
    body: "You are a content marketer structuring a customer case study.\nCustomer/company: {{customer_name}}.\nProblem they had before using the product: {{problem_before}}.\nResults achieved: {{results_achieved}}.\nOutline a case study with sections: Customer Snapshot, Challenge, Solution, Results (with specific quantified outcomes where possible), and a pull-quote suggestion.\nSuggest 3 interview questions to ask the customer to surface a stronger, more specific quote than generic praise.\nEnd with a one-line summary suitable for use in sales collateral.",
    variables: ["customer_name", "problem_before", "results_achieved"],
    complexity: "Beginner",
  },
  {
    category: "Marketing",
    title: "Pricing Page Messaging Review",
    body: "You are a pricing and packaging messaging specialist reviewing a pricing page.\nCurrent pricing page copy/structure: {{pricing_page_content}}.\nPricing tiers: {{pricing_tiers}}.\nCommon prospect objections at this stage: {{common_objections}}.\nReview whether the page clearly communicates value per tier, handles the common objections proactively (e.g., with FAQ or reassurance copy), and guides the visitor toward the most likely-fit tier rather than leaving them to guess.\nFor each weak spot, suggest specific rewritten copy.\nEnd with one trust-building element (guarantee, social proof, FAQ) you'd recommend adding if missing.",
    variables: ["pricing_page_content", "pricing_tiers", "common_objections"],
    complexity: "Intermediate",
  },
  {
    category: "Marketing",
    title: "Marketing Budget Justification Memo",
    body: "You are a marketing leader writing a budget justification memo for leadership.\nBudget request: {{budget_request}}.\nExpected outcomes/ROI reasoning: {{expected_outcomes}}.\nWhat happens if not funded: {{opportunity_cost}}.\nWrite a concise memo with sections: Ask, Rationale (tied to business goals, not just channel tactics), Expected ROI and how it will be measured, and Risk of Inaction.\nAnticipate the most likely pushback from a finance-minded reader and address it directly rather than avoiding it.\nKeep the memo under 350 words and end with a clear, specific approval request.",
    variables: ["budget_request", "expected_outcomes", "opportunity_cost"],
    complexity: "Intermediate",
  },
  {
    category: "Marketing",
    title: "Referral Program Mechanics Design",
    body: "You are a growth marketing strategist designing a referral program.\nProduct: {{product_name}}.\nExisting customer incentive ideas: {{incentive_ideas}}.\nTarget referrer segment: {{target_segment}}.\nDesign the referral program mechanics: reward structure for both referrer and referee, qualifying action definition, and fraud/abuse guardrails appropriate for the target segment.\nExplain why the chosen incentive structure is likely to motivate the target segment specifically, rather than a generic cash-back offer.\nEnd with the key metric to track program health and a threshold that would signal the program needs adjustment.",
    variables: ["product_name", "incentive_ideas", "target_segment"],
    complexity: "Intermediate",
  },
  {
    category: "Marketing",
    title: "Marketing Automation Workflow Documentation",
    body: "You are a marketing operations specialist documenting an automation workflow.\nWorkflow purpose: {{workflow_purpose}}.\nTrigger and exit conditions: {{trigger_and_exit_conditions}}.\nTools involved: {{tools_involved}}.\nWrite documentation covering: Workflow Purpose and Goal, Trigger Logic and Exit Conditions, Step-by-Step Flow with branching logic explained, and Tools/Integrations Involved.\nInclude a troubleshooting section for the most likely failure point (e.g., a contact getting stuck or duplicated across branches).\nEnd with an ownership note on who should update this workflow when messaging or offers change.",
    variables: ["workflow_purpose", "trigger_and_exit_conditions", "tools_involved"],
    complexity: "Intermediate",
  },

  // ===================== UI/UX Developers =====================
  {
    category: "UI/UX Developers",
    title: "Design System Style Guide Documentation",
    body: "You are a design systems writer documenting the foundational style guide.\nDesign system name: {{design_system_name}}.\nCore visual tokens (colors, type scale, spacing): {{core_tokens}}.\nPlatforms it must support: {{platforms}}.\nWrite the style guide documentation covering: Design Principles, Color Usage (with accessibility contrast notes), Typography Scale and Usage Rules, and Spacing/Layout Grid Rules, tailored to work consistently across the platforms listed.\nInclude do/don't examples described in words for at least two of the sections.\nFormat with clear markdown headings suitable for a documentation site landing page.",
    variables: ["design_system_name", "core_tokens", "platforms"],
    complexity: "Intermediate",
  },
  {
    category: "UI/UX Developers",
    title: "Usability Test Report Writer",
    body: "You are a UX researcher writing up a usability test report.\nFeature tested: {{feature_tested}}.\nNumber and type of participants: {{participants}}.\nRaw observations/notes: {{raw_observations}}.\nWrite a usability test report with sections: Methodology, Key Findings (grouped by severity: critical, moderate, minor), Supporting Evidence/Quotes from the raw observations, and Recommendations mapped to each finding.\nAvoid over-generalizing from a small sample; note where findings are suggestive versus strongly supported given the participant count.\nEnd with a prioritized action list the product team could act on immediately.",
    variables: ["feature_tested", "participants", "raw_observations"],
    complexity: "Intermediate",
  },
  {
    category: "UI/UX Developers",
    title: "Component Usage Guidelines Documentation",
    body: "You are a design systems documentation specialist writing usage guidelines for a UI component.\nComponent: {{component_name}}.\nCommon misuse patterns observed: {{misuse_patterns}}.\nAccessible interaction requirements: {{accessibility_requirements}}.\nWrite usage guidelines covering: When to Use / When Not to Use, Content Guidelines (character limits, tone), Accessibility Requirements, and a Do/Don't comparison addressing the specific misuse patterns observed.\nMake the guidance concrete enough to settle real disagreements between designers and engineers about how the component should be used.\nFormat as markdown suitable for the component's documentation page.",
    variables: ["component_name", "misuse_patterns", "accessibility_requirements"],
    complexity: "Intermediate",
  },
  {
    category: "UI/UX Developers",
    title: "Heuristic Evaluation of a Screen",
    body: "You are a senior UX researcher conducting a formal heuristic evaluation.\nScreen or flow description: {{screen_description}}.\nHeuristic framework to use: {{heuristic_framework}}.\nUser context (device, urgency, expertise level): {{user_context}}.\nEvaluate the screen systematically against each heuristic in the given framework, citing a specific element for every violation found rather than general impressions.\nRate each violation's severity (cosmetic, minor, major, catastrophic) considering the user context described.\nOutput as a table: Heuristic, Violation Found, Severity, Recommended Fix, followed by a short summary of the top 3 issues to fix first.",
    variables: ["screen_description", "heuristic_framework", "user_context"],
    complexity: "Advanced",
  },
  {
    category: "UI/UX Developers",
    title: "Design Consistency Audit",
    body: "You are a design systems auditor reviewing a product for visual and interaction consistency.\nProduct/section audited: {{product_section}}.\nDesign system it should conform to: {{design_system_reference}}.\nScreens or components sampled: {{screens_sampled}}.\nAudit the sampled screens against the referenced design system for inconsistencies in spacing, color usage, component variants, and interaction patterns (e.g., different confirmation-dialog styles for similar actions).\nFor each inconsistency found, note which screen deviates, what the system-compliant version should look like, and the likely reason it drifted (one-off exception, missing component, outdated screen).\nEnd with a prioritized cleanup list ordered by user-visible impact.",
    variables: ["product_section", "design_system_reference", "screens_sampled"],
    complexity: "Advanced",
  },
  {
    category: "UI/UX Developers",
    title: "Usability Quality Gate Checklist",
    body: "You are a UX quality lead defining a pre-release usability quality gate.\nProduct area: {{product_area}}.\nHistorically common usability regressions: {{common_regressions}}.\nRelease type (major feature vs minor update): {{release_type}}.\nDefine a quality gate checklist covering interaction consistency, accessibility basics (keyboard nav, focus order, contrast), responsive behavior across breakpoints, and error/empty state handling, weighted toward catching the historically common regressions listed.\nScale the checklist's rigor appropriately to the release type so minor updates aren't over-burdened.\nEnd with a clear pass/fail criterion for each checklist item so it isn't subjective.",
    variables: ["product_area", "common_regressions", "release_type"],
    complexity: "Advanced",
  },
  {
    category: "UI/UX Developers",
    title: "Design Pattern Recommendation from UX Research",
    body: "You are a UX research-informed design advisor recommending a design pattern based on research I've gathered.\nInteraction problem to solve: {{interaction_problem}}.\nPattern options I'm considering, with research/precedent notes: {{pattern_options}}.\nUser context and constraints: {{user_context}}.\nCompare the pattern options against the research and precedent notes given, weighing learnability, accessibility, and fit with the user context and constraints.\nRecommend the single best pattern to implement and justify why it beats the alternatives for this specific context rather than just citing general best practice.\nEnd with one thing to validate with real users after implementation to confirm the pattern works as expected here.",
    variables: ["interaction_problem", "pattern_options", "user_context"],
    complexity: "Advanced",
  },
  {
    category: "UI/UX Developers",
    title: "Navigation Model Comparison and Recommendation",
    body: "You are a UX architecture advisor recommending a navigation model based on research findings.\nProduct description: {{product_description}}.\nNavigation options under consideration: {{navigation_options}}.\nResearch or analytics findings gathered so far: {{research_findings}}.\nCompare the navigation options against the research findings, weighing discoverability, scalability as features grow, and consistency with platform conventions.\nRecommend the option best supported by the evidence and explain specifically why the runner-up falls short for this product.\nEnd with a lightweight way to validate the recommendation before a full rebuild (e.g., a prototype test or card sort).",
    variables: ["product_description", "navigation_options", "research_findings"],
    complexity: "Advanced",
  },
  {
    category: "UI/UX Developers",
    title: "Empty State Design Brief",
    body: "You are a UX designer crafting an empty state experience.\nScreen/feature: {{feature_name}}.\nReason the state is empty (no data yet, filtered to zero results, error): {{empty_reason}}.\nDesired next action for the user: {{desired_action}}.\nDesign the empty state content and structure: headline, supporting copy, illustration/icon guidance, and a clear primary action button, tailored to the specific reason it's empty rather than a generic 'nothing here' message.\nExplain how the tone should shift if this is a first-time-use empty state versus a zero-results filter state.\nOutput as a short content and layout spec a developer could implement directly.",
    variables: ["feature_name", "empty_reason", "desired_action"],
    complexity: "Beginner",
  },
  {
    category: "UI/UX Developers",
    title: "Form Validation UX Review",
    body: "You are a UX specialist reviewing a form's validation experience.\nForm description: {{form_description}}.\nCurrent validation behavior: {{current_validation_behavior}}.\nCommon user errors observed: {{common_errors}}.\nReview the current validation behavior for timing (inline vs on-submit), clarity of error messages, and whether it helps users recover quickly from the common errors observed.\nRecommend specific improvements to error message copy and validation timing, explaining the UX principle behind each change.\nEnd with a short list of edge cases (paste events, autofill, slow typers) the validation logic should be tested against.",
    variables: ["form_description", "current_validation_behavior", "common_errors"],
    complexity: "Intermediate",
  },
  {
    category: "UI/UX Developers",
    title: "Design Handoff Readiness Checklist",
    body: "You are a design ops specialist creating a design-to-development handoff checklist.\nProject: {{project_name}}.\nDesign tool used: {{design_tool}}.\nCommon handoff issues the team has hit before: {{common_handoff_issues}}.\nBuild a checklist covering annotated states/interactions, responsive behavior notes, exported/linked assets, token or variable naming alignment with the codebase, and edge-case coverage (error, loading, empty).\nWeight the checklist toward directly preventing the common handoff issues named.\nEnd with a suggested sign-off step so designers and engineers both confirm readiness before development starts.",
    variables: ["project_name", "design_tool", "common_handoff_issues"],
    complexity: "Beginner",
  },
  {
    category: "UI/UX Developers",
    title: "Dark Mode Adaptation Review",
    body: "You are a UI engineer reviewing a design system's dark mode implementation.\nComponent or screen: {{component_or_screen}}.\nCurrent color token setup: {{color_token_setup}}.\nKnown visual issues reported: {{known_issues}}.\nReview whether the current token setup properly adapts contrast, elevation cues (shadows vs borders), and semantic colors (success/error/warning) for dark mode, diagnosing the likely cause of each known issue reported.\nRecommend specific token or implementation fixes, and flag any place a light-mode-only assumption (like a hardcoded hex value) is likely hiding in the code.\nEnd with a short manual QA checklist to verify dark mode across key screens.",
    variables: ["component_or_screen", "color_token_setup", "known_issues"],
    complexity: "Advanced",
  },
  {
    category: "UI/UX Developers",
    title: "Onboarding Flow Simplification",
    body: "You are a UX designer simplifying a product onboarding flow.\nCurrent onboarding steps: {{current_steps}}.\nDrop-off data if known: {{drop_off_data}}.\nCore value the product should demonstrate early: {{core_value}}.\nPropose a simplified onboarding flow that gets the user to the core value faster, identifying which current steps could be deferred, merged, or removed entirely, and why.\nUse the drop-off data if provided to prioritize which step to fix first.\nOutput as a before/after step list with a one-line rationale for each change.",
    variables: ["current_steps", "drop_off_data", "core_value"],
    complexity: "Intermediate",
  },
  {
    category: "UI/UX Developers",
    title: "Design Token Naming Convention Proposal",
    body: "You are a design systems engineer proposing a token naming convention.\nCurrent token examples (if any): {{current_tokens}}.\nPlatforms consuming the tokens: {{platforms}}.\nPain points with the current or absent convention: {{pain_points}}.\nPropose a layered naming convention (e.g., primitive, semantic, component-level tokens) that resolves the stated pain points and works cleanly across the listed platforms.\nGive 6-8 example token names under the new convention, showing how a designer or engineer would pick the right one for a given use case.\nEnd with a migration approach for renaming existing tokens without breaking consumers.",
    variables: ["current_tokens", "platforms", "pain_points"],
    complexity: "Advanced",
  },
  {
    category: "UI/UX Developers",
    title: "Mobile Gesture Interaction Spec",
    body: "You are a mobile UX designer specifying gesture-based interactions.\nFeature: {{feature_name}}.\nPlatform: {{platform}}.\nSimilar gestures already used elsewhere in the app: {{existing_gestures}}.\nSpecify the gesture interactions for this feature (tap, long-press, swipe, drag thresholds) ensuring consistency with the existing gestures listed so users aren't relearning conflicting patterns.\nDescribe the visual/haptic feedback expected at each interaction stage (start, in-progress, completion, cancel).\nEnd with accessibility considerations for users who cannot perform the specified gestures and what alternative interaction should be provided.",
    variables: ["feature_name", "platform", "existing_gestures"],
    complexity: "Advanced",
  },
  {
    category: "UI/UX Developers",
    title: "Responsive Breakpoint Strategy Review",
    body: "You are a front-end UX engineer reviewing a responsive design's breakpoint strategy.\nCurrent breakpoints used: {{current_breakpoints}}.\nKey content/components that break awkwardly: {{problem_areas}}.\nTarget device mix: {{device_mix}}.\nReview whether the current breakpoints are content-driven (based on where the layout actually breaks) versus arbitrary device-width guesses, given the target device mix.\nFor each problem area listed, diagnose the likely layout cause and propose a specific fix (new breakpoint, container query, flexible grid change).\nEnd with a recommendation on whether to add, remove, or consolidate breakpoints overall.",
    variables: ["current_breakpoints", "problem_areas", "device_mix"],
    complexity: "Intermediate",
  },
  {
    category: "UI/UX Developers",
    title: "Icon Set Consistency Review",
    body: "You are a visual design reviewer auditing an icon set for consistency.\nIcon set description: {{icon_set_description}}.\nStroke/style guidelines it should follow: {{style_guidelines}}.\nIcons flagged as inconsistent: {{flagged_icons}}.\nReview the flagged icons against the stated style guidelines for stroke weight, corner radius, optical sizing, and grid alignment, explaining specifically what deviates for each one.\nRecommend the corrected treatment for each flagged icon so it matches the rest of the set.\nEnd with a lightweight review process (e.g., a shared icon grid template) to prevent future inconsistencies as new icons are added.",
    variables: ["icon_set_description", "style_guidelines", "flagged_icons"],
    complexity: "Beginner",
  },
  {
    category: "UI/UX Developers",
    title: "Error State Messaging Standardization",
    body: "You are a UX writer standardizing error messaging across a product.\nSample error messages currently in use: {{sample_error_messages}}.\nProduct tone of voice: {{tone_of_voice}}.\nTechnical severity levels needed (e.g., recoverable vs blocking): {{severity_levels}}.\nReview the sample error messages for clarity, blame-avoidance (not blaming the user for system issues), and whether each gives the user a clear next action.\nPropose a standardized error message template per severity level, matching the stated tone of voice, and rewrite each sample message using it.\nEnd with 2-3 rules writers should follow when drafting new error messages going forward.",
    variables: ["sample_error_messages", "tone_of_voice", "severity_levels"],
    complexity: "Intermediate",
  },
];
