import type { SeedPrompt } from "./prompt-data";

export const seedPromptsBatchC: SeedPrompt[] = [
  // ===================== Azure =====================
  {
    category: "Azure",
    title: "Azure Incident Response Runbook Generator",
    body: "You are a cloud reliability engineer writing an incident response runbook for an Azure workload.\nThe workload is: {{workload_description}}.\nThe most common failure scenario I need to cover is: {{failure_scenario}}.\nOn-call team structure: {{oncall_structure}}.\nDraft a runbook with sections: Detection (which alerts/metrics fire), Triage Steps (in order, with Azure CLI/Portal actions), Escalation Path, Mitigation Steps, and Post-Incident Review Template.\nWrite each step specifically enough that an on-call engineer unfamiliar with this exact resource could follow it under pressure.\nEnd with a checklist of the top 5 things to verify before declaring the incident resolved.",
    variables: ["workload_description", "failure_scenario", "oncall_structure"],
    complexity: "Intermediate",
  },
  {
    category: "Azure",
    title: "Resource Group Architecture Documentation",
    body: "You are a cloud architect documenting a deployed Azure resource group for future maintainers.\nResource group contents: {{resource_group_contents}}.\nBusiness purpose of this environment: {{business_purpose}}.\nAudience for this doc: {{audience}}.\nWrite architecture documentation covering: a plain-language overview, a component list with each resource's role, data flow between components, key dependencies and naming conventions used, and known limitations or tech debt.\nInclude a short 'if this breaks, start here' section pointing to the most fragile parts.\nFormat as a markdown document with clear headings suitable for a team wiki.",
    variables: ["resource_group_contents", "business_purpose", "audience"],
    complexity: "Beginner",
  },
  {
    category: "Azure",
    title: "Disaster Recovery Plan Documentation",
    body: "You are a cloud resilience consultant documenting a disaster recovery plan for an Azure environment.\nWorkload: {{workload_description}}.\nRecovery objectives: RTO of {{rto_target}} and RPO of {{rpo_target}}.\nCurrent redundancy setup: {{current_redundancy}}.\nWrite a DR plan document covering: failure scenarios in scope, the failover procedure step-by-step (including which Azure services/regions are involved), data replication and consistency considerations, roles and responsibilities during a DR event, and a test/drill schedule to validate the plan stays accurate.\nHighlight any gap between the stated RTO/RPO and what the current setup can actually deliver.\nOutput as a structured document with numbered procedures a responder can follow during a real event.",
    variables: ["workload_description", "rto_target", "rpo_target", "current_redundancy"],
    complexity: "Advanced",
  },
  {
    category: "Azure",
    title: "Azure Security Hardening Review",
    body: "You are a cloud security engineer performing a hardening review of an Azure environment.\nEnvironment description: {{environment_description}}.\nCompliance framework I need to align with: {{compliance_framework}}.\nReview the setup for common Azure misconfigurations: overly permissive NSG rules, public storage endpoints, missing encryption at rest/in transit, weak Key Vault access policies, and missing diagnostic logging.\nFor each issue category, explain the risk, the specific Azure setting to check, and the remediation steps (CLI or Portal).\nOutput a prioritized findings table with columns: Finding, Risk Level, Affected Resource, Remediation, and a closing summary of the top 3 must-fix items before this passes {{compliance_framework}} review.",
    variables: ["environment_description", "compliance_framework"],
    complexity: "Advanced",
  },
  {
    category: "Azure",
    title: "Azure Reliability and Resilience Review",
    body: "You are a site reliability engineer reviewing an Azure architecture for resilience gaps.\nArchitecture summary: {{architecture_summary}}.\nAvailability target: {{availability_target}}.\nAssess single points of failure, zone/region redundancy, retry and circuit-breaker patterns in the application tier, autoscaling configuration, and dependency health checks.\nFor each gap found, explain the failure mode it exposes and a concrete fix (e.g., availability zones, Traffic Manager, Front Door, queue-based load leveling).\nEnd with a ranked list of the 3 changes that would most improve resilience relative to effort, and note any that are required to realistically hit {{availability_target}}.",
    variables: ["architecture_summary", "availability_target"],
    complexity: "Advanced",
  },
  {
    category: "Azure",
    title: "Bicep Template Quality Review",
    body: "You are a principal cloud engineer reviewing Infrastructure-as-Code quality for an Azure Bicep template.\nHere is the template: {{bicep_template}}.\nDeployment context: {{deployment_context}}.\nReview for: hardcoded values that should be parameters, missing resource tags, lack of module reuse, unsafe defaults (e.g., public access enabled by default), and missing outputs needed by downstream pipelines.\nFor each issue, quote the relevant snippet, explain why it's a problem, and provide a corrected version.\nConclude with a short list of best-practice conventions (naming, parameterization, module structure) this template should adopt going forward.",
    variables: ["bicep_template", "deployment_context"],
    complexity: "Advanced",
  },
  {
    category: "Azure",
    title: "Azure Monitoring and Observability Gap Analysis",
    body: "You are an observability specialist auditing monitoring coverage for an Azure application.\nApplication description: {{application_description}}.\nCurrent monitoring setup: {{current_monitoring_setup}}.\nBusiness-critical user journeys: {{critical_journeys}}.\nIdentify gaps across metrics, logs, traces, and alerting: missing Application Insights instrumentation, absent availability tests, alerts without clear owners or runbooks, and dashboards that don't reflect the critical journeys listed.\nFor each gap, recommend the specific Azure Monitor / Application Insights feature to close it.\nOutput as a gap analysis table (Area, Current State, Gap, Recommendation) followed by a prioritized 30/60/90-day improvement plan.",
    variables: ["application_description", "current_monitoring_setup", "critical_journeys"],
    complexity: "Advanced",
  },
  {
    category: "Azure",
    title: "Azure Compute Hosting Options Comparison",
    body: "You are a cloud solutions architect helping me choose the best compute hosting model on Azure.\nWorkload characteristics: {{workload_characteristics}}.\nTeam's operational maturity: {{ops_maturity}}.\nBudget constraints: {{budget_constraints}}.\nResearch and compare Azure App Service, Azure Container Apps, AKS, and Azure Functions against this workload, covering scaling behavior, operational overhead, cost profile, and cold-start/latency characteristics for each.\nWeigh the trade-offs explicitly against the stated ops maturity and budget.\nEnd with a clear recommended plan: which option to choose, why, and a brief migration/adoption path if we start simple and need to graduate to a more complex option later.",
    variables: ["workload_characteristics", "ops_maturity", "budget_constraints"],
    complexity: "Advanced",
  },
  {
    category: "Azure",
    title: "Azure Database Options Comparison and Recommendation",
    body: "You are a data platform architect recommending a database service on Azure.\nData shape and access patterns: {{data_patterns}}.\nExpected scale: {{expected_scale}}.\nConsistency and latency requirements: {{consistency_requirements}}.\nCompare Azure SQL Database, Cosmos DB, and Azure Database for PostgreSQL against these requirements, covering consistency models, scaling approach, cost at the stated scale, and operational burden.\nCall out scenarios where each option would clearly be the wrong choice.\nConclude with a specific recommendation, the reasoning behind it, and a short list of risks or unknowns I should validate with a proof of concept before committing.",
    variables: ["data_patterns", "expected_scale", "consistency_requirements"],
    complexity: "Advanced",
  },
  {
    category: "Azure",
    title: "Azure Landing Zone Onboarding Guide",
    body: "You are a cloud platform engineer writing an onboarding guide for teams adopting a new Azure landing zone.\nLanding zone structure: {{landing_zone_structure}}.\nGovernance policies in place: {{governance_policies}}.\nWrite an onboarding guide covering: how to request a subscription/resource group, naming and tagging conventions to follow, the policies that will block non-compliant deployments and why, how to request policy exceptions, and where to find shared services (networking, logging, Key Vault).\nInclude a first-week checklist a new team can follow.\nFormat as a step-by-step guide with a troubleshooting FAQ at the end for the most common onboarding blockers.",
    variables: ["landing_zone_structure", "governance_policies"],
    complexity: "Intermediate",
  },
  {
    category: "Azure",
    title: "Azure Virtual Network Segmentation Design",
    body: "You are a network architect designing VNet segmentation for an Azure environment.\nWorkloads to place: {{workloads}}.\nSecurity/compliance requirements: {{security_requirements}}.\nDesign a VNet and subnet layout including hub-and-spoke vs flat topology recommendation, subnet segmentation by tier (web/app/data), NSG and route table strategy, and where to place private endpoints vs public-facing components.\nExplain the reasoning behind each segmentation decision in terms of blast-radius reduction and the stated security requirements.\nOutput the design as a labeled diagram description plus a table of subnets with purpose, CIDR guidance, and associated NSG rules.",
    variables: ["workloads", "security_requirements"],
    complexity: "Advanced",
  },
  {
    category: "Azure",
    title: "Azure Secrets Management Strategy",
    body: "You are a DevSecOps engineer designing a secrets management strategy for Azure workloads.\nApplication types involved: {{application_types}}.\nCurrent secret handling: {{current_secret_handling}}.\nDesign a strategy using Azure Key Vault covering: how secrets/certificates/keys should be structured and scoped, managed identity usage to avoid secrets in app config, rotation policy recommendations, and access policy vs RBAC model choice.\nCall out the specific risks in the current secret handling described and how the new design eliminates them.\nOutput as a migration plan with phases (assessment, Key Vault setup, app integration, rotation automation, decommission of old method).",
    variables: ["application_types", "current_secret_handling"],
    complexity: "Intermediate",
  },
  {
    category: "Azure",
    title: "Azure-to-Azure Region Migration Plan",
    body: "You are a cloud migration architect planning a region-to-region migration within Azure.\nCurrent environment: {{current_environment}}.\nTarget region: {{target_region}}.\nMigration constraints: {{migration_constraints}}.\nProduce a migration plan covering: resource inventory and dependency mapping, data migration approach for stateful services, DNS/traffic cutover strategy, rollback plan if the cutover fails, and a validation checklist to confirm parity post-migration.\nSequence the plan into phases with rough effort estimates per phase.\nEnd with the top 3 risks specific to this migration and mitigation for each.",
    variables: ["current_environment", "target_region", "migration_constraints"],
    complexity: "Advanced",
  },
  {
    category: "Azure",
    title: "Azure DevOps to GitHub Actions CI/CD Migration",
    body: "You are a DevOps engineer planning a CI/CD migration from Azure DevOps Pipelines to GitHub Actions for an Azure-hosted application.\nCurrent pipeline description: {{current_pipeline}}.\nDeployment targets: {{deployment_targets}}.\nMap the existing pipeline stages to GitHub Actions equivalents, covering secrets/service connection migration to OIDC federated credentials, artifact handling differences, and approval/gate equivalents for production deployments.\nFlag any Azure DevOps-specific features that don't have a direct GitHub Actions equivalent and suggest a workaround.\nOutput a side-by-side mapping table followed by a cutover plan that keeps both pipelines running in parallel until validated.",
    variables: ["current_pipeline", "deployment_targets"],
    complexity: "Intermediate",
  },
  {
    category: "Azure",
    title: "Azure Autoscaling Configuration Advisor",
    body: "You are a performance engineer configuring autoscaling for an Azure workload.\nService type: {{service_type}}.\nTraffic pattern: {{traffic_pattern}}.\nCost sensitivity: {{cost_sensitivity}}.\nRecommend an autoscaling configuration including the metric(s) to scale on, scale-out/scale-in thresholds and cooldown periods, minimum/maximum instance counts, and whether scheduled scaling should supplement metric-based scaling given the traffic pattern.\nExplain the trade-off between responsiveness and cost/thrashing for the thresholds you choose.\nOutput as a configuration summary plus a short rationale paragraph addressing the stated cost sensitivity.",
    variables: ["service_type", "traffic_pattern", "cost_sensitivity"],
    complexity: "Intermediate",
  },
  {
    category: "Azure",
    title: "Azure Kubernetes Service Upgrade Planning",
    body: "You are a Kubernetes platform engineer planning an AKS cluster version upgrade.\nCurrent cluster state: {{cluster_state}}.\nTarget version: {{target_version}}.\nWorkloads running on the cluster: {{workloads_running}}.\nProduce an upgrade plan covering: pre-upgrade compatibility checks (deprecated APIs, add-on compatibility), node pool upgrade sequencing to minimize downtime, PodDisruptionBudget considerations for the listed workloads, and a rollback strategy if the upgrade causes issues.\nInclude a validation checklist to run after each stage of the upgrade.\nOutput as a phased plan with clear go/no-go checkpoints.",
    variables: ["cluster_state", "target_version", "workloads_running"],
    complexity: "Advanced",
  },
  {
    category: "Azure",
    title: "Azure Storage Access Tiering Strategy",
    body: "You are a cloud storage consultant designing an access tiering strategy for Azure Blob Storage.\nData types and access patterns: {{data_access_patterns}}.\nRetention/compliance requirements: {{retention_requirements}}.\nRecommend a tiering strategy across Hot, Cool, Cold, and Archive tiers, including lifecycle management rules to automate transitions, and estimate the relative cost impact of the recommended policy versus an all-Hot baseline.\nAddress how retrieval latency from Archive tier affects the retention requirements described.\nOutput as a lifecycle policy summary (in plain language, translatable to a lifecycle management JSON rule) plus a short cost-benefit explanation.",
    variables: ["data_access_patterns", "retention_requirements"],
    complexity: "Intermediate",
  },
  {
    category: "Azure",
    title: "Azure Well-Architected Framework Self-Assessment",
    body: "You are a cloud advisor guiding me through a Well-Architected Framework self-assessment for an Azure workload.\nWorkload overview: {{workload_overview}}.\nPrimary business risk we're most worried about: {{primary_risk}}.\nWalk through the five pillars (Reliability, Security, Cost Optimization, Operational Excellence, Performance Efficiency) and for each, ask me 2-3 targeted questions to surface gaps relevant to the stated workload and primary risk.\nBased on plausible answers to those questions, produce a sample findings summary per pillar with a maturity rating (Low/Medium/High) and the single highest-impact improvement for that pillar.\nEnd with an overall prioritized action plan across all five pillars.",
    variables: ["workload_overview", "primary_risk"],
    complexity: "Advanced",
  },

  // ===================== AWS =====================
  {
    category: "AWS",
    title: "AWS Infrastructure Documentation Generator",
    body: "You are a cloud documentation specialist generating infrastructure documentation from a description of a deployed AWS stack.\nStack description: {{stack_description}}.\nIntended audience: {{audience}}.\nWrite documentation covering: a plain-language architecture overview, a resource inventory with purpose per resource, data and traffic flow between components, environment-specific configuration differences (dev/staging/prod), and operational contacts or ownership.\nInclude a 'common questions new team members ask' section with answers.\nFormat as a markdown document suitable for onboarding and long-term reference.",
    variables: ["stack_description", "audience"],
    complexity: "Beginner",
  },
  {
    category: "AWS",
    title: "AWS Well-Architected Review Write-Up",
    body: "You are a cloud consultant writing up the results of an AWS Well-Architected review.\nWorkload: {{workload_name}}.\nKey findings from the review session: {{key_findings}}.\nBusiness priorities: {{business_priorities}}.\nProduce a formal write-up structured by the six pillars (Operational Excellence, Security, Reliability, Performance Efficiency, Cost Optimization, Sustainability), summarizing the findings under each relevant pillar, assigning a risk level to each finding, and proposing a remediation owner and rough timeline.\nWeight the prioritization by the stated business priorities, not just technical severity.\nEnd with an executive summary paragraph suitable for leadership who won't read the full detail.",
    variables: ["workload_name", "key_findings", "business_priorities"],
    complexity: "Advanced",
  },
  {
    category: "AWS",
    title: "New AWS Account Onboarding Documentation",
    body: "You are a cloud platform engineer writing onboarding documentation for a newly provisioned AWS account.\nAccount purpose: {{account_purpose}}.\nOrganizational guardrails already applied: {{guardrails}}.\nWrite onboarding docs covering: how access is granted (SSO/IAM roles), the account's place in the AWS Organization structure, budget alerts and cost controls already configured, required tags and naming conventions, and how to request additional permissions or services.\nInclude a first-day checklist for a new engineer joining the team that owns this account.\nFormat as a step-by-step onboarding document with a short FAQ at the end.",
    variables: ["account_purpose", "guardrails"],
    complexity: "Beginner",
  },
  {
    category: "AWS",
    title: "AWS Security Hardening Review",
    body: "You are a cloud security engineer performing a hardening review of an AWS environment.\nEnvironment description: {{environment_description}}.\nCompliance framework to align with: {{compliance_framework}}.\nReview for common AWS misconfigurations: overly permissive IAM policies (wildcard actions/resources), public S3 buckets, unencrypted EBS volumes or RDS instances, missing MFA on privileged accounts, and security groups open to 0.0.0.0/0.\nFor each issue category, explain the risk, the specific AWS setting to check, and remediation steps (CLI or Console).\nOutput a prioritized findings table (Finding, Risk Level, Affected Resource, Remediation) and close with the top 3 must-fix items before {{compliance_framework}} review.",
    variables: ["environment_description", "compliance_framework"],
    complexity: "Advanced",
  },
  {
    category: "AWS",
    title: "AWS Reliability and Resilience Review",
    body: "You are a site reliability engineer reviewing an AWS architecture for resilience gaps.\nArchitecture summary: {{architecture_summary}}.\nAvailability target: {{availability_target}}.\nAssess single points of failure, multi-AZ vs single-AZ deployment of stateful services, retry/backoff and circuit-breaker patterns, health checks and failover configuration, and dependency coupling between services.\nFor each gap, explain the failure mode it exposes and a concrete fix (e.g., multi-AZ RDS, Route 53 failover, SQS-based decoupling, auto-scaling health checks).\nEnd with the 3 changes that most improve resilience relative to effort, noting which are required to realistically hit {{availability_target}}.",
    variables: ["architecture_summary", "availability_target"],
    complexity: "Advanced",
  },
  {
    category: "AWS",
    title: "Terraform AWS Module Quality Review",
    body: "You are a principal cloud engineer reviewing Infrastructure-as-Code quality for a Terraform module targeting AWS.\nModule code: {{terraform_code}}.\nDeployment context: {{deployment_context}}.\nReview for hardcoded values that should be variables, missing resource tags, unsafe defaults (public access, permissive security groups), missing lifecycle rules causing risky replacements, and lack of module reuse or output exposure needed downstream.\nFor each issue, quote the relevant snippet, explain the problem, and give a corrected version.\nConclude with a short set of conventions (naming, variable structure, state management) this module should adopt.",
    variables: ["terraform_code", "deployment_context"],
    complexity: "Advanced",
  },
  {
    category: "AWS",
    title: "AWS Observability Gap Analysis",
    body: "You are an observability specialist auditing monitoring coverage for an AWS application.\nApplication description: {{application_description}}.\nCurrent monitoring setup: {{current_monitoring_setup}}.\nBusiness-critical user journeys: {{critical_journeys}}.\nIdentify gaps across CloudWatch metrics/logs, X-Ray tracing, and alerting: missing custom metrics, absent synthetic canaries for the critical journeys, alarms without clear runbooks or owners, and log groups without retention or structured logging.\nFor each gap, recommend the specific AWS service/feature to close it.\nOutput a gap analysis table (Area, Current State, Gap, Recommendation) followed by a prioritized 30/60/90-day improvement plan.",
    variables: ["application_description", "current_monitoring_setup", "critical_journeys"],
    complexity: "Advanced",
  },
  {
    category: "AWS",
    title: "ECS vs EKS vs Lambda Compute Recommendation",
    body: "You are a cloud solutions architect helping me choose the best compute service on AWS.\nWorkload characteristics: {{workload_characteristics}}.\nTeam's Kubernetes/container experience: {{team_experience}}.\nBudget constraints: {{budget_constraints}}.\nResearch and compare ECS (Fargate), EKS, and Lambda against this workload, covering operational overhead, scaling behavior, cost profile, and cold-start/latency characteristics.\nWeigh the trade-offs explicitly against the stated team experience and budget.\nEnd with a clear recommended plan: which option to choose, why, and a migration path if we need to graduate to a more complex option as the workload grows.",
    variables: ["workload_characteristics", "team_experience", "budget_constraints"],
    complexity: "Advanced",
  },
  {
    category: "AWS",
    title: "AWS Database Options Comparison and Recommendation",
    body: "You are a data platform architect recommending a database service on AWS.\nData shape and access patterns: {{data_patterns}}.\nExpected scale: {{expected_scale}}.\nConsistency and latency requirements: {{consistency_requirements}}.\nCompare RDS (specify engine trade-offs), DynamoDB, and Aurora against these requirements, covering consistency models, scaling approach, cost at the stated scale, and operational burden.\nCall out scenarios where each option would clearly be the wrong choice.\nConclude with a specific recommendation, reasoning, and risks or unknowns to validate with a proof of concept before committing.",
    variables: ["data_patterns", "expected_scale", "consistency_requirements"],
    complexity: "Advanced",
  },
  {
    category: "AWS",
    title: "AWS Multi-Account Landing Zone Design",
    body: "You are a cloud platform architect designing a multi-account AWS landing zone using AWS Organizations.\nWorkloads/teams to onboard: {{workloads_teams}}.\nGovernance requirements: {{governance_requirements}}.\nDesign the account structure (e.g., security, log archive, shared services, per-workload accounts), the SCP guardrails to apply at each OU, and the centralized logging/monitoring approach across accounts.\nExplain the reasoning behind the account boundaries chosen in terms of blast-radius isolation and billing clarity.\nOutput as an account structure diagram description plus a table of OUs with their guardrails and purpose.",
    variables: ["workloads_teams", "governance_requirements"],
    complexity: "Advanced",
  },
  {
    category: "AWS",
    title: "AWS Secrets Manager Migration Strategy",
    body: "You are a DevSecOps engineer designing a secrets management strategy for AWS workloads.\nApplication types involved: {{application_types}}.\nCurrent secret handling: {{current_secret_handling}}.\nDesign a strategy using AWS Secrets Manager (or Parameter Store where appropriate) covering: how secrets should be structured and scoped per environment, IAM role usage to avoid long-lived credentials, rotation policy recommendations with Lambda rotation functions, and cost trade-offs between Secrets Manager and Parameter Store.\nCall out the specific risks in the current secret handling and how the new design eliminates them.\nOutput as a migration plan with phases (assessment, setup, app integration, rotation automation, decommission).",
    variables: ["application_types", "current_secret_handling"],
    complexity: "Intermediate",
  },
  {
    category: "AWS",
    title: "Cross-Region AWS Disaster Recovery Design",
    body: "You are a cloud resilience architect designing a cross-region disaster recovery plan for AWS.\nWorkload: {{workload_description}}.\nRecovery objectives: RTO of {{rto_target}} and RPO of {{rpo_target}}.\nCurrent architecture: {{current_architecture}}.\nRecommend a DR strategy (backup-and-restore, pilot light, warm standby, or multi-site active-active) that matches the stated RTO/RPO, including the specific AWS services needed for replication (e.g., cross-region S3 replication, RDS read replicas, Route 53 failover routing).\nExplain the cost-vs-recovery-speed trade-off between the strategy you recommend and a cheaper/more expensive alternative.\nOutput as a structured design document with a failover runbook outline.",
    variables: ["workload_description", "rto_target", "rpo_target", "current_architecture"],
    complexity: "Advanced",
  },
  {
    category: "AWS",
    title: "AWS CI/CD Pipeline Design with CodePipeline",
    body: "You are a DevOps engineer designing a CI/CD pipeline on AWS.\nApplication type: {{application_type}}.\nDeployment targets: {{deployment_targets}}.\nRelease requirements: {{release_requirements}}.\nDesign a pipeline using CodePipeline/CodeBuild/CodeDeploy (or GitHub Actions integrated with AWS where relevant) covering build stage validation, artifact storage, deployment strategy (blue/green, canary, or rolling) suited to the release requirements, and approval gates before production.\nExplain how rollback would work if a deployment fails health checks.\nOutput as a stage-by-stage pipeline diagram description plus a table of stages, tools, and gate criteria.",
    variables: ["application_type", "deployment_targets", "release_requirements"],
    complexity: "Intermediate",
  },
  {
    category: "AWS",
    title: "AWS Auto Scaling Configuration Advisor",
    body: "You are a performance engineer configuring Auto Scaling for an AWS workload.\nService type: {{service_type}}.\nTraffic pattern: {{traffic_pattern}}.\nCost sensitivity: {{cost_sensitivity}}.\nRecommend an Auto Scaling configuration including the CloudWatch metric(s) to scale on, scale-out/scale-in policies and cooldowns, minimum/maximum/desired capacity, and whether scheduled scaling should supplement metric-based scaling given the traffic pattern.\nExplain the trade-off between responsiveness and cost/thrashing for the thresholds chosen.\nOutput as a configuration summary plus a rationale paragraph addressing the stated cost sensitivity.",
    variables: ["service_type", "traffic_pattern", "cost_sensitivity"],
    complexity: "Intermediate",
  },
  {
    category: "AWS",
    title: "On-Premises to AWS Migration Plan",
    body: "You are a cloud migration architect planning a lift-and-shift or replatform migration from on-premises to AWS.\nCurrent environment: {{current_environment}}.\nMigration constraints: {{migration_constraints}}.\nTarget AWS services: {{target_services}}.\nProduce a migration plan covering: workload discovery and dependency mapping, migration strategy per workload (rehost/replatform/refactor) based on the 6 R's, data migration approach (e.g., DMS, Snowball, DataSync), cutover and rollback plan, and a post-migration validation checklist.\nSequence the plan into phases with rough effort estimates.\nEnd with the top 3 risks specific to this migration and mitigation for each.",
    variables: ["current_environment", "migration_constraints", "target_services"],
    complexity: "Advanced",
  },
  {
    category: "AWS",
    title: "S3 Storage Class Lifecycle Strategy",
    body: "You are a cloud storage consultant designing a lifecycle strategy for AWS S3 storage classes.\nData types and access patterns: {{data_access_patterns}}.\nRetention/compliance requirements: {{retention_requirements}}.\nRecommend a tiering strategy across S3 Standard, Standard-IA, Glacier Instant Retrieval, and Glacier Deep Archive, including lifecycle rules to automate transitions, and estimate the relative cost impact versus an all-Standard baseline.\nAddress how retrieval latency from Glacier tiers affects the retention requirements described.\nOutput as a lifecycle policy summary (translatable to an S3 lifecycle configuration) plus a short cost-benefit explanation.",
    variables: ["data_access_patterns", "retention_requirements"],
    complexity: "Intermediate",
  },
  {
    category: "AWS",
    title: "AWS Cost Anomaly Root Cause Investigation Guide",
    body: "You are a FinOps analyst investigating an unexpected AWS cost spike.\nCost and usage report summary: {{cost_report_summary}}.\nTimeframe of the spike: {{spike_timeframe}}.\nServices most affected: {{affected_services}}.\nWalk through a structured investigation approach: which Cost Explorer filters/groupings to check first, how to correlate the spike with deployment or traffic events, common root causes for the affected services listed (e.g., runaway Lambda concurrency, orphaned EBS volumes, cross-AZ data transfer), and how to confirm the actual root cause versus a coincidental correlation.\nEnd with a template for documenting the root cause and remediation for stakeholders.\nOutput as a step-by-step investigation guide.",
    variables: ["cost_report_summary", "spike_timeframe", "affected_services"],
    complexity: "Intermediate",
  },
  {
    category: "AWS",
    title: "VPC Peering vs Transit Gateway Networking Recommendation",
    body: "You are a network architect recommending an inter-VPC connectivity approach on AWS.\nNumber and layout of VPCs involved: {{vpc_layout}}.\nExpected growth in connected accounts/VPCs: {{growth_expectations}}.\nCompare VPC Peering and Transit Gateway for this scenario, covering routing complexity as the number of VPCs grows, cost differences, and bandwidth/latency characteristics.\nCall out the specific point at which peering's mesh complexity would become unmanageable given the stated growth expectations.\nConclude with a specific recommendation and a note on how to migrate from one approach to the other later if growth outpaces the initial choice.",
    variables: ["vpc_layout", "growth_expectations"],
    complexity: "Intermediate",
  },

  // ===================== Docker =====================
  {
    category: "Docker",
    title: "Dockerfile Documentation Comment Generator",
    body: "You are a DevOps engineer improving the documentation of a Dockerfile for future maintainers.\nHere is the Dockerfile: {{dockerfile_content}}.\nContext on what this image is used for: {{image_purpose}}.\nAdd clear, concise inline comments explaining the purpose of each stage and non-obvious instruction (why a base image was chosen, why a layer is ordered where it is, why a flag is used), without restating the obvious.\nAlso produce a short header comment block summarizing the image's purpose, build arguments, and exposed ports/volumes.\nReturn the fully commented Dockerfile followed by a brief summary of what was clarified and why.",
    variables: ["dockerfile_content", "image_purpose"],
    complexity: "Beginner",
  },
  {
    category: "Docker",
    title: "Container Operations Runbook",
    body: "You are a platform engineer writing a container operations runbook for an on-call team.\nApplication running in containers: {{application_description}}.\nOrchestration platform: {{orchestration_platform}}.\nCommon operational issue to cover: {{common_issue}}.\nWrite a runbook with sections: Detection (logs/metrics indicating the issue), Diagnostic Commands (docker/kubectl commands to run, in order), Common Root Causes, Remediation Steps, and Escalation Path.\nMake each step concrete enough for an engineer unfamiliar with this specific container to follow under pressure.\nEnd with a checklist of what to verify before closing out the incident.",
    variables: ["application_description", "orchestration_platform", "common_issue"],
    complexity: "Intermediate",
  },
  {
    category: "Docker",
    title: "Image Build Documentation for New Contributors",
    body: "You are a developer experience engineer writing image build documentation for new contributors.\nProject/repo context: {{project_context}}.\nBuild tooling in use: {{build_tooling}}.\nWrite documentation covering: prerequisites to build the image locally, the exact build command(s) with explanation of key flags/build args, how to run the resulting container locally with sample environment variables, how the image relates to any base/parent images, and how to publish a new tag to the registry.\nInclude a troubleshooting section for the 3 most likely build failures a newcomer would hit.\nFormat as a README-style markdown document.",
    variables: ["project_context", "build_tooling"],
    complexity: "Beginner",
  },
  {
    category: "Docker",
    title: "Container Security Configuration Audit",
    body: "You are a container security engineer performing a hardening review of a Docker deployment.\nDeployment description: {{deployment_description}}.\nCompliance requirement: {{compliance_requirement}}.\nReview for common Docker security issues: containers running as root, missing read-only root filesystem where feasible, use of the `latest` tag in production, secrets baked into image layers, missing resource limits, and unnecessary capabilities not dropped.\nFor each issue category, explain the risk, how to detect it, and the remediation (Dockerfile or run-time flag change).\nOutput a prioritized findings table (Finding, Risk Level, Location, Remediation) and close with the top 3 must-fix items before {{compliance_requirement}} review.",
    variables: ["deployment_description", "compliance_requirement"],
    complexity: "Advanced",
  },
  {
    category: "Docker",
    title: "Docker Compose Reliability Review",
    body: "You are a reliability engineer reviewing a Docker Compose setup for resilience gaps.\nHere is the compose file: {{compose_file}}.\nExpected traffic/usage pattern: {{usage_pattern}}.\nAssess restart policies, health checks and their effect on dependent service startup ordering, resource limits and their sufficiency for the stated usage pattern, volume persistence for stateful services, and single points of failure in the service topology.\nFor each gap, explain the failure mode it exposes and a concrete fix.\nEnd with the 3 changes that most improve reliability relative to effort.",
    variables: ["compose_file", "usage_pattern"],
    complexity: "Intermediate",
  },
  {
    category: "Docker",
    title: "Dockerfile and Compose Config Quality Review",
    body: "You are a principal platform engineer reviewing the quality of a Dockerfile and its accompanying docker-compose.yml.\nDockerfile: {{dockerfile_content}}.\nCompose file: {{compose_file}}.\nReview for layer bloat and cache-busting ordering issues, missing .dockerignore leading to bloated build context, inconsistent environment variable handling between the two files, missing pinned versions for base images or dependencies, and any drift between what the Dockerfile exposes and what compose actually wires up.\nFor each issue, quote the relevant snippet, explain the problem, and provide a corrected version.\nConclude with a short list of conventions this project should standardize on.",
    variables: ["dockerfile_content", "compose_file"],
    complexity: "Advanced",
  },
  {
    category: "Docker",
    title: "Container Observability Gap Analysis",
    body: "You are an observability specialist auditing monitoring coverage for a containerized application.\nApplication description: {{application_description}}.\nCurrent monitoring setup: {{current_monitoring_setup}}.\nOrchestration platform: {{orchestration_platform}}.\nIdentify gaps across container-level metrics (CPU/memory/restarts), application logs (structured vs unstructured, aggregation), and health/readiness probe coverage.\nFor each gap, recommend the specific tool or configuration to close it (e.g., cAdvisor, Prometheus exporters, log driver configuration, readiness probe tuning).\nOutput a gap analysis table (Area, Current State, Gap, Recommendation) followed by a prioritized 30/60/90-day improvement plan.",
    variables: ["application_description", "current_monitoring_setup", "orchestration_platform"],
    complexity: "Advanced",
  },
  {
    category: "Docker",
    title: "Container Orchestration Strategy Comparison",
    body: "You are a platform architect helping me choose a container orchestration strategy.\nWorkload characteristics: {{workload_characteristics}}.\nTeam's operational maturity: {{ops_maturity}}.\nScale expectations: {{scale_expectations}}.\nResearch and compare running plain Docker Compose, a managed container service (e.g., ECS/Cloud Run equivalent), and full Kubernetes for this workload, covering operational overhead, scaling ceiling, and how each fits the team's maturity level.\nWeigh the trade-offs explicitly against the stated scale expectations.\nEnd with a clear recommended plan: which option to adopt now, why, and the trigger conditions that would justify moving to a more complex option later.",
    variables: ["workload_characteristics", "ops_maturity", "scale_expectations"],
    complexity: "Advanced",
  },
  {
    category: "Docker",
    title: "Base Image Strategy Comparison and Recommendation",
    body: "You are a container platform engineer recommending a base image strategy.\nApplication runtime: {{application_runtime}}.\nSecurity and size priorities: {{security_size_priorities}}.\nCompare Alpine, slim/distroless, and full official base images for this runtime, covering image size, attack surface, library/glibc compatibility risks, and build/debugging convenience trade-offs.\nCall out scenarios where each option would clearly cause problems for this specific runtime.\nConclude with a specific recommendation, the reasoning behind it, and a fallback option if the recommended base image causes compatibility issues in testing.",
    variables: ["application_runtime", "security_size_priorities"],
    complexity: "Intermediate",
  },
  {
    category: "Docker",
    title: "Docker Volume Backup and Restore Strategy",
    body: "You are a platform engineer designing a backup and restore strategy for Docker volumes holding stateful data.\nServices using volumes: {{services_with_volumes}}.\nRecovery objectives: RTO of {{rto_target}} and RPO of {{rpo_target}}.\nDesign a backup strategy including backup frequency and tooling (e.g., volume snapshot approach, sidecar backup containers), where backups should be stored off-host, and a tested restore procedure with the exact commands needed.\nAddress how this strategy meets or falls short of the stated RTO/RPO.\nOutput as a structured plan with a step-by-step restore runbook a teammate could follow without prior context.",
    variables: ["services_with_volumes", "rto_target", "rpo_target"],
    complexity: "Intermediate",
  },
  {
    category: "Docker",
    title: "Container Registry Access and Promotion Strategy",
    body: "You are a DevOps engineer designing a container image promotion strategy across environments.\nRegistry in use: {{registry_type}}.\nEnvironments to support: {{environments}}.\nDesign a tagging and promotion strategy (e.g., immutable digests, environment-specific tags, promotion by re-tagging vs rebuilding) that ensures the exact image tested in staging is what runs in production.\nInclude access control recommendations for who can push to which repository/tag pattern.\nOutput as a strategy document with a diagram description of the promotion flow and a table of tag conventions per environment.",
    variables: ["registry_type", "environments"],
    complexity: "Intermediate",
  },
  {
    category: "Docker",
    title: "Docker Networking Troubleshooting Playbook",
    body: "You are a platform engineer writing a troubleshooting playbook for Docker networking issues.\nDeployment topology: {{deployment_topology}}.\nMost frequent connectivity symptom reported: {{symptom_description}}.\nWrite a playbook covering: how to check which network mode/driver is in use, commands to inspect container-to-container DNS resolution, how to verify port publishing and firewall rules, and how to distinguish an application-level issue from a networking issue.\nStructure it as a decision tree starting from the symptom described.\nEnd with a short list of the most common misconfigurations that cause this specific symptom.",
    variables: ["deployment_topology", "symptom_description"],
    complexity: "Intermediate",
  },
  {
    category: "Docker",
    title: "Multi-Container App CI/CD Integration Design",
    body: "You are a DevOps engineer designing CI/CD for a multi-container application.\nApplication components: {{application_components}}.\nCI/CD platform: {{cicd_platform}}.\nDesign a pipeline covering per-service build caching strategy, how to run integration tests against a docker-compose stack in CI, image tagging tied to commit SHA, and a deployment step that updates only the changed services rather than redeploying everything.\nExplain how this reduces both build time and deployment risk compared to a monolithic rebuild-everything pipeline.\nOutput as a stage-by-stage pipeline description plus a table of stages, tools, and triggers.",
    variables: ["application_components", "cicd_platform"],
    complexity: "Advanced",
  },
  {
    category: "Docker",
    title: "Container Resource Limits Tuning Guide",
    body: "You are a performance engineer tuning CPU and memory limits for containerized services.\nService description: {{service_description}}.\nObserved resource usage pattern: {{usage_pattern}}.\nHost/cluster capacity constraints: {{capacity_constraints}}.\nRecommend CPU and memory requests/limits, explaining the reasoning from the observed usage pattern, how to size in a way that avoids OOM kills while not over-provisioning given the capacity constraints, and how to validate the chosen limits under load.\nAddress the trade-off between limits that are too tight (throttling/OOM) versus too loose (poor bin-packing).\nOutput as a recommended configuration plus a short validation test plan.",
    variables: ["service_description", "usage_pattern", "capacity_constraints"],
    complexity: "Intermediate",
  },
  {
    category: "Docker",
    title: "Rootless Docker Migration Advisor",
    body: "You are a container security engineer advising on a migration to rootless Docker.\nCurrent Docker setup: {{current_setup}}.\nOrganizational security driver: {{security_driver}}.\nExplain what changes for the team when moving to rootless mode (networking limitations, volume permission handling, port binding below 1024, storage driver differences), assess whether the current setup described has any blockers, and give a step-by-step migration plan with a rollback option if issues surface.\nAddress how this migration specifically responds to the stated security driver.\nOutput as a migration plan document with a pre-migration checklist and a post-migration validation checklist.",
    variables: ["current_setup", "security_driver"],
    complexity: "Advanced",
  },
  {
    category: "Docker",
    title: "Docker Build Cache Optimization Diagnostic",
    body: "You are a build performance engineer diagnosing slow Docker image builds.\nDockerfile: {{dockerfile_content}}.\nObserved build time and where time is spent: {{build_time_observations}}.\nDiagnose which layers are invalidating the cache unnecessarily, whether dependency installation is properly separated from source code copying, whether multi-stage builds could reduce final image size and rebuild time, and whether BuildKit features (cache mounts, parallel stages) are being underused.\nFor each finding, quote the relevant instruction and give a corrected ordering or syntax.\nEnd with an estimate of the expected build-time improvement from the top 3 changes.",
    variables: ["dockerfile_content", "build_time_observations"],
    complexity: "Advanced",
  },
  {
    category: "Docker",
    title: "Health Check and Readiness Probe Design",
    body: "You are a reliability engineer designing health check and readiness probe configuration for a containerized service.\nService description: {{service_description}}.\nDependencies the service relies on: {{dependencies}}.\nDesign a HEALTHCHECK instruction (or orchestrator-level liveness/readiness probes) that accurately reflects whether the service can serve traffic, distinguishing liveness (is the process alive) from readiness (can it serve requests, including checking the listed dependencies where appropriate).\nExplain the risk of checks that are too shallow (false healthy) versus too aggressive (unnecessary restarts from transient dependency blips).\nOutput the recommended check configuration plus a short explanation of the interval, timeout, and retry values chosen.",
    variables: ["service_description", "dependencies"],
    complexity: "Intermediate",
  },
  {
    category: "Docker",
    title: "Dev-to-Prod Docker Environment Parity Advisor",
    body: "You are a platform engineer closing the gap between local development and production container environments.\nCurrent local dev setup: {{local_dev_setup}}.\nCurrent production setup: {{production_setup}}.\nIdentify parity gaps: differing base images or dependency versions, environment variables or feature flags that behave differently, volume-mounted code in dev versus baked-in code in prod, and any dev-only tooling that risks leaking into the production image.\nFor each gap, explain the risk it creates (the classic 'works on my machine' failure mode) and a concrete fix, such as a shared multi-stage Dockerfile or a docker-compose override file.\nOutput as a parity gap table (Gap, Risk, Fix) followed by a short recommended target-state description.",
    variables: ["local_dev_setup", "production_setup"],
    complexity: "Intermediate",
  },

  // ===================== Research Prompt =====================
  {
    category: "Research Prompt",
    title: "Structured Research Report Generator",
    body: "You are a research analyst producing a structured research report on {{topic}}.\nIntended audience: {{audience}}.\nKey questions the report must answer: {{key_questions}}.\nProduce a report with sections: Executive Summary, Background, Findings (organized by the key questions listed), Implications, and Open Questions for Further Research.\nWrite each finding with enough specificity to be actionable, and note where evidence is strong versus where it's speculative or based on limited sources.\nFormat as a formal document with clear headings suitable for {{audience}} to read without additional context.",
    variables: ["topic", "audience", "key_questions"],
    complexity: "Intermediate",
  },
  {
    category: "Research Prompt",
    title: "Annotated Bibliography Builder",
    body: "You are a research librarian helping me build an annotated bibliography on {{topic}}.\nSource list or types of sources I'm working from: {{source_list}}.\nFocus angle for the research: {{focus_angle}}.\nFor each source (or type of source if I haven't listed specific ones), produce an entry with: a citation-style reference, a 2-3 sentence summary of its core argument or findings, an assessment of its credibility/methodology, and a note on how it relates to the stated focus angle.\nGroup entries thematically rather than alphabetically if a thematic grouping would be more useful for {{topic}}.\nEnd with a short paragraph identifying which sources are most central versus peripheral to the focus angle.",
    variables: ["topic", "source_list", "focus_angle"],
    complexity: "Intermediate",
  },
  {
    category: "Research Prompt",
    title: "Research Findings Memo for Stakeholders",
    body: "You are a research lead writing a findings memo for non-technical stakeholders on {{topic}}.\nWhat prompted this research: {{research_trigger}}.\nDecision(s) this memo needs to inform: {{decision_context}}.\nWrite a memo with sections: Bottom Line Up Front (1-2 sentences), Why We Looked Into This, What We Found (plain-language, no jargon), What This Means for the Decision(s) at hand, and Confidence Level and Caveats.\nKeep the tone direct and avoid hedging language that obscures the actual takeaway.\nCap the memo at roughly 400 words so it's genuinely skimmable by a busy stakeholder.",
    variables: ["topic", "research_trigger", "decision_context"],
    complexity: "Beginner",
  },
  {
    category: "Research Prompt",
    title: "Research Summary Gap and Weakness Finder",
    body: "You are a skeptical peer reviewer examining an existing research summary on {{topic}}.\nHere is the summary: {{research_summary}}.\nWhat this summary will be used for: {{intended_use}}.\nIdentify gaps in the summary: claims made without cited evidence, questions the summary doesn't address but probably should given its intended use, sample size or scope limitations that aren't acknowledged, and any logical leaps from evidence to conclusion.\nFor each gap, explain why it matters for the intended use and suggest what additional research or caveat would fix it.\nOutput as a numbered list of gaps ordered from most to least concerning.",
    variables: ["topic", "research_summary", "intended_use"],
    complexity: "Advanced",
  },
  {
    category: "Research Prompt",
    title: "Source Credibility and Bias Evaluator",
    body: "You are a media literacy expert evaluating the credibility and potential bias of sources on {{topic}}.\nSources to evaluate: {{source_list}}.\nWhy credibility matters here: {{stakes_context}}.\nFor each source, assess: the author's or publisher's apparent expertise and track record, funding or institutional incentives that could bias the framing, whether claims are corroborated elsewhere or stand alone, and the overall reliability tier (high/medium/low) with justification.\nBe explicit about uncertainty when you don't have enough information to judge a source confidently rather than guessing.\nOutput as a table (Source, Expertise, Potential Bias, Corroboration, Reliability Tier) followed by an overall recommendation on which sources to weight most heavily.",
    variables: ["topic", "source_list", "stakes_context"],
    complexity: "Advanced",
  },
  {
    category: "Research Prompt",
    title: "Red-Team a Research Conclusion",
    body: "You are a rigorous devil's advocate red-teaming a research conclusion about {{topic}}.\nThe conclusion as currently stated: {{conclusion_statement}}.\nEvidence cited in support: {{supporting_evidence}}.\nConstruct the strongest possible steelmanned case against this conclusion: identify alternative explanations for the evidence, confounding variables that weren't controlled for, evidence that contradicts or complicates the conclusion, and ways the conclusion could be true but overstated in scope or certainty.\nThen assess how well the original conclusion holds up against this challenge, and state what evidence would need to exist to settle the disagreement.\nOutput as: Steelman Against, Rebuttal Assessment, and What Would Change My Mind.",
    variables: ["topic", "conclusion_statement", "supporting_evidence"],
    complexity: "Advanced",
  },
  {
    category: "Research Prompt",
    title: "Research-Backed Recommended Course of Action",
    body: "You are a strategic advisor synthesizing research on {{topic}} into a recommended course of action.\nResearch findings summary: {{research_findings}}.\nDecision to be made: {{decision_to_make}}.\nConstraints I'm operating under: {{constraints}}.\nSynthesize the findings into a clear recommendation: state the recommended action, the 2-3 strongest pieces of evidence supporting it, the main risks or ways this recommendation could be wrong, and what early warning signs would indicate we should change course.\nBe genuinely decisive rather than listing options without picking one, while being explicit about your confidence level.\nOutput as: Recommendation, Supporting Evidence, Key Risks, and Course-Correction Triggers.",
    variables: ["topic", "research_findings", "decision_to_make", "constraints"],
    complexity: "Advanced",
  },
  {
    category: "Research Prompt",
    title: "Strategy Selection from Competing Research Findings",
    body: "You are a decision analyst helping me choose between competing strategies based on research about {{topic}}.\nStrategy options under consideration: {{strategy_options}}.\nResearch evidence relevant to each: {{research_evidence}}.\nDecision criteria that matter most to me: {{decision_criteria}}.\nEvaluate each strategy option against the decision criteria using the research evidence provided, being explicit when evidence for one option is stronger or weaker than for another.\nRecommend the single best strategy, explain the reasoning, and note the specific conditions under which a different strategy would become the better choice.\nOutput as a comparison table followed by a clear final recommendation with justification and caveats.",
    variables: ["topic", "strategy_options", "research_evidence", "decision_criteria"],
    complexity: "Advanced",
  },
  {
    category: "Research Prompt",
    title: "Market Sizing Estimation Framework",
    body: "You are an analyst building a market sizing estimate for {{topic}}.\nKnown data points or assumptions I can provide: {{known_data_points}}.\nSizing approach preference (top-down, bottom-up, or both): {{sizing_approach}}.\nWalk through a structured estimation using the requested approach, stating each assumption explicitly, showing the calculation logic step by step, and producing a range (low/base/high) rather than a single false-precision number.\nIdentify which assumptions the estimate is most sensitive to, so I know what to validate first if I need more confidence.\nOutput as: Assumptions, Calculation Walkthrough, Resulting Range, and Most Sensitive Assumptions.",
    variables: ["topic", "known_data_points", "sizing_approach"],
    complexity: "Intermediate",
  },
  {
    category: "Research Prompt",
    title: "Stakeholder Impact Mapping",
    body: "You are a research analyst mapping stakeholder impact for {{topic}}.\nContext or decision driving this analysis: {{decision_context}}.\nKnown stakeholder groups: {{stakeholder_groups}}.\nFor each stakeholder group, identify how they are likely affected (directly or indirectly), their probable stance (supportive, neutral, opposed) and why, and their relative influence over the outcome.\nHighlight any stakeholder groups that are commonly overlooked in analyses like this one and explain why they matter here.\nOutput as a stakeholder map table (Group, Impact, Likely Stance, Influence Level) followed by a short paragraph on which stakeholders most need proactive engagement.",
    variables: ["topic", "decision_context", "stakeholder_groups"],
    complexity: "Intermediate",
  },
  {
    category: "Research Prompt",
    title: "Chronology and Timeline Builder",
    body: "You are a research assistant building a clear chronology of events related to {{topic}}.\nRaw information or sources I have: {{raw_information}}.\nWhat I need the timeline to clarify: {{clarification_goal}}.\nOrganize the information into a chronological timeline, noting dates or approximate periods, the key event at each point, and its significance to the stated clarification goal.\nFlag any gaps in the timeline where information is missing or dates are uncertain, rather than guessing to fill them in.\nOutput as a timeline table (Date/Period, Event, Significance) followed by a short narrative summary tying the sequence together.",
    variables: ["topic", "raw_information", "clarification_goal"],
    complexity: "Beginner",
  },
  {
    category: "Research Prompt",
    title: "Cross-Domain Analogy Finder",
    body: "You are a research assistant skilled at finding illuminating analogies across domains.\nThe concept or situation I'm trying to understand: {{topic}}.\nAudience I need to explain this to: {{audience}}.\nFind 3 analogies from different, well-known domains (e.g., biology, everyday life, another industry) that each illuminate a different aspect of {{topic}}.\nFor each analogy, explain precisely which part of the concept it maps to and where the analogy breaks down so it isn't taken too literally.\nOutput as a list of analogies, each with: The Analogy, What It Illuminates, and Where It Breaks Down, tailored in complexity to {{audience}}.",
    variables: ["topic", "audience"],
    complexity: "Beginner",
  },
  {
    category: "Research Prompt",
    title: "Research Question Refinement Assistant",
    body: "You are a research methodology advisor helping me refine a vague research question into something answerable.\nMy initial question: {{initial_question}}.\nWhat I ultimately want to be able to do with the answer: {{intended_application}}.\nDiagnose what makes the initial question too broad, ambiguous, or unanswerable as stated, then propose 3 refined versions that are each specific, scoped, and empirically answerable, ranging from narrow/quick-to-answer to broader/more resource-intensive.\nFor each refined version, note what kind of evidence or research method would actually answer it.\nOutput as: Diagnosis of the Original Question, then the 3 Refined Questions each with its suited research method.",
    variables: ["initial_question", "intended_application"],
    complexity: "Beginner",
  },
  {
    category: "Research Prompt",
    title: "Multi-Perspective Literature Gap Map",
    body: "You are a research analyst mapping where the literature or existing knowledge on {{topic}} has gaps.\nWhat's already well-established, as far as I know: {{established_knowledge}}.\nWhy this gap analysis matters right now: {{motivation}}.\nIdentify categories of open questions: areas with contradictory findings across sources, areas that are under-studied relative to their apparent importance, and areas where most existing work shares a common blind spot or unexamined assumption.\nFor each gap identified, suggest what kind of study or research approach would be best suited to closing it.\nOutput as a gap map table (Gap Category, Description, Why It Matters, Suggested Research Approach).",
    variables: ["topic", "established_knowledge", "motivation"],
    complexity: "Advanced",
  },
  {
    category: "Research Prompt",
    title: "Assumption Surfacing and Stress Test",
    body: "You are a critical thinking coach helping me surface and stress-test the hidden assumptions behind a claim about {{topic}}.\nThe claim as I currently understand it: {{claim_statement}}.\nWhy I need to be confident in this claim: {{stakes_context}}.\nList the assumptions the claim implicitly depends on, ranked by how load-bearing each one is (i.e., how much the conclusion collapses if that assumption is false).\nFor the top 2-3 most load-bearing assumptions, suggest a quick way I could actually test or verify each one.\nOutput as a ranked list of assumptions with a one-line verification method for each, followed by an overall confidence assessment of the claim given how many assumptions remain unverified.",
    variables: ["topic", "claim_statement", "stakes_context"],
    complexity: "Intermediate",
  },
  {
    category: "Research Prompt",
    title: "Research Plan and Methodology Outline",
    body: "You are a research methodology consultant helping me plan an investigation into {{topic}}.\nResources available to me: {{available_resources}}.\nTimeline I'm working within: {{timeline}}.\nPropose a research plan including the key questions to investigate in priority order, the most appropriate methods given my available resources (e.g., desk research, interviews, surveys, experiments), a realistic sequencing of activities across the stated timeline, and how I'll know when I have 'enough' evidence to stop and act.\nFlag any part of the plan that's likely to be a bottleneck given the resources described.\nOutput as a phased research plan with milestones and a brief risk note per phase.",
    variables: ["topic", "available_resources", "timeline"],
    complexity: "Intermediate",
  },
  {
    category: "Research Prompt",
    title: "Contrarian Data Point Hunter",
    body: "You are a research analyst specifically hunting for data points that contradict the prevailing narrative on {{topic}}.\nThe prevailing narrative as I understand it: {{prevailing_narrative}}.\nWhy it's worth stress-testing this narrative: {{motivation}}.\nSearch your reasoning for credible contrarian evidence, minority findings, or dissenting expert views that push back on the prevailing narrative, being clear about how strong or fringe each piece of contrarian evidence actually is.\nAvoid manufacturing false balance: if the contrarian evidence is genuinely weak, say so plainly rather than presenting it as equally credible.\nOutput as a list of contrarian points, each with a strength rating (Strong/Moderate/Weak) and a one-line explanation of why it matters for {{motivation}}.",
    variables: ["topic", "prevailing_narrative", "motivation"],
    complexity: "Advanced",
  },
];
