import type { SeedPrompt } from "./prompt-data";

export const seedPromptsProjectPlanning: SeedPrompt[] = [
  {
    category: "Project Planning",
    title: "Complete Software Development Plan Generator",
    body: "You are a principal technical program manager building a complete, ready-to-execute development plan for a new project.\nProject description and goals: {{project_description}}.\nTeam size and roles available: {{team_composition}}.\nTarget timeline or deadline: {{target_timeline}}.\nKnown technical constraints (existing systems, required stack, compliance): {{constraints}}.\nProduce a full development plan covering: (1) a phase breakdown from discovery through launch and post-launch stabilization, with rough duration per phase, (2) a recommended tech stack and architecture approach with a one-line justification for each major choice given the constraints, (3) a milestone list with concrete, demoable deliverables (not vague checkpoints), (4) a risk register of the 5 most likely risks with mitigation for each, (5) a staffing plan mapping the given team to phases and flagging any skill gaps, and (6) a test/QA and rollout strategy appropriate for the timeline.\nOutput as a structured plan document with clear headings, and end with the single biggest assumption this plan depends on that should be validated first.",
    variables: ["project_description", "team_composition", "target_timeline", "constraints"],
    complexity: "Advanced",
  },
  {
    category: "Project Planning",
    title: "Project Charter Writer",
    body: "You are a project manager drafting a project charter to formally kick off a new initiative.\nProject name and one-line purpose: {{project_purpose}}.\nSponsor and key stakeholders: {{stakeholders}}.\nHigh-level scope and explicit out-of-scope items: {{scope_and_exclusions}}.\nSuccess criteria the sponsor cares about: {{success_criteria}}.\nWrite a project charter covering: purpose and business case, scope (in and explicitly out), success criteria tied to measurable outcomes, key stakeholders and their roles, high-level timeline, and known constraints or assumptions.\nKeep it to one page's worth of content — charters that sprawl don't get read. Flag any success criterion that's currently unmeasurable as written and suggest a measurable rephrasing.",
    variables: ["project_purpose", "stakeholders", "scope_and_exclusions", "success_criteria"],
    complexity: "Beginner",
  },
  {
    category: "Project Planning",
    title: "Work Breakdown Structure (WBS) Builder",
    body: "You are a project planner decomposing a project into a work breakdown structure.\nProject scope: {{project_scope}}.\nMajor deliverables already identified, if any: {{known_deliverables}}.\nTeam structure (functional teams or individuals): {{team_structure}}.\nBreak the scope into a hierarchical WBS: top-level deliverables, then work packages under each small enough to estimate and assign to one owner (roughly 1-5 days of effort each).\nFor each work package, note the owning team/role and any work package it depends on.\nFlag any part of the stated scope that doesn't cleanly decompose yet — that's usually a sign the scope itself is still ambiguous — and suggest the clarifying question to ask before finalizing that branch.",
    variables: ["project_scope", "known_deliverables", "team_structure"],
    complexity: "Intermediate",
  },
  {
    category: "Project Planning",
    title: "Project Scope Statement Writer",
    body: "You are a business analyst writing a formal scope statement to prevent scope creep later.\nProject objective: {{project_objective}}.\nRequested features or work items so far: {{requested_items}}.\nBudget or resource ceiling: {{resource_ceiling}}.\nWrite a scope statement with three sections: In Scope (specific, testable statements — not vague goals), Out of Scope (explicitly named items likely to be assumed included but aren't), and Assumptions/Constraints this scope depends on.\nFor each requested item, classify it as in-scope, out-of-scope, or \"needs a decision\" and explain why for the ambiguous ones.\nEnd with a one-paragraph change-control note: how scope changes should be requested and approved once this is signed off.",
    variables: ["project_objective", "requested_items", "resource_ceiling"],
    complexity: "Intermediate",
  },
  {
    category: "Project Planning",
    title: "Sprint Planning Assistant",
    body: "You are an agile coach helping a team plan their upcoming sprint.\nSprint length and team capacity (person-days or story points): {{sprint_capacity}}.\nCandidate backlog items with rough sizes: {{backlog_items}}.\nCarryover or in-progress work from last sprint: {{carryover_work}}.\nPropose a sprint plan that fits within capacity, prioritizing carryover completion first, then highest-value backlog items, and explain the tradeoff for any item you leave out.\nFlag any item whose size looks too large for a single sprint and suggest how to split it.\nEnd with a one-sentence sprint goal that ties the selected work together into a coherent outcome, not just a list of tickets.",
    variables: ["sprint_capacity", "backlog_items", "carryover_work"],
    complexity: "Beginner",
  },
  {
    category: "Project Planning",
    title: "Product Roadmap Builder",
    body: "You are a product manager building a quarter-by-quarter roadmap.\nProduct vision or north star: {{product_vision}}.\nCandidate initiatives under consideration: {{candidate_initiatives}}.\nKnown constraints (team size, committed deadlines, dependencies on other teams): {{constraints}}.\nGroup the candidate initiatives into a roadmap across the next 2-3 quarters, sequencing by dependency and value rather than just importance, and explicitly note initiatives you're deliberately deferring and why.\nFor each quarter, state the theme in one sentence (what capability or outcome it unlocks) rather than just listing features.\nEnd with the two riskiest sequencing assumptions in this roadmap and what would force a re-prioritization.",
    variables: ["product_vision", "candidate_initiatives", "constraints"],
    complexity: "Intermediate",
  },
  {
    category: "Project Planning",
    title: "Risk Register and Mitigation Planner",
    body: "You are a project risk manager building a risk register.\nProject description: {{project_description}}.\nKnown pain points or past issues on similar projects: {{known_pain_points}}.\nTeam and stakeholder context: {{team_context}}.\nIdentify 8-10 realistic risks across categories (technical, resourcing, scope, external/vendor, stakeholder), and for each: rate likelihood and impact (High/Medium/Low), write a specific mitigation action (not \"monitor closely\"), and name an owner role responsible for watching it.\nRank the top 3 risks that most threaten the timeline specifically, and for those three, add a concrete trigger condition that means the mitigation needs to activate.\nOutput as a table: Risk, Likelihood, Impact, Mitigation, Owner.",
    variables: ["project_description", "known_pain_points", "team_context"],
    complexity: "Intermediate",
  },
  {
    category: "Project Planning",
    title: "RACI Matrix Builder",
    body: "You are an operations lead clarifying decision rights across a project team.\nProject or process being mapped: {{project_or_process}}.\nKey activities or decisions involved: {{key_activities}}.\nRoles/people involved: {{roles_involved}}.\nBuild a RACI matrix (Responsible, Accountable, Consulted, Informed) mapping each activity to each role, ensuring exactly one Accountable per activity — flag any activity where accountability is genuinely unclear from the given information rather than guessing.\nAfter the matrix, call out any role that's marked Responsible or Accountable on an unreasonable number of items (likely bottleneck) and any activity with no clear owner at all.\nOutput as a table with activities as rows and roles as columns.",
    variables: ["project_or_process", "key_activities", "roles_involved"],
    complexity: "Beginner",
  },
  {
    category: "Project Planning",
    title: "Stakeholder Communication Plan Writer",
    body: "You are a project manager designing a stakeholder communication plan.\nProject and its stakeholder groups: {{stakeholder_groups}}.\nProject duration and key milestones: {{project_milestones}}.\nKnown communication pain points from past projects, if any: {{past_pain_points}}.\nFor each stakeholder group, specify: what they need to know, at what cadence, through what channel (status email, dashboard, meeting), and who owns sending it.\nDifferentiate executive stakeholders (outcome-focused, infrequent, high-level) from working-team stakeholders (detail-focused, frequent).\nFlag any stakeholder group getting no communication plan currently and any redundant communication that could be consolidated.",
    variables: ["stakeholder_groups", "project_milestones", "past_pain_points"],
    complexity: "Beginner",
  },
  {
    category: "Project Planning",
    title: "Resource Allocation Planner",
    body: "You are a resource manager allocating people across concurrent project work.\nAvailable team members and their skills/capacity: {{team_availability}}.\nProject workstreams needing staffing: {{workstreams}}.\nHard constraints (PTO, partial allocations, required skills per workstream): {{constraints}}.\nPropose an allocation of people to workstreams that respects the constraints and avoids over-allocating anyone above 100% capacity across their concurrent commitments.\nFor each workstream, flag if it's understaffed relative to its scope, and for each person, show their total allocation percentage across all workstreams they're assigned to.\nEnd with the single most fragile allocation (the one where losing that person would hurt most) and a suggested contingency.",
    variables: ["team_availability", "workstreams", "constraints"],
    complexity: "Intermediate",
  },
  {
    category: "Project Planning",
    title: "Project Timeline and Milestone Estimator",
    body: "You are a delivery lead building a realistic project timeline.\nWork breakdown or major tasks: {{work_items}}.\nTeam capacity (people and hours/week available): {{team_capacity}}.\nHard external deadlines, if any: {{hard_deadlines}}.\nEstimate duration for each major task given the stated capacity, sequence them accounting for dependencies, and build a milestone timeline with dates.\nAdd a buffer appropriate to the project's uncertainty level and explain why you chose that buffer size rather than an arbitrary percentage.\nIf any hard deadline is at risk given the estimates, say so explicitly and propose the two most viable options to address it (cut scope, add capacity, or move the deadline) rather than silently presenting an optimistic timeline.",
    variables: ["work_items", "team_capacity", "hard_deadlines"],
    complexity: "Intermediate",
  },
  {
    category: "Project Planning",
    title: "Project Kickoff Meeting Agenda Builder",
    body: "You are a project manager preparing the kickoff meeting for a new project.\nProject overview: {{project_overview}}.\nAttendees and their roles: {{attendees}}.\nMeeting length available: {{meeting_length}}.\nBuild a kickoff agenda that covers project purpose and success criteria, roles and RACI at a high level, timeline and key milestones, working norms (meeting cadence, communication channels, decision-making process), and open questions to resolve live rather than leaving them unspoken.\nAllocate time per section that fits the stated meeting length, and flag which section is most likely to run over and how to timebox it.\nEnd with 3 concrete discussion questions to ask attendees live to surface concerns early rather than after the meeting.",
    variables: ["project_overview", "attendees", "meeting_length"],
    complexity: "Beginner",
  },
  {
    category: "Project Planning",
    title: "Sprint Retrospective Facilitator Guide",
    body: "You are a scrum master preparing to facilitate a sprint retrospective.\nWhat happened this sprint (wins, misses, incidents): {{sprint_summary}}.\nTeam mood or known tensions, if any: {{team_context}}.\nRetro format preference, if any: {{format_preference}}.\nDesign a retrospective agenda (format, timing, prompts) suited to the team's current mood — a rough sprint needs a format that surfaces root causes safely, a smooth sprint can move faster toward forward-looking improvements.\nProvide 4-5 specific discussion prompts tailored to what actually happened this sprint, not generic \"what went well/poorly\" questions.\nEnd with guidance on how to convert discussion into 2-3 concrete, owned action items rather than a diffuse list of complaints.",
    variables: ["sprint_summary", "team_context", "format_preference"],
    complexity: "Beginner",
  },
  {
    category: "Project Planning",
    title: "Change Request Impact Assessment",
    body: "You are a project manager assessing a scope change request mid-project.\nOriginal scope/plan: {{original_scope}}.\nRequested change: {{requested_change}}.\nCurrent project status (progress, budget spent, timeline remaining): {{current_status}}.\nAssess the change's impact on scope, timeline, budget, and risk, being explicit about what would have to be cut, delayed, or added to resource if this change is accepted as-is.\nRecommend one of: accept as-is, accept with a specific tradeoff, defer to a later phase, or reject — with reasoning tied to the current status, not just the change's merits in isolation.\nOutput as a short impact-assessment memo suitable to send to the requesting stakeholder for a decision.",
    variables: ["original_scope", "requested_change", "current_status"],
    complexity: "Intermediate",
  },
  {
    category: "Project Planning",
    title: "Dependency Mapping and Critical Path Analyzer",
    body: "You are a program manager mapping cross-team dependencies for a complex project.\nWorkstreams and their owning teams: {{workstreams}}.\nKnown dependencies between them: {{known_dependencies}}.\nProject deadline: {{deadline}}.\nMap the dependency graph, identify the critical path (the sequence of dependent tasks that determines the minimum project duration), and flag any dependency that isn't yet firmly committed by the owning team as a risk to that path.\nIdentify which single workstream, if delayed by one week, would most damage the overall timeline, and suggest one way to reduce that fragility (parallelization, buffer, or scope adjustment).\nOutput the critical path as an ordered list with expected dates.",
    variables: ["workstreams", "known_dependencies", "deadline"],
    complexity: "Advanced",
  },
  {
    category: "Project Planning",
    title: "Project Budget Estimator",
    body: "You are a project controller building a budget estimate.\nProject scope and major cost drivers (people, tools, infrastructure, vendors): {{cost_drivers}}.\nTeam composition and approximate rates or salary bands: {{team_costs}}.\nProject duration: {{project_duration}}.\nBuild a budget estimate broken down by category (labor, tooling/licenses, infrastructure, contingency), showing the calculation logic for labor cost from team composition and duration.\nInclude a contingency percentage appropriate to how well-defined the scope is, and explain why you chose that percentage.\nFlag the single cost driver with the widest uncertainty range and suggest what information would tighten that estimate.",
    variables: ["cost_drivers", "team_costs", "project_duration"],
    complexity: "Intermediate",
  },
  {
    category: "Project Planning",
    title: "Project Tooling and Vendor Comparison",
    body: "You are a project operations lead choosing a tool or vendor to support a project (project management software, a specialized vendor, an outsourced service).\nNeed or problem to solve: {{need_description}}.\nCandidate options being considered: {{candidate_options}}.\nBudget and must-have requirements: {{requirements}}.\nCompare the candidate options against the stated requirements, weighing cost, capability fit, integration effort, and switching risk if this choice needs to be reversed later.\nRecommend one option with clear reasoning, avoiding the most expensive/full-featured option unless the stated requirements genuinely need it.\nEnd with the one condition under which you'd revisit this recommendation.",
    variables: ["need_description", "candidate_options", "requirements"],
    complexity: "Intermediate",
  },
  {
    category: "Project Planning",
    title: "Project Status Report Writer",
    body: "You are a project manager writing a status report for stakeholders.\nThis period's progress and completed milestones: {{progress_summary}}.\nCurrent risks or blockers: {{risks_and_blockers}}.\nUpcoming milestones and any timeline/budget changes: {{upcoming_and_changes}}.\nWrite a status report using a RAG (Red/Amber/Green) overall status with justification, a concise progress summary in outcomes rather than activity (\"X shipped\" not \"X worked on tickets\"), risks/blockers with what's being done about each, and what's coming next.\nKeep it skimmable in under 90 seconds of reading — use short sections and bullets, not paragraphs.\nIf overall status is anything other than Green, make sure the justification is specific enough that a reader understands exactly what's at risk and why, not just a vague caution.",
    variables: ["progress_summary", "risks_and_blockers", "upcoming_and_changes"],
    complexity: "Beginner",
  },
  {
    category: "Project Planning",
    title: "Post-Project Retrospective and Post-Mortem Writer",
    body: "You are a project manager writing a post-project retrospective after delivery.\nProject outcome (delivered on time/budget/scope or not, and how): {{project_outcome}}.\nKey events, decisions, or incidents worth examining: {{key_events}}.\nTeam feedback gathered, if any: {{team_feedback}}.\nWrite a blameless post-mortem covering: what happened versus what was planned, root causes (not just proximate causes — ask \"why\" at least twice) for the biggest deviations, what worked well and should be repeated, and 3-5 specific, actionable process changes for future projects.\nAvoid vague lessons like \"communicate better\" — tie each lesson to the specific event that surfaced it and a concrete mechanism to change (a new checklist item, a changed cadence, a new role).\nOutput as a shareable document with clear headings.",
    variables: ["project_outcome", "key_events", "team_feedback"],
    complexity: "Intermediate",
  },
  {
    category: "Project Planning",
    title: "Project Documentation Standard Writer",
    body: "You are setting up a documentation standard so every project run by your team is planned and tracked consistently.\nTeam or department: {{team_name}}.\nTypes of projects this needs to cover: {{project_types}}.\nExisting tools already in use (PM software, wikis): {{existing_tools}}.\nDocument a project documentation standard covering: what artifacts every project must produce (charter, plan, status reports, retro) and at what stage, a naming/location convention so documents are findable, a minimum-viable template for each artifact type, and who's responsible for keeping each artifact current.\nOutput as a reference doc a new project manager on the team could follow without additional explanation, and flag any existing tool gap this standard assumes is filled.",
    variables: ["team_name", "project_types", "existing_tools"],
    complexity: "Intermediate",
  },
  {
    category: "Project Planning",
    title: "Project Plan Feasibility and Quality Review",
    body: "You are a portfolio manager reviewing a project plan before it's approved to proceed.\nProject plan summary (scope, timeline, budget, team): {{plan_summary}}.\nOrganizational constraints it must fit within (other commitments, standard processes): {{org_constraints}}.\nReview the plan for common feasibility gaps: unrealistic timeline given the team size, missing risk coverage for obvious failure modes, scope that doesn't match the stated budget/team, and success criteria that are vague or unmeasurable.\nFor each issue found, explain the specific evidence in the plan that reveals it and what a stronger version would look like.\nEnd with a go/no-go/go-with-changes recommendation and, if not a clean go, the single change that would most improve this plan's odds of success.",
    variables: ["plan_summary", "org_constraints"],
    complexity: "Advanced",
  },
  {
    category: "Project Planning",
    title: "Agile vs. Waterfall Methodology Recommendation",
    body: "You are a delivery methodology advisor helping a team choose how to run a project.\nProject characteristics (requirements stability, stakeholder involvement style, regulatory needs): {{project_characteristics}}.\nTeam's prior experience with each methodology: {{team_experience}}.\nOrganizational or contractual constraints, if any: {{constraints}}.\nCompare Agile (iterative/Scrum-style) and Waterfall (or a hybrid) for this specific project, weighing requirements stability, how the team's experience affects execution risk under each, and any constraint that forces one approach (fixed-price contracts and heavy regulatory sign-off tend to push toward more Waterfall-like gating, for example).\nRecommend one approach or a specific hybrid, with the reasoning tied to this project's actual characteristics rather than generic methodology preferences.\nEnd with the single biggest risk of the chosen approach and how to mitigate it.",
    variables: ["project_characteristics", "team_experience", "constraints"],
    complexity: "Intermediate",
  },
  {
    category: "Project Planning",
    title: "Definition of Done Writer",
    body: "You are a scrum master helping a team write a clear Definition of Done.\nTeam and type of work (feature development, bug fixes, infrastructure): {{work_type}}.\nCurrent quality issues or disputes about \"done,\" if any: {{current_issues}}.\nTools/process already in place (CI, code review, QA): {{existing_process}}.\nWrite a Definition of Done as a checklist covering code quality (review, tests passing), functional verification (acceptance criteria met, tested in the right environment), documentation, and any deployment/release criteria relevant to this team's process.\nTailor it to address the specific current issues mentioned rather than being generic — if disputes are about untested edge cases, the DoD should explicitly close that gap.\nKeep it to a single checklist a team member could verify against without ambiguity in any line item.",
    variables: ["work_type", "current_issues", "existing_process"],
    complexity: "Beginner",
  },
  {
    category: "Project Planning",
    title: "Backlog Grooming and Prioritization Assistant",
    body: "You are a product owner grooming and prioritizing a backlog before sprint planning.\nBacklog items with rough descriptions: {{backlog_items}}.\nPrioritization criteria that matter most right now (revenue impact, technical debt, customer requests, strategic bets): {{prioritization_criteria}}.\nTeam capacity for the upcoming period: {{team_capacity}}.\nScore and rank the backlog items against the stated criteria, flag any item that's too vague to be actionable and needs refinement before it can be estimated, and identify duplicate or overlapping items that should be merged.\nPropose a prioritized order for the next planning cycle that respects capacity, and explicitly name the highest-scored item you're still deferring and why (usually a dependency or a refinement gap).\nOutput as a ranked table: Item, Score/Rationale, Ready for Sprint (Y/N).",
    variables: ["backlog_items", "prioritization_criteria", "team_capacity"],
    complexity: "Intermediate",
  },
  {
    category: "Project Planning",
    title: "Cross-Functional Team Onboarding Plan for New Project",
    body: "You are a project lead onboarding a cross-functional team onto a new project.\nProject overview: {{project_overview}}.\nTeam composition (roles and how many are new to this domain/codebase): {{team_composition}}.\nTimeline before the team needs to be fully productive: {{ramp_timeline}}.\nBuild an onboarding plan covering: what context each role needs first (a backend engineer and a designer don't need the same onboarding), a suggested first small task per role to build familiarity without derailing the timeline, key people to introduce them to and why, and documentation/access they'll need set up before day one.\nSequence the plan across the available ramp timeline rather than front-loading everything on day one.\nFlag the biggest onboarding risk given how many team members are new to the domain, and one mitigation for it.",
    variables: ["project_overview", "team_composition", "ramp_timeline"],
    complexity: "Beginner",
  },
];
