import type { SeedPrompt } from "./prompt-data";

export const seedPromptsBatchD: SeedPrompt[] = [
  // ===================== Finance =====================
  {
    category: "Finance",
    title: "Financial Policy Documentation Drafter",
    body: "You are a finance operations lead drafting a formal financial policy document.\nPolicy area: {{policy_area}}.\nDepartment or team it applies to: {{applicable_department}}.\nKey rules or limits that must be enforced: {{key_rules}}.\nWrite a complete policy document with sections: Purpose, Scope, Policy Statement, Roles & Responsibilities, Approval Thresholds/Exceptions, and Revision History.\nUse precise, unambiguous language appropriate for an internal finance manual, and call out any rule that requires a named approver or escalation path.\nEnd with a short FAQ of 3 likely employee questions and their answers.",
    variables: ["policy_area", "applicable_department", "key_rules"],
    complexity: "Beginner",
  },
  {
    category: "Finance",
    title: "Audit Trail Documentation Builder",
    body: "You are a finance controller responsible for audit readiness.\nProcess being audited: {{process_name}}.\nSystems or tools involved: {{systems_involved}}.\nCompliance framework or standard I need to satisfy: {{compliance_standard}}.\nProduce audit trail documentation describing what evidence must be captured at each process step (who performed the action, timestamp, approval, supporting document), where it is stored, and how an auditor would trace a transaction end to end.\nInclude a gap-check section flagging steps where evidence capture is currently weak or manual.\nFormat as a numbered process map followed by an 'Evidence Checklist' table with columns: Step, Evidence Required, Storage Location, Owner.",
    variables: ["process_name", "systems_involved", "compliance_standard"],
    complexity: "Intermediate",
  },
  {
    category: "Finance",
    title: "Finance Process SOP Writer",
    body: "You are a finance process improvement specialist writing a standard operating procedure.\nProcess name: {{process_name}}.\nTeam that will follow this SOP: {{owning_team}}.\nCurrent pain points I want the SOP to resolve: {{pain_points}}.\nWrite a step-by-step SOP with numbered steps, decision points clearly marked, required inputs/outputs at each step, and named responsible roles.\nInclude a 'Common Errors and Fixes' section addressing the pain points I listed.\nEnd with a short version history block and a note on how often this SOP should be reviewed.",
    variables: ["process_name", "owning_team", "pain_points"],
    complexity: "Intermediate",
  },
  {
    category: "Finance",
    title: "Financial Model Error Audit",
    body: "You are a senior FP&A analyst conducting a rigorous quality audit of a financial model.\nModel purpose: {{model_purpose}}.\nHere is a description or excerpt of the model structure and formulas: {{model_structure}}.\nKnown or suspected issue areas: {{suspected_issues}}.\nAudit the model for circular references, hardcoded values mixed with formulas, inconsistent time-period alignment, unit mismatches, and broken linkages between sheets.\nFor each issue you identify or suspect based on the description, explain the risk it poses to output accuracy and give a concrete fix.\nOutput as a severity-ranked table with columns: Issue, Location, Risk, Recommended Fix, followed by a short note on how to build in error-checking cells going forward.",
    variables: ["model_purpose", "model_structure", "suspected_issues"],
    complexity: "Advanced",
  },
  {
    category: "Finance",
    title: "Assumption Sensitivity Review",
    body: "You are a financial planning analyst stress-testing a forecast's key assumptions.\nForecast or model context: {{forecast_context}}.\nKey assumptions driving the output: {{key_assumptions}}.\nBusiness decision this forecast supports: {{business_decision}}.\nFor each assumption, estimate how sensitive the final output is to a reasonable plus/minus swing, rank assumptions from highest to lowest impact, and identify which ones deserve a full sensitivity or scenario analysis before the decision is made.\nFlag any assumption that is more of a guess than a data-backed estimate and suggest how to firm it up.\nPresent results as a ranked table (Assumption, Plausible Range, Impact on Output, Confidence Level) followed by a recommendation on which 2-3 scenarios to model explicitly.",
    variables: ["forecast_context", "key_assumptions", "business_decision"],
    complexity: "Advanced",
  },
  {
    category: "Finance",
    title: "Reconciliation Quality Checker",
    body: "You are a finance controls specialist reviewing the rigor of a reconciliation process.\nAccounts or ledgers being reconciled: {{accounts_reconciled}}.\nCurrent reconciliation method: {{current_method}}.\nTypical discrepancy size or frequency observed: {{discrepancy_pattern}}.\nEvaluate whether the current method would reliably catch timing differences, duplicate entries, currency conversion errors, and unauthorized adjustments.\nIdentify weaknesses in the current approach and propose specific control improvements (e.g., tolerance thresholds, automated matching rules, segregation of duties).\nOutput as: Current Method Assessment, Weaknesses Found, Recommended Controls (numbered), and a suggested cadence for reviewing reconciliation quality itself.",
    variables: ["accounts_reconciled", "current_method", "discrepancy_pattern"],
    complexity: "Intermediate",
  },
  {
    category: "Finance",
    title: "Financing Options Comparison and Recommendation",
    body: "You are a corporate finance advisor helping me choose a financing option.\nFunding need and amount: {{funding_need}}.\nCandidate financing options to evaluate: {{financing_options}}.\nConstraints such as timeline, risk tolerance, or covenant sensitivity: {{constraints}}.\nResearch and compare the candidate options on cost of capital, repayment structure, dilution or control impact, speed to close, and covenant/collateral requirements.\nBuild a side-by-side comparison, then recommend the single best option given my constraints, explicitly justifying the trade-offs you accepted to get there.\nOutput as a comparison table followed by a 'Recommendation and Rationale' section and a short list of risks to monitor after choosing this option.",
    variables: ["funding_need", "financing_options", "constraints"],
    complexity: "Advanced",
  },
  {
    category: "Finance",
    title: "Investment Options Comparison and Recommendation",
    body: "You are an investment analyst helping me decide where to allocate capital.\nAmount and horizon for this decision: {{investment_amount_horizon}}.\nCandidate investment options: {{investment_options}}.\nMy risk appetite and strategic priorities: {{risk_priorities}}.\nResearch each option's expected return profile, risk factors, liquidity, and strategic fit, then compare them side by side.\nRecommend the option (or blend) that best matches my stated risk appetite and priorities, explaining the trade-offs of the paths not chosen.\nFormat as a comparison table (Option, Expected Return, Risk, Liquidity, Strategic Fit) followed by a clear recommendation paragraph and 2-3 conditions under which I should revisit the decision.",
    variables: ["investment_amount_horizon", "investment_options", "risk_priorities"],
    complexity: "Advanced",
  },
  {
    category: "Finance",
    title: "Vendor Payment Terms Negotiator Brief",
    body: "You are a procurement finance advisor preparing me to negotiate payment terms.\nVendor name and relationship history: {{vendor_context}}.\nCurrent payment terms: {{current_terms}}.\nWhat I'm trying to achieve (e.g., extended terms, early-pay discount): {{negotiation_goal}}.\nDraft talking points that frame the ask in terms of mutual benefit, anticipate 2-3 objections the vendor might raise, and provide a fallback position if my primary ask is rejected.\nInclude a short calculation of the cash-flow or discount impact of the proposed change.\nOutput as: Opening Position, Supporting Rationale, Anticipated Objections & Responses, Fallback Position.",
    variables: ["vendor_context", "current_terms", "negotiation_goal"],
    complexity: "Intermediate",
  },
  {
    category: "Finance",
    title: "Working Capital Optimization Plan",
    body: "You are a treasury and working capital consultant.\nCurrent working capital position: {{current_position}}.\nKey drivers (e.g., DSO, DPO, inventory days): {{key_drivers}}.\nBusiness constraints I must respect (e.g., customer relationships, supplier reliability): {{constraints}}.\nPropose a working capital optimization plan targeting each key driver, with specific levers (collections process changes, payment term renegotiation, inventory policy) and an estimate of the cash impact of each lever.\nSequence the levers by ease of implementation versus impact.\nOutput as a prioritized action table (Lever, Driver Affected, Estimated Cash Impact, Implementation Effort) followed by a 90-day rollout outline.",
    variables: ["current_position", "key_drivers", "constraints"],
    complexity: "Intermediate",
  },
  {
    category: "Finance",
    title: "Budget Proposal Justification Writer",
    body: "You are a finance business partner helping a department justify a budget request.\nDepartment: {{department_name}}.\nAmount requested and purpose: {{budget_request}}.\nExpected business outcome or ROI: {{expected_outcome}}.\nWrite a budget justification memo that connects the requested spend directly to the expected outcome, anticipates the most likely pushback from finance leadership, and proposes a fallback reduced-scope option.\nKeep the tone confident but grounded in numbers rather than aspiration.\nStructure as: Request Summary, Business Case, Expected ROI/Outcome, Risks of Not Funding, Reduced-Scope Alternative.",
    variables: ["department_name", "budget_request", "expected_outcome"],
    complexity: "Beginner",
  },
  {
    category: "Finance",
    title: "Cost Reduction Opportunity Finder",
    body: "You are a cost optimization consultant reviewing a spend category.\nSpend category or department: {{spend_category}}.\nCurrent annual spend: {{current_spend}}.\nConstraints I must preserve (e.g., service quality, headcount): {{constraints}}.\nIdentify 5-8 realistic cost reduction opportunities in this category, categorizing each as quick win, medium-term, or structural change, and estimate potential savings range for each.\nFlag any opportunity that carries meaningful risk to the constraints I listed.\nOutput as a table with columns: Opportunity, Category, Estimated Savings Range, Risk to Constraints, followed by a recommended sequencing for pursuing them.",
    variables: ["spend_category", "current_spend", "constraints"],
    complexity: "Intermediate",
  },
  {
    category: "Finance",
    title: "Financial Ratio Interpretation Coach",
    body: "You are a finance educator helping me interpret a company's financial ratios in plain language.\nCompany or business context: {{company_context}}.\nRatios and values I have: {{ratio_values}}.\nAudience I need to explain this to: {{audience}}.\nExplain what each ratio means, whether the value is generally healthy or concerning for this type of business, and what follow-up question a sharp reviewer would ask next.\nAvoid jargon where possible and translate technical terms into plain-language equivalents suited to the audience.\nOutput as a table (Ratio, Value, Plain-Language Meaning, Health Signal, Follow-up Question) followed by a 2-sentence overall takeaway.",
    variables: ["company_context", "ratio_values", "audience"],
    complexity: "Beginner",
  },
  {
    category: "Finance",
    title: "Month-End Close Checklist Builder",
    body: "You are a controller building a month-end close checklist for the team.\nEntities or business units in scope: {{entities_in_scope}}.\nCurrent close duration and pain points: {{close_pain_points}}.\nSystems used for close (ERP, spreadsheets, etc.): {{systems_used}}.\nBuild a day-by-day close checklist from day 1 through final sign-off, grouping tasks by owner (AP, AR, GL, FP&A) and marking dependencies between tasks.\nAddress the stated pain points directly by suggesting where a task can be moved earlier or automated.\nOutput as a table with columns: Day, Task, Owner, Depends On, followed by a short note on the target close-day reduction this should achieve.",
    variables: ["entities_in_scope", "close_pain_points", "systems_used"],
    complexity: "Beginner",
  },
  {
    category: "Finance",
    title: "Tax Compliance Summary Explainer",
    body: "You are a tax advisor summarizing a compliance requirement for a non-tax audience.\nJurisdiction and tax type: {{jurisdiction_tax_type}}.\nBusiness activity that triggers this requirement: {{business_activity}}.\nAudience receiving the summary: {{audience}}.\nExplain in plain language what the requirement is, why it applies to this business activity, key deadlines, and the consequences of missing them.\nInclude a short checklist of information the audience needs to gather before the deadline.\nOutput as: Plain-Language Summary, Why It Applies to Us, Key Dates, Information Checklist, and note clearly that this is not formal tax advice and should be confirmed with a qualified tax professional.",
    variables: ["jurisdiction_tax_type", "business_activity", "audience"],
    complexity: "Intermediate",
  },
  {
    category: "Finance",
    title: "Vendor Contract Renewal Cost Analyzer",
    body: "You are a finance analyst evaluating an upcoming vendor contract renewal.\nVendor and service description: {{vendor_service}}.\nCurrent contract terms and cost: {{current_terms_cost}}.\nProposed renewal terms: {{proposed_terms}}.\nAnalyze the cost trajectory versus the value delivered, flag any unfavorable clauses (auto-renewal, price escalators, termination penalties), and compare against typical market benchmarks if inferable.\nRecommend whether to renew as-is, renegotiate, or explore alternatives, with a clear rationale.\nOutput as: Cost/Value Summary, Clause Risks Identified, Benchmark Comparison, Recommendation with Rationale.",
    variables: ["vendor_service", "current_terms_cost", "proposed_terms"],
    complexity: "Intermediate",
  },
  {
    category: "Finance",
    title: "Capital Expenditure Justification Memo",
    body: "You are a finance business partner drafting a capital expenditure justification memo.\nProposed capital investment: {{capex_description}}.\nEstimated cost and expected useful life: {{cost_and_life}}.\nStrategic or operational driver behind this request: {{strategic_driver}}.\nWrite a memo that lays out the business case, expected payback period or ROI, key risks if the investment is delayed or not made, and alternatives considered (including a 'do nothing' baseline).\nAnticipate the toughest question a CFO would ask and answer it proactively within the memo.\nStructure as: Executive Summary, Business Case, Financial Analysis, Risks & Alternatives Considered, Recommendation.",
    variables: ["capex_description", "cost_and_life", "strategic_driver"],
    complexity: "Advanced",
  },
  {
    category: "Finance",
    title: "Currency Exposure Risk Summary",
    body: "You are a treasury risk analyst summarizing foreign currency exposure for leadership.\nCurrencies and exposure sources (e.g., revenue, payables, intercompany): {{exposure_sources}}.\nApproximate exposure size by currency: {{exposure_size}}.\nCurrent hedging approach, if any: {{current_hedging}}.\nSummarize the net exposure by currency, the potential earnings impact under a plausible adverse move, and whether the current hedging approach is adequate given that exposure.\nRecommend next steps, being clear about the difference between a hedging suggestion and formal treasury policy that would need sign-off.\nOutput as: Exposure Summary Table (Currency, Net Exposure, Potential Impact), Hedging Adequacy Assessment, Recommended Next Steps.",
    variables: ["exposure_sources", "exposure_size", "current_hedging"],
    complexity: "Advanced",
  },

  // ===================== Presentation Skills =====================
  {
    category: "Presentation Skills",
    title: "Presentation Style Guide Documentation",
    body: "You are a presentation design lead documenting a reusable style guide.\nTeam or organization this applies to: {{team_name}}.\nBrand or visual identity constraints: {{brand_constraints}}.\nCommon presentation types this team creates: {{presentation_types}}.\nWrite a style guide document covering slide layout rules, font and color usage, chart formatting conventions, acceptable levels of animation, and a do's-and-don'ts section with concrete examples.\nInclude a short section on how to handle exceptions when a one-off deck needs to break the rules.\nOutput as a structured reference document with numbered sections and a one-page quick-reference summary at the end.",
    variables: ["team_name", "brand_constraints", "presentation_types"],
    complexity: "Beginner",
  },
  {
    category: "Presentation Skills",
    title: "Meeting Debrief Report Template",
    body: "You are a communications lead creating a reusable debrief report template for talks and meetings.\nType of meeting or talk this template covers: {{meeting_type}}.\nWho will read the debrief afterward: {{audience_for_debrief}}.\nInformation that must always be captured: {{required_fields}}.\nBuild a debrief report template with sections for objective, key messages delivered, audience reactions and questions, what landed well, what to improve next time, and follow-up actions with owners.\nMake the template fillable in under 10 minutes right after a session ends.\nOutput as a structured template with placeholder prompts under each heading, ready to be copied for future use.",
    variables: ["meeting_type", "audience_for_debrief", "required_fields"],
    complexity: "Beginner",
  },
  {
    category: "Presentation Skills",
    title: "Training Deck Documentation for Reuse",
    body: "You are an instructional design specialist documenting a training deck so others can reuse and update it confidently.\nTraining topic: {{training_topic}}.\nIntended audience and skill level: {{audience_skill_level}}.\nWho will maintain this deck after me: {{future_owner}}.\nWrite accompanying documentation covering the learning objectives per section, facilitation notes for tricky slides, timing guidance, known audience questions with suggested answers, and instructions for updating the content when it goes stale.\nInclude a changelog section for tracking future edits.\nOutput as a structured 'Facilitator Guide' with sections: Objectives, Slide-by-Slide Notes, Timing, FAQ, Update Instructions, Changelog.",
    variables: ["training_topic", "audience_skill_level", "future_owner"],
    complexity: "Intermediate",
  },
  {
    category: "Presentation Skills",
    title: "Presentation Clarity Critique",
    body: "You are a rigorous presentation coach reviewing a deck for clarity.\nPresentation purpose: {{presentation_purpose}}.\nHere is the slide-by-slide content or outline: {{slide_content}}.\nIntended audience: {{intended_audience}}.\nCritique the deck for unclear messaging, buried key points, jargon unsuited to the audience, and any slide where a reader would need more than 10 seconds to grasp the point.\nFor each issue, quote or reference the specific slide and give a concrete rewrite suggestion.\nOutput as a table with columns: Slide, Clarity Issue, Suggested Fix, followed by an overall clarity score out of 10 and the single biggest change that would improve it.",
    variables: ["presentation_purpose", "slide_content", "intended_audience"],
    complexity: "Intermediate",
  },
  {
    category: "Presentation Skills",
    title: "Slide Density and Cognitive Load Audit",
    body: "You are a presentation design expert auditing cognitive load across a deck.\nDeck topic: {{deck_topic}}.\nSlide-by-slide content or description: {{slide_content}}.\nPresentation setting (e.g., boardroom, conference, virtual): {{presentation_setting}}.\nAudit each slide for text density, number of competing visual elements, and whether the slide asks the audience to read and listen simultaneously in a way that hurts retention.\nFlag slides that should be split into two, simplified, or converted from text to visual, and explain the cognitive-load principle behind each recommendation.\nOutput as a table (Slide, Density Issue, Cognitive Load Principle Violated, Recommended Fix) followed by a summary of the top 3 highest-priority fixes.",
    variables: ["deck_topic", "slide_content", "presentation_setting"],
    complexity: "Intermediate",
  },
  {
    category: "Presentation Skills",
    title: "Rehearsal Feedback Simulator",
    body: "You are an executive presentation coach running a simulated rehearsal feedback session.\nPresentation topic and goal: {{presentation_topic}}.\nHere is a rough transcript or description of my delivery: {{delivery_transcript}}.\nAudience I'll be presenting to: {{audience}}.\nAct as if you just watched this rehearsal and give feedback on pacing, filler words, clarity of transitions between points, and whether the opening and closing were strong enough to be memorable.\nThen simulate 3 tough questions this audience is likely to ask and give me a model answer for each.\nOutput as: Delivery Feedback (strengths and fixes), Simulated Q&A with Model Answers, and one specific rehearsal drill to practice before the real presentation.",
    variables: ["presentation_topic", "delivery_transcript", "audience"],
    complexity: "Advanced",
  },
  {
    category: "Presentation Skills",
    title: "Presentation Format Comparison for Audience",
    body: "You are a presentation strategy consultant helping me choose the right format.\nContent I need to present: {{content_description}}.\nAudience characteristics (size, seniority, familiarity with topic): {{audience_characteristics}}.\nConstraints such as time limit or setting: {{constraints}}.\nResearch and compare candidate formats (e.g., traditional slide deck, one-pager plus discussion, live demo, structured narrative, data-first dashboard walkthrough) on engagement fit, information density suited to the audience, and preparation effort.\nRecommend the single best format for this specific audience and constraints, explaining the trade-offs of the formats you ruled out.\nOutput as a comparison table (Format, Engagement Fit, Density Fit, Prep Effort) followed by a clear recommendation and rationale.",
    variables: ["content_description", "audience_characteristics", "constraints"],
    complexity: "Advanced",
  },
  {
    category: "Presentation Skills",
    title: "Presentation Structure Comparison and Recommendation",
    body: "You are a communications strategist comparing narrative structures for an upcoming presentation.\nKey message I need to land: {{key_message}}.\nAudience and their likely starting position (skeptical, supportive, neutral): {{audience_position}}.\nTime available: {{time_available}}.\nResearch and compare at least three structural approaches (e.g., problem-solution-benefit, chronological case-building, inverted-pyramid lead-with-recommendation, comparison-then-verdict) for how well each would land with this audience's starting position.\nRecommend the single best structure, mapping out roughly how the time available should be allocated across its sections.\nOutput as a comparison table (Structure, Fit for Audience Position, Time Allocation Feasibility) followed by a recommended section-by-section outline for the chosen structure.",
    variables: ["key_message", "audience_position", "time_available"],
    complexity: "Advanced",
  },
  {
    category: "Presentation Skills",
    title: "Elevator Pitch Builder",
    body: "You are a communications coach helping me craft a tight elevator pitch.\nWhat I'm pitching: {{pitch_subject}}.\nWho I'll likely be pitching to: {{typical_listener}}.\nTime I realistically have: {{time_limit}}.\nWrite 3 versions of the pitch at roughly 10, 30, and 60 seconds, each hitting the same core value proposition but adjusting depth of detail.\nMake sure each version ends with a natural, low-pressure next-step ask rather than a hard close.\nOutput as three labeled versions with word counts, followed by one tip on adapting tone depending on the listener's reaction.",
    variables: ["pitch_subject", "typical_listener", "time_limit"],
    complexity: "Beginner",
  },
  {
    category: "Presentation Skills",
    title: "Stakeholder Objection Anticipator",
    body: "You are a presentation strategist helping me prepare for a skeptical stakeholder audience.\nProposal or recommendation I'm presenting: {{proposal_summary}}.\nStakeholders likely to push back and their known concerns: {{stakeholder_concerns}}.\nWhat's at stake if the presentation doesn't land: {{stakes}}.\nList the most likely objections from each stakeholder, and for each one draft a calm, evidence-based response I can give in the room without sounding defensive.\nSuggest one slide or data point I should have ready as backup for the toughest objection.\nOutput as a table (Stakeholder, Likely Objection, Suggested Response, Backup Evidence Needed).",
    variables: ["proposal_summary", "stakeholder_concerns", "stakes"],
    complexity: "Intermediate",
  },
  {
    category: "Presentation Skills",
    title: "Visual Metaphor Brainstormer",
    body: "You are a creative presentation consultant helping me find a strong visual metaphor.\nConcept I need to explain: {{concept_to_explain}}.\nAudience's background and familiarity with the topic: {{audience_background}}.\nTone I want to strike (playful, serious, inspiring): {{desired_tone}}.\nBrainstorm 5-6 visual metaphors or analogies that would make this concept instantly click for this audience, briefly explaining how each metaphor maps to the real concept and where it might break down if pushed too far.\nRecommend the single strongest option and sketch in words how I could build one slide around it.\nOutput as a list of metaphors with mapping and limitation notes, followed by a 'Recommended Choice' section.",
    variables: ["concept_to_explain", "audience_background", "desired_tone"],
    complexity: "Beginner",
  },
  {
    category: "Presentation Skills",
    title: "Technical-to-Non-Technical Translator for Slides",
    body: "You are a communication specialist who translates technical content for non-technical audiences.\nTechnical content or finding I need to present: {{technical_content}}.\nAudience's background: {{audience_background}}.\nDecision this presentation needs to support: {{decision_context}}.\nRewrite the technical content into plain-language slide bullets, replacing jargon with everyday analogies while preserving the accuracy of the underlying finding.\nFlag any place where simplification risks meaningfully changing the meaning, and suggest a caveat line to include.\nOutput as: Original Technical Point, Plain-Language Slide Version, Simplification Risk (if any), for each key point.",
    variables: ["technical_content", "audience_background", "decision_context"],
    complexity: "Intermediate",
  },
  {
    category: "Presentation Skills",
    title: "Presentation Timing and Pacing Planner",
    body: "You are a presentation coach helping me plan timing and pacing.\nTotal time allotted: {{total_time}}.\nMain sections or topics I need to cover: {{main_sections}}.\nParts of the content that are highest priority if time runs short: {{priority_content}}.\nAllocate time per section, building in a buffer for questions or tangents, and mark which sections can be compressed or cut if I'm running behind.\nSuggest a verbal time-check cue I can use mid-talk to keep myself on pace without breaking flow.\nOutput as a table (Section, Allocated Time, Compressible If Short on Time) followed by pacing tips.",
    variables: ["total_time", "main_sections", "priority_content"],
    complexity: "Beginner",
  },
  {
    category: "Presentation Skills",
    title: "Cross-Cultural Presentation Adaptation Advisor",
    body: "You are a cross-cultural communications advisor helping me adapt a presentation for an international audience.\nOriginal presentation topic and content: {{presentation_content}}.\nTarget audience's cultural or regional background: {{target_culture}}.\nAspects I'm most unsure about (humor, directness, visuals, examples): {{uncertain_aspects}}.\nReview the content for idioms, humor, or examples that may not translate well, and suggest culturally appropriate substitutions that preserve the original intent.\nFlag any communication norms around directness, hierarchy, or Q&A etiquette I should be aware of for this audience.\nOutput as: Content Adjustments Needed (table: Original, Issue, Suggested Adaptation), followed by a 'Cultural Norms to Respect' section.",
    variables: ["presentation_content", "target_culture", "uncertain_aspects"],
    complexity: "Advanced",
  },
  {
    category: "Presentation Skills",
    title: "Virtual Presentation Engagement Planner",
    body: "You are a virtual event facilitation expert helping me keep a remote audience engaged.\nPresentation topic and duration: {{presentation_topic_duration}}.\nAudience size and platform being used: {{audience_and_platform}}.\nTypical challenges I've had with remote audiences: {{engagement_challenges}}.\nDesign an engagement plan that inserts interaction points (polls, chat prompts, breakout discussion, quick quizzes) at natural moments, directly addressing the challenges I described.\nInclude a contingency plan for low engagement or technical issues mid-session.\nOutput as a timeline table (Time Marker, Content, Engagement Tactic) followed by a short contingency plan section.",
    variables: ["presentation_topic_duration", "audience_and_platform", "engagement_challenges"],
    complexity: "Intermediate",
  },
  {
    category: "Presentation Skills",
    title: "Panel Discussion Talking Points Builder",
    body: "You are a media training coach preparing me for a panel discussion.\nPanel topic and format: {{panel_topic_format}}.\nMy specific expertise or angle on this topic: {{my_expertise}}.\nOther panelists and their likely perspectives: {{other_panelists}}.\nDraft 5-6 concise talking points I can weave into the discussion naturally, each with a memorable one-line version and a slightly longer backup version if given more time.\nSuggest how to pivot back to my key points if the conversation drifts, and one respectful way to disagree with another panelist if needed.\nOutput as a table (Talking Point, Short Version, Extended Version) followed by pivot and disagreement phrasing tips.",
    variables: ["panel_topic_format", "my_expertise", "other_panelists"],
    complexity: "Intermediate",
  },
  {
    category: "Presentation Skills",
    title: "Crisis Communication Presentation Drafter",
    body: "You are a crisis communications advisor helping me prepare an urgent presentation.\nSituation that needs to be communicated: {{crisis_situation}}.\nAudience receiving this news: {{audience}}.\nKey facts confirmed so far versus still unknown: {{known_and_unknown_facts}}.\nDraft a presentation structure that leads with what is known, is transparent about what is still unknown without speculating, states what actions are being taken, and closes with a clear channel for follow-up questions.\nUse a calm, direct tone that avoids corporate euphemism while still being measured and accurate.\nOutput as: Opening Statement, What We Know, What We Don't Know Yet, Actions Being Taken, Closing and Follow-up Channel.",
    variables: ["crisis_situation", "audience", "known_and_unknown_facts"],
    complexity: "Advanced",
  },
  {
    category: "Presentation Skills",
    title: "Presentation Closing and Call-to-Action Builder",
    body: "You are a presentation coach helping me craft a strong closing.\nPresentation topic: {{presentation_topic}}.\nSpecific action I want the audience to take afterward: {{desired_action}}.\nTone I want to end on (urgent, inspiring, reassuring): {{desired_tone}}.\nWrite 3 alternative closing statements that summarize the core message, make the desired action unmistakably clear, and end on the requested tone rather than fizzling out.\nFor each option, include a one-line explanation of when it would work best.\nOutput as three labeled closing statements with a short 'best used when' note for each.",
    variables: ["presentation_topic", "desired_action", "desired_tone"],
    complexity: "Beginner",
  },

  // ===================== Content Generation =====================
  {
    category: "Content Generation",
    title: "Content Style Guide and Governance Documentation",
    body: "You are a content strategy lead documenting a style guide and governance process.\nBrand or publication name: {{brand_name}}.\nContent types this guide must cover: {{content_types}}.\nTone and voice principles already agreed on: {{tone_principles}}.\nWrite a governance document covering voice and tone rules with examples, grammar and formatting conventions, approval workflow for new content, and a review cadence for keeping the guide current.\nInclude a short 'red flags' section listing phrases or patterns that should never be published under this brand.\nOutput as a structured reference document with numbered sections and a one-page quick-reference summary at the end.",
    variables: ["brand_name", "content_types", "tone_principles"],
    complexity: "Intermediate",
  },
  {
    category: "Content Generation",
    title: "SEO Content Brief Documentation",
    body: "You are a content operations lead documenting a reusable SEO content brief template.\nContent types this template will be used for: {{content_types}}.\nSEO tooling or keyword research process the team already uses: {{seo_process}}.\nInformation writers have historically been missing when they start drafts: {{missing_information}}.\nDocument a standardized brief template with fields for target keyword and search intent, audience, required sections, internal linking rules, and a definition-of-done checklist before a draft is considered brief-complete.\nAddress the missing-information gaps directly by making those fields mandatory in the template.\nOutput as a fillable template document with field labels and short instructional notes under each one.",
    variables: ["content_types", "seo_process", "missing_information"],
    complexity: "Intermediate",
  },
  {
    category: "Content Generation",
    title: "Editorial Calendar Documentation",
    body: "You are a content operations manager documenting how the editorial calendar works.\nContent channels covered by the calendar: {{content_channels}}.\nPublishing cadence per channel: {{publishing_cadence}}.\nRoles involved in the content lifecycle (ideation, writing, review, publish): {{roles_involved}}.\nWrite documentation explaining how the calendar is structured, what status labels mean at each stage, who owns handoffs between stages, and how last-minute changes or breaking-news content get slotted in without breaking the schedule.\nInclude a short troubleshooting section for the most common scheduling conflicts.\nOutput as a structured reference document with a lifecycle diagram described in words, a role-responsibility table, and a troubleshooting FAQ.",
    variables: ["content_channels", "publishing_cadence", "roles_involved"],
    complexity: "Beginner",
  },
  {
    category: "Content Generation",
    title: "Content Quality and Readability Audit",
    body: "You are a content quality editor conducting a rigorous readability audit.\nContent to review: {{content_text}}.\nTarget audience and their reading level: {{target_audience}}.\nPurpose of the content (inform, persuade, convert): {{content_purpose}}.\nAudit the content for sentence complexity, jargon unsuited to the audience, passive-voice overuse, unclear transitions, and whether the structure supports skimming.\nFor each issue, quote the problematic passage and provide a rewritten version.\nOutput as a table (Original Passage, Issue, Rewritten Version) followed by an overall readability score out of 10 and the single highest-impact fix.",
    variables: ["content_text", "target_audience", "content_purpose"],
    complexity: "Intermediate",
  },
  {
    category: "Content Generation",
    title: "Plagiarism-Risk and Originality Review",
    body: "You are a content integrity reviewer assessing originality risk.\nContent to review: {{content_text}}.\nKnown source material or competitor content it may resemble: {{known_sources}}.\nPublication context (internal use, public blog, client deliverable): {{publication_context}}.\nReview the content for passages that closely paraphrase common source phrasing, over-reliance on generic boilerplate that reads as templated, and any claims stated as fact that would need citation.\nFlag sections that should be rewritten in a more original voice or that need a citation added before publishing.\nOutput as a table (Passage, Originality Concern, Recommended Action) followed by an overall originality risk rating (Low/Medium/High) and rationale.",
    variables: ["content_text", "known_sources", "publication_context"],
    complexity: "Advanced",
  },
  {
    category: "Content Generation",
    title: "Tone and Brand-Consistency Review",
    body: "You are a brand voice editor reviewing content for tone consistency.\nBrand voice guidelines or description: {{brand_voice}}.\nContent to review: {{content_text}}.\nWhere this content will be published: {{publication_channel}}.\nReview the content line by line for tone drift, inconsistent formality, or word choices that clash with the stated brand voice, and check that the tone is appropriate for the publication channel.\nFor each inconsistency, show the original line, explain the drift, and provide a corrected version that matches brand voice.\nOutput as a table (Original Line, Tone Issue, Corrected Line) followed by an overall brand-consistency score out of 10.",
    variables: ["brand_voice", "content_text", "publication_channel"],
    complexity: "Intermediate",
  },
  {
    category: "Content Generation",
    title: "Content Format Comparison and Channel Recommendation",
    body: "You are a content strategy consultant helping me decide how to package a piece of content.\nCore message or topic: {{core_topic}}.\nTarget audience and where they typically consume content: {{audience_habits}}.\nResources available (time, budget, in-house skills): {{available_resources}}.\nResearch and compare candidate formats (long-form article, short video, carousel, infographic, podcast segment, interactive tool) on audience fit, production effort given my resources, and expected shelf life.\nRecommend the single best format, or a primary-plus-repurposed combination, with clear justification for the trade-offs made.\nOutput as a comparison table (Format, Audience Fit, Production Effort, Shelf Life) followed by a clear recommendation and rationale.",
    variables: ["core_topic", "audience_habits", "available_resources"],
    complexity: "Advanced",
  },
  {
    category: "Content Generation",
    title: "Content Channel Research and Plan Recommendation",
    body: "You are a content distribution strategist building a channel plan.\nContent piece or campaign topic: {{content_topic}}.\nCandidate channels under consideration: {{candidate_channels}}.\nBusiness goal this content plan must support: {{business_goal}}.\nResearch and compare the candidate channels on reach potential for this audience, effort to produce channel-native versions, and how directly each channel supports the stated business goal.\nRecommend a prioritized content plan naming which channels get primary investment versus lightweight repurposing, and justify why the deprioritized channels were set aside.\nOutput as a comparison table (Channel, Reach Potential, Production Effort, Goal Alignment) followed by a prioritized content plan and rationale.",
    variables: ["content_topic", "candidate_channels", "business_goal"],
    complexity: "Advanced",
  },
  {
    category: "Content Generation",
    title: "Social Media Caption Repurposer",
    body: "You are a social media content specialist repurposing existing content into fresh captions.\nSource content to repurpose: {{source_content}}.\nTarget platform: {{target_platform}}.\nCampaign goal for this post: {{campaign_goal}}.\nWrite 4 distinct caption variations from the source content suited to the target platform's norms, each with a different hook style (question, bold statement, relatable observation, quick stat), and suggest 3-5 relevant hashtags per variation.\nKeep each caption within a length appropriate for the platform.\nOutput as four labeled caption variations, each with its hashtag suggestions.",
    variables: ["source_content", "target_platform", "campaign_goal"],
    complexity: "Beginner",
  },
  {
    category: "Content Generation",
    title: "Content Repurposing Plan Across Channels",
    body: "You are a content operations strategist building a repurposing plan.\nOriginal long-form content piece: {{original_content}}.\nChannels I want to repurpose it for: {{target_channels}}.\nTimeline for rolling this out: {{rollout_timeline}}.\nBreak the original content into a repurposing plan showing what sub-asset gets created for each target channel, what needs to be rewritten versus lightly adapted, and a suggested publishing order that maximizes cross-promotion between assets.\nFlag any channel where the original content doesn't translate well and suggest an alternative angle instead.\nOutput as a table (Channel, Asset Type, Adaptation Needed, Suggested Publish Order) followed by a short rollout timeline summary.",
    variables: ["original_content", "target_channels", "rollout_timeline"],
    complexity: "Intermediate",
  },
  {
    category: "Content Generation",
    title: "Listicle Writer",
    body: "You are a content writer specializing in high-engagement listicles.\nTopic: {{topic}}.\nTarget audience: {{target_audience}}.\nDesired number of list items: {{list_length}}.\nWrite a listicle with a compelling title, a short intro hook, and one paragraph per list item that delivers real value rather than filler.\nVary sentence rhythm across items so it doesn't read formulaically, and end with a short closing thought that ties the list back to the audience's underlying goal.\nOutput as a complete ready-to-publish listicle with numbered headers for each item.",
    variables: ["topic", "target_audience", "list_length"],
    complexity: "Beginner",
  },
  {
    category: "Content Generation",
    title: "Email Subject Line Generator",
    body: "You are an email marketing copywriter specializing in subject lines that get opened.\nEmail topic or offer: {{email_topic}}.\nAudience segment: {{audience_segment}}.\nTone constraint (e.g., must avoid spammy phrasing, must match brand formality): {{tone_constraint}}.\nGenerate 8 subject line options, varying the angle across curiosity, urgency, benefit-forward, and personalization styles, keeping each under 60 characters.\nFlag any option that risks tripping spam filters and suggest a safer alternative phrasing for it.\nOutput as a numbered list of subject lines with the angle labeled for each, followed by a top-pick recommendation.",
    variables: ["email_topic", "audience_segment", "tone_constraint"],
    complexity: "Beginner",
  },
  {
    category: "Content Generation",
    title: "Content Localization Adapter",
    body: "You are a localization specialist adapting content for a new market.\nOriginal content: {{original_content}}.\nTarget market and language/locale: {{target_market}}.\nCultural or regulatory sensitivities to watch for in this market: {{sensitivities}}.\nAdapt the content so idioms, examples, humor, and currency/date formats fit the target market naturally rather than reading as a direct translation, while preserving the original core message.\nFlag any claim or example that may raise a cultural or regulatory concern in this market and suggest a safer alternative.\nOutput as: Adapted Content, followed by a 'Localization Notes' section listing each change made and why.",
    variables: ["original_content", "target_market", "sensitivities"],
    complexity: "Advanced",
  },
  {
    category: "Content Generation",
    title: "Thought Leadership Article Drafter",
    body: "You are a ghostwriter specializing in executive thought leadership.\nExecutive's area of expertise and unique point of view: {{expertise_and_pov}}.\nTopic they want to weigh in on: {{topic}}.\nPublication or platform this will appear on: {{publication_target}}.\nDraft an article that opens with a contrarian or non-obvious framing, builds the argument with specific examples or reasoning rather than generic industry statements, and closes with a forward-looking statement that reinforces the executive's expertise.\nMatch a confident, first-person voice appropriate for an executive byline.\nOutput as a complete draft with a suggested headline and a one-line author bio placeholder.",
    variables: ["expertise_and_pov", "topic", "publication_target"],
    complexity: "Advanced",
  },
  {
    category: "Content Generation",
    title: "User-Generated Content Curation Guide",
    body: "You are a community and content manager building a UGC curation guide.\nBrand or campaign this UGC supports: {{campaign_name}}.\nPlatforms where UGC is being sourced: {{source_platforms}}.\nCriteria that matter most (brand fit, image quality, engagement level): {{selection_criteria}}.\nWrite a curation guide defining what makes a piece of UGC worth featuring, a permission/attribution checklist before reposting, and a short scoring rubric reviewers can use to decide quickly.\nInclude 2-3 example scenarios showing how the rubric would be applied to borderline content.\nOutput as: Curation Criteria (table), Permission Checklist, Scoring Rubric, Example Scenarios.",
    variables: ["campaign_name", "source_platforms", "selection_criteria"],
    complexity: "Intermediate",
  },
  {
    category: "Content Generation",
    title: "Content Gap Analysis Report",
    body: "You are a content strategist conducting a content gap analysis.\nTopic area or industry: {{topic_area}}.\nOur existing content inventory summary: {{existing_content_summary}}.\nCompetitor or reference content to benchmark against: {{competitor_content}}.\nIdentify subtopics, questions, or formats the competitors or reference sources cover that our existing inventory is missing or under-serving, and rank the gaps by likely audience demand and strategic relevance.\nFor each gap, suggest a specific content piece (format and angle) that would close it.\nOutput as a ranked table (Gap, Evidence It Matters, Suggested Content Piece, Priority) followed by a short recommended production order.",
    variables: ["topic_area", "existing_content_summary", "competitor_content"],
    complexity: "Advanced",
  },
  {
    category: "Content Generation",
    title: "Interactive Quiz or Content Idea Generator",
    body: "You are a creative content strategist specializing in interactive formats.\nTopic to build interactive content around: {{topic}}.\nAudience and platform where this will run: {{audience_and_platform}}.\nGoal of the interactive piece (lead capture, engagement, education): {{content_goal}}.\nBrainstorm 4-5 interactive content concepts (quiz, calculator, assessment, poll series) suited to this topic and goal, describing the core mechanic, an example question or input for each, and what result or payoff the user gets at the end.\nRecommend the strongest concept given the stated goal and explain why.\nOutput as a list of concepts with mechanic, example, and payoff, followed by a 'Recommended Concept' section.",
    variables: ["topic", "audience_and_platform", "content_goal"],
    complexity: "Beginner",
  },
  {
    category: "Content Generation",
    title: "Content Accessibility Review",
    body: "You are an accessibility specialist reviewing content for inclusive readability.\nContent to review: {{content_text}}.\nFormat it will be published in (web article, social image, video): {{publication_format}}.\nAccessibility standard I need to meet, if any: {{accessibility_standard}}.\nReview the content for reading-level complexity, need for alt text on any described visuals, use of directional language ('see the chart above') that fails for screen readers, and color/contrast dependence in described visuals.\nFor each issue, explain the barrier it creates and provide a corrected version or alt-text suggestion.\nOutput as a table (Issue, Barrier Created, Fix or Alt Text Suggestion) followed by an overall accessibility readiness summary.",
    variables: ["content_text", "publication_format", "accessibility_standard"],
    complexity: "Intermediate",
  },
];
